### ISSUE TITLE
Assigning certain anti-personnel weapons to Battle Armor fails to register

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megameklab#1]
Several anti-personal weapons - for example the Grenade Launcher (Auto) - can be assigned to BattleArmor.  Unfortunately, you cannot drag the weapon onto an arm (showing 0 crits), and when you attempt to auto-assign, the weapon does not mount properly and shows it's listing in the "Body," and isn't usable.

This seems to occur in both Clan and IS BattleArmor.

Steps to Repro:
1) Setup a new battle armor 
2) Add a Grenade Launcher (Auto) to the weapons list
3) Attempt to assign the grenade launcher; note it cannot be dragged
4) Autofill the crits and notice it appears in the body, but does not register.

**Comment by pheonixstorm** [comment]
They should be mounted on an APWM or Armored Glove but after testing this the tooltip only shows them as being able to go on the armored glove. Any other attempt at mounting (such as APWM) fails.

**Comment by BLOODWOLF333** [comment]
MML 0.1.56 I right clicked the grenade launcher and assigned it to the armored glove and it appears to work correctly.

![mml0](https://cloud.githubusercontent.com/assets/16950832/16901294/c5fdda88-4c04-11e6-821b-b2810c301f30.png)
