### ISSUE TITLE
Clan AMS not visible unless tech level set to experimental or above

### ISSUE THREAD

**Issue by Question2** [MegaMek/megameklab#100]
For some reason, clan AMS is no longer visible in the equipment tab unless the tech level is set to experimental or above. This was with the default year of 3145. I tried 3069 as well, but it was still not visible till i set the tech level to experimental or above.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1417067/megameklablog.txt)

**Comment by HammerGS** [comment]
Looks like the simple Tech level was set to experimental by mistake.

**Comment by neoancient** [comment]
This was fixed in MegaMek/megamek@5eac16da.
