### ISSUE TITLE
Printing RS to a file that's open in a viewer results in uncaught Exception

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megameklab#1002]
MML throws an exception when printing a record sheet to a file that is currently open in a viewer (or otherwise write-protected).

**Comment by Windchild292** [comment]
You kinda need the actual exception to take a look at this @SJuliez 😂

**Comment by SJuliez** [comment]
Huh? Can't write to file bla bla. Easy to reproduce, no need to remember.

**Comment by Windchild292** [comment]
It's rather important when there's issues raised elsewhere, and a stacktrace would assist in figuring out if it's the same thing without requiring a computer. It comes up more often that I'd like when it comes to our socials.

**Comment by HammerGS** [comment]
But when it’s a dev opening a bug report so they remember I think it’s a little different. 😉
