### ISSUE TITLE
Reclaiming Crticial Space

### ISSUE THREAD

**Issue by snrdg102417** [MegaMek/megameklab#101]
Per BT TechManual PDF CAT 35002 2007-2013 The Topps Company, Inc. Corrected Third Printing Published by Catalyst Game Lab BattleMech Basics/Space/Reclaiming Critical Space p. 45 BattleMech lower arm and hand actuators or hand actuators may be removed. Megameklab does not have the option available.

**Comment by HammerGS** [comment]
Right click on the Hand or Lower Arm Crit and select remove.

![image](https://user-images.githubusercontent.com/13752452/32152905-86b8252c-bcec-11e7-911a-0aa73663c970.png)

**Comment by snrdg102417** [comment]
Hello HammerGS,

Thank you for the reply and providing the information on how to remove the hand and lower arm actuators. Prior to posting I did try the direction provided of right clicking, apparently I did not, and was not able to get the option box remove hand/remove lower arm.
