### ISSUE TITLE
Cannot generate PDF or print

### ISSUE THREAD

**Issue by phoenixgsu** [MegaMek/megameklab#1011]
### Environment
showInfo : Starting MegaMekLab v0.48.0 ...
	Compiled on Fri Mar 05 09:38:56 EST 2021
	Today is 2022-01-20
	Java vendor Oracle Corporation
	Java version 1.8.0_321
	Platform Windows 10 10.0 (x86)
	Total memory available to MegaMek: 1,013,632 kB

### Description
Cannot generate PDF or print loadouts directly

### Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/7917145/megameklablog.txt)

**Comment by HammerGS** [comment]
Are you printing with a Fluff image. Looks like one of the like a jpeg or jpg is causing issues. Best to try to Export to PDF then print to paper. Also trying converting fluff images to PNG.

**Comment by phoenixgsu** [comment]
> Are you printing with a Fluff image. Looks like one of the like a jpeg or jpg is causing issues. Best to try to Export to PDF then print to paper. Also trying converting fluff images to PNG.

Thanks, I will try that.

**Comment by Windchild292** [comment]
Closing based on the above
