### ISSUE TITLE
MML lets you take Engines on Conventional Fighters you otherwise couldn't

### ISSUE THREAD

**Issue by Logion567** [MegaMek/megameklab#1012]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MML version 0.49.5 Windows, forget what Java i'm using but that isn't the issue.

### Description
![image](https://user-images.githubusercontent.com/98195429/150616962-1fa049c0-8e1e-484e-b2bf-569d5f8c5af9.png)
![image](https://user-images.githubusercontent.com/98195429/150616993-e77112a6-e79d-4f3a-b98f-79161dab633c.png)
The issue here is that, according to the Tech Manual, Conventional fighters cannot take XL or XXL engines, while in version 0.49.5 of MML you can

**Comment by HammerGS** [comment]
Per TacOp AuE pg 121 - Conventional Fighters can use XXL engines. However XL engines will need to be confirmed, and I have a rules clarification into Catalyst for this.
