### ISSUE TITLE
RFE - Display CASE II at the top of a location

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#1016]
v.49.6

On a record sheet's critical table, locations with CASE have (CASE) listed at the top of said location, to the right of the location name.
Units with CASE II do not currently do this. Would it be possible to have (CASE II) be listed in the same way?

**Comment by SJuliez** [comment]
Currently this seems only to be done for Clan base (I think this includes clan base mixed) and indeed not for CASE II, probably based on the notion that in other cases CASE/CASEII is written in a crit slot already. Is the wish to have CASEII additionally noted in the title? In that case the question would be if this should be done for IS as well.

**Comment by AlphaSled** [comment]
Ah, of course. I forgot that IS CASE wasn't put up there either.
It would be great if this were done with every type of CASE, yes. It'd really makes things clearer for the player.

**Comment by SJuliez** [comment]
Does it make sense to _not_ print CASE on Clan units for HD and CT even if it qualifies for auto-CASE (has ammo)?

**Comment by AlphaSled** [comment]
I would say yes, just because there might eventually be rules that benefit from knowing this in some way.

**Comment by SJuliez** [comment]
Eh I take your answer means "Print it even for HD/CT", right? Because I asked if it made sense to NOT print it :)

**Comment by AlphaSled** [comment]
Yeah, sorry, that could have been clearer on my behalf. I think it should be printed even for the HD/CT.
Thanks for bearing with my unclear language :)
