### ISSUE TITLE
MegaMekLab version 0.34.4  File/Export To/Text

### ISSUE THREAD

**Issue by snrdg102417** [MegaMek/megameklab#102]
After selecting File/Export To/Text the Save As dialog box opens and shows the File name as Design Name.html versus Design Name.txt.

**Comment by wildj79** [comment]
I can confirm this behavior is still present even when compiling the code from the repo.

**Comment by HammerGS** [comment]
Fixed

**Comment by snrdg102417** [comment]
I do not know how to get the fix into version 0.43.4 Development Release. The Version 0.42.2 Stable release I downloaded and installed has the same issue when selecting File/Export/to text showing that the saved file is .html rather than .txt. I am very new here and I have not figured out how to make the changes. Would someone please help me in finding out how to do the fix?

**Comment by HammerGS** [comment]
Any fixes added, need to be added by a developer to the source code.  At that points it will make its way into the next release.  Our release schedule varies but if I had to estimate we'll do a release toward the end of November.

**Comment by snrdg102417** [comment]
Morning from WA David N, 

Thank you for letting me know that the next release will probably have many of noted items incorporated and there is a high probability the next one will be at the end of November. 

Tom Rux 

----- Original Message -----
