### ISSUE TITLE
LAM Conversion Equipment tonnage is calculated incorrectly

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megameklab#1023]
### Environment
What version of MekLab does your issue apply to?  **HQ's MekLab 49.6**
What operating system are you using?  **Linux**
What java version are you using?  **openjdk 17.0.1**

### Description
Describe the issue and provide screenshots ingame if able. **LAM conversion equipment is 10% of the mech's tonnage, but unlike internal structure, this is rounded up to the nearest *whole ton*. Meklab doesn't do this rounding, and as a result units like the Waneta appear to have an unused half ton.**
![image](https://user-images.githubusercontent.com/29113974/152303060-2af473f1-95fc-42a3-a68a-b2c58d3994e3.png)
Provide the rulebook, page number, and text if you feel like this is a rules issue. **Interstellar Operations p114**
And provide the steps you have taken to reproduce the issue. **Create a 55 ton LAM, or load the Waneta S-WN-2LAM.**

**Comment by SJuliez** [comment]
To be fixed by MM 3481.

**Comment by Windchild292** [comment]
Resolved in https://github.com/MegaMek/megamek/pull/3481

Also, I noticed you are using JDK 17. The suite does not support it at this time, and it may cause significant issues.
