### ISSUE TITLE
Feature request: Export/Print with warrior data

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#1039]
### Environment
All

### Description
I wish to be able to print out RS (and export PDF RS) with Name, Gunnery skill and Piloting Skill already filled in.
This will also mean that both the original and the skill adjusted BV is shown on the RS.

I can see this now as either having a new or altered prompt or by adding the optional fields to the fluff tab.

This feature will be of use for unique 'Mechs with named warriors. But it will also be an easy and future proof solution for getting the correct BV for Drones which have predetermined skill levels.

**Comment by HammerGS** [comment]
This is out of scope for MegaMekLab. Force building is handled via MegaMek or MekHQ.
