### ISSUE TITLE
MegMekLab 0.43.4 Missing LAM Compact Fusion Engine Option

### ISSUE THREAD

**Issue by snrdg102417** [MegaMek/megameklab#104]
BT Interstellar Operation PDF CAT 35006 2016 The Topps Company, Inc. Printed in USA Published by Catalyst Game Labs p. 114 Engines: LAMs may not use any engine other than a standard or a
compact fusion engine and cannot mount a supercharger.

**Comment by HammerGS** [comment]
What year and tech level do you have set?  Those setting have a huge impact on what equipment shows.

![image](https://user-images.githubusercontent.com/13752452/32330521-f9fac43e-bfa5-11e7-9e63-1ea489d2024f.png)

**Comment by snrdg102417** [comment]
Hello Dave N, 

Background: On the Heavy Metal Pro site a contest is being run to convert the Hollander BZK-F3 into a LAM. Loading the Hollander's data from cache I did not see that the Date was 3054 because the Source/Era is TRO 3055 - Clan Era. Selecting LAM automatically selects Experimental. 

My apologies for not catching the date was not set correctly. 

Tom Rux 

----- Original Message -----
