### ISSUE TITLE
Feature request: Unsaved indication/warning

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#1040]
### Environment
megameklab-windows-0.49.7 (and before)

### Description
Currently MegaMekLab doesn't give any indication if a design has been saved, in fact MegaMekLab can be closed without it even giving a warning that the design has yet to be saved.

**Comment by Windchild292** [comment]
I'm going to do this in the same vein as MM and MHQ, namely having the exit dialog have three options: Save, Don't Save, and Cancel.
