### ISSUE TITLE
Space Station check box "Modular"

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#1041]
### Environment
megameklab-windows-0.49.6 (just unchecks the boxes)
megameklab-windows-0.49.7 (now also an error message when checking/unchecking Military, see pic)

### Description
Several construction options for Space stations are implemented with check-boxes (Sail, Military, Modular), however if a saved design is loaded from file then both Military & Modular options will be unchecked. Also the construction options are not noted on the RS.

Also _Modular_ is not the best term for the last option as:
- Modular Space Station option should only be available for Space Stations larger than 100kt, see IO p117: "Any space station designed to have a final total mass of more than 100,000 tons may be built as a modular space station.....  In essence, a modular space station receives 1 K-F adapter for every 100,000 tons of station mass (or fraction thereof)."
- For smaller stations the option should be K-F Adapter (IO p105)  "K-F adapters may be installed on any space station of 100,000 tons or less."

### Files
![ss1](https://user-images.githubusercontent.com/43098653/154780173-aea4a325-a7ec-4da0-9c33-7bcd2c47c52c.jpg)

**Comment by SJuliez** [comment]
The checkboxes work. The modular/KF-Drive issue is still open.
