### ISSUE TITLE
Missing CV equipment

### ISSUE THREAD

**Issue by Dropskiler** [MegaMek/megameklab#1045]
### Environment
MegaMek Version: 0.49.7
Java Version: 15.0.2
Platform: Windows 10

### Description
Some Combat Vehicle equipment types seem to be missing from "others" tab. This isue persists regardless of selected tech level.
Vehicle Chassis Mods seem to be partialy missing as well as sponson turrets.

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/8110704/megameklab.log)

**Comment by gsparks3** [comment]
### Reproduction Steps
Open a "New Combat Vehicle" in MML 49.7. Default year is 3145. Go to Equipment tab, CTRL+click "Other" to view this exclusively and deactivate "Hide Unavailable". Some items are not visible in this view.

"Backhoe" item (and other industrial equipment with physical attacks such as Chainsaw, Dual Saw, etc) are available, but only when choosing "Show All", not "Other" or any other single category or manual combination of categories.

"Combat Vehicle Chassis Mod [Environmental Sealing]" does not appear at all.
"Vehicular Sponson Turret" does not appear at all.

All other items from the "Other" category in 48.0 appear to be present, although some have changed categories (e.g. AMS is now under Ballistic, and Laser AMS is now under Energy) or had their names slightly adjusted.

**Comment by HammerGS** [comment]
Did some poking around and think it's a mix of flag issues on the equipment and the other filtering in MML. But not sure the best approach to fixing.
