### ISSUE TITLE
0.47.9 Graphics glitch

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#1047]
The following graphical glitch occurs either after multiple pdf batches are created, or when dealing with very large lists of weapons (such as with large spacecraft units). Moving over buttons or changing selections causes these ghost images to appear, making the program effectively unuseable unless it is restarted.
![Bug](https://user-images.githubusercontent.com/34638413/155433561-1d594881-8f98-49b2-87bf-83dfd78a7549.jpg)

**Comment by HammerGS** [comment]
Please try the fix under Artifacts and Screen Distortions
https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by neoancient** [comment]
Closing due to lack of followup about suggested fix.
