### ISSUE TITLE
Add 'Generator' key to .mtf format

### ISSUE THREAD

**Issue by IsaBison** [MegaMek/megameklab#1061]
Given that .mtf is effectively an interchange format, it would be helpful if .mtf files include an optional `Generator:` key with a value indicating the program that generated the file along with the version of that program.  

e.g. `Generator:MegaMekLabv0.49.7`

As far as I can tell, the location of the key in the file need not be specified but it might be ergonomic to place it at the beginning or end. 

(edited to note the key would be optional.)

**Comment by MordelBlacknight** [comment]
Sounds like a solid plan to me! Information is power. What I'd really love to see is a standardized XML Schema for unit files. That would be very powerful and would allow for the sharing of units across various apps and platforms.

**Comment by HammerGS** [comment]
We've recently also added the MUL ID to the unit files. But I'd support having a what version of MML it was made. But I don't think we'd be able to go back and figure that out.

**Comment by IsaBison** [comment]
> We've recently also added the MUL ID to the unit files. 

Innnteresting...

> ...But I don't think we'd be able to go back and figure that out.

Just to clarify, are you saying it'd be prohibitive to add that key to existing documents (for sure), or that it'd be prohibitive to change the output format such that future documents would include that key, or more specifically that including a version in the value for that key would be prohibitive?

If it helps, I did not mean to suggest that an accurate value for the key be included in the existing library (e.g. this archer was originally made in v0.36.22) (woof!) only that new files (especially user generated ones) include it moving forward.

**Comment by IsaBison** [comment]
> Sounds like a solid plan to me! Information is power. What I'd really love to see is a standardized XML Schema for unit files. That would be very powerful and would allow for the sharing of units across various apps and platforms.

I think a format joined with a schema of some kind would be pretty nice but if you want that in XML specifically you may need to dance with stakeholders who'd prefer JSON...

**Comment by MordelBlacknight** [comment]
> > Sounds like a solid plan to me! Information is power. What I'd really love to see is a standardized XML Schema for unit files. That would be very powerful and would allow for the sharing of units across various apps and platforms.
> 
> I think a format joined with a schema of some kind would be pretty nice but if you want that in XML specifically you may need to dance with stakeholders who'd prefer JSON...

JSON works as well. I'm pretty flexible. I just want something definable and reusable across solutions.

**Comment by gblouin** [comment]
I am adding Generator: to the output and will have it take place of the existing "Version: 1.1" that is hard coded and gives less value then the new field will.

**Comment by IanBellomy** [comment]
You don't say!

**Question:**
When changes to the MTF format happen are old library files piped through MML in some sense to produce the new files, or are they modified as raw source?

If it's the _latter_, it occurs to me that it may be valuable to have a value for 'Generated' for the MML library files that indicate they were not, in fact, exported or saved-as from MML, but are essentially raw files within some version of the MM source, manipulated in whatever environment the developer is using to make changes.

**Comment by gblouin** [comment]
SSW and SAW has it's own export code that generates a formatted file with a .mtf extension on it.  Since they are just text...we matched the format.  This change will NOT regenerate all mtf files...users would have to do that themselves.

**Comment by SJuliez** [comment]
@gblouin Please note that the Generator keyword will be used also by MM. Additionally, MTF files no longer use the "Version:" line but now use chassis: and model: keywords (meaning that chassis and model no longer have to appear in fixed order at the beginning of the file). Also, MTF files now store the combat role using role: and quirks using quirk: and weaponquirk:
The mtf reader is backwards compatible and will shortly be changed to make it read MTFs from SSW 0.7.6.1
