### ISSUE TITLE
[0.49.9-672] Cannot export or print from MML

### ISSUE THREAD

**Issue by kernhe** [MegaMek/megameklab#1068]
### Environment
V: mekhq-0.49.8-692
S: x86_64 GNU/Linux (Ubuntu 20.04.x)
J: openjdk version "11.0.14" 2022-01-18

### Description
When you want to export a mech to pdf or you want to print one, you'll end up with a dialog telling you, that "A problem has occured" .... "java.lang.NullPointerException"

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/8310802/megameklab.log)

**Comment by Windchild292** [comment]
This is actually two issues, missing null handling in MML and a build script issue in MHQ. I'll handle both fixes, but close this as part of the MML fix.
