### ISSUE TITLE
Equipment Tab Not Drawing

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megameklab#107]
0.43.5

Open MML > Click Equipment Tab

The Tab doesn't draw correctly. Works fine in MHQ when choosing Refit.
Attached Screenshot and MML log showing errors with IS ERLL and Autocannon Damage Options. Tried with those Options turned off as well.

[MML Equipment.zip](https://github.com/MegaMek/megameklab/files/1478991/MML.Equipment.zip)

**Comment by scJazz2** [comment]
Works fine when downloaded and launched as a standalone.

**Comment by Qwertronix** [comment]
Seems to be something MHQ's ant packager does to the files. Running Java 9 I also get the "Java Exception has occurred" error message when trying to launch the MegaMek.exe that gets bundled with MHQ, but MM works fine as a standalone before MHQ packaging, and both work fine if I overwrite MHQ files with the MM and MML standalone files afterwards.

**Comment by Dylan-M** [comment]
We don't support Java 9 yet, just FYI. There are known issues.

https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by neoancient** [comment]
You say it works fine when doing a refit within MekHQ and when downloaded and launched as a standalone. Am I correct in understanding that the problem is present when running the MML jar that was included in the MekHQ package? Does it happen every time?

**Comment by scJazz2** [comment]
I am closing this issue as it no longer occurs in 0.43.5.

It existed in the Beta.
