### ISSUE TITLE
Can select dates with invalid core availability

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megameklab#1076]
I first selected an Archer ARC-2R, then manually changed the year to 2000. This breaks the Summary Availabilities, as per the below image.
![image](https://user-images.githubusercontent.com/39067288/160303708-d606aa21-e72d-49b7-b4ff-09113f2a987e.png)

This may be because of #1077, but shouldn't be possible in general.

**Comment by neoancient** [comment]
This is no longer happening.
