### ISSUE TITLE
File | Export to Clipboard (missing elements)

### ISSUE THREAD

**Issue by donlindsay** [MegaMek/megameklab#108]
Some elements missing, like the Head location in the Armor table. Also, some of the items you get in the preview pane.

Version 0.43.4

**Comment by HammerGS** [comment]
We would need to see a screenshot

**Comment by donlindsay** [comment]
On the right side is the paste operation on the clipboard after selecting the File | Export | to Clipboard (text)

[https://i.imgur.com/ZL8Duyp.png]( https://i.imgur.com/ZL8Duyp.png)
