### ISSUE TITLE
(0.49.7) Java Index out of bounds

### ISSUE THREAD

**Issue by Janaszar** [MegaMek/megameklab#1082]
I did a search for this issue/related, found something from 2021 that mentioned the same error, but was, as far as I can tell, unrelated.
Error popup: Uncaught java.lang.IndexOutOfBoundsException detected.

### Environment
Using MekLab 0.49.7, standalone (I think; this is using the MegaMekLab.exe, not the MekHQ.exe)
Windows 10 
Java 17.0.2 JDK

I had just updated to the new 0.49 MegaMek package, and downloaded Java 17 JDK the past few days.
I copied over several mech design files from the data\mechfiles of the old install to the new install.

### Description
Launched MekLab, selected "Load existing unit", selected something (first time was a custom unit, second time was a Marauder II)
On loading the mechlab window, popup saying "java.index.outofboundserror" (or something close to that) popped up, with mention to submit logs here for a bug/issue.
I attempted a few times to reproduce it for a screenshot, but most times it failed to occur again.  Though, while writing this, I attempted again (to grab a screenshot, below), and now it's happening somewhat regularly, but it seems certain mechs (Patron Loadermech) don't trigger it?  I don't think it's related to the units, it seems to "come and go" on certain units (Shugosha PTN-LAW, for example).

![image](https://user-images.githubusercontent.com/32232509/161444865-7b441190-7dee-44d8-8e3c-66f18f8f9abb.png)

Reproduce:
Open MegaMekLab, Load Existing Unit, select...
Well, this part is annoying; I wanted to use the Shugosha, but that's now "working".  The Exo HaulerMech HMX-1 has it happen now.
I'd guess "select a unit and continue to the mechlab screen".

### Files
Hope these are the right file for the log: 

Log 1: [megameklab.log](https://github.com/MegaMek/megameklab/files/8405330/megameklab.log)
Log 2: [megameklab.log](https://github.com/MegaMek/megameklab/files/8405340/megameklab.log)

**Comment by Janaszar** [comment]
Oh, right, forgot to mention:

Can click through the error, seems like nothing is "wrong"/Mechlab works from what I can tell (though I'm not doing anything "complex").
That is, it's not freezing, I can select dropdown menus, adjust weight and movement...

**Comment by HammerGS** [comment]
We don't support Java 17 and for the programs to run without issues you'll need to only use Java 11.

**Comment by Janaszar** [comment]
Ah, ok.

Closing this then.
