### ISSUE TITLE
[49.8] Infantry specialisations result in additional weight

### ISSUE THREAD

**Issue by mwberlindeu** [MegaMek/megameklab#1083]
**Environment**
MegaMekLab version: 49.6

**Description**
Adding infantry specialisations adds weight in some cases. The following specialisations are not affected:
- Marines
- Mountain troops
- Xenoplanetary condition
All other specialisations add weight.

I have briefly look of in the Tech manual and TacOps but did not see a reference that this additional weight is actually in the rules (but I may have missed it). In previous versions of MegaMekLab no weight was added if I remember things correctly. 

![Infantry specializations](https://user-images.githubusercontent.com/28268113/162567763-2024c8ab-3835-46ff-8b70-ff3aa71abfa3.png)

**Comment by mwberlindeu** [comment]
Rechecked in 49.8: Behavior is the same as in 49.6

In addition various Specialisations are now invalid, except:
- Marines
- Paratroops
- Xenoplanetary Condition-Trained Troops

Note that weight addition above and design invalidity are not identical.

**Comment by HammerGS** [comment]
This is covered in TacOps:AuE pg 153. Any Engineer, Paratrooper, or Paramedic will add weight due to specialized equipment they need. SCUBA adds when you select the motive type.

**Comment by mwberlindeu** [comment]
Thanks, I corrected all custom units in 49.8. Sometimes I got an "invalid" message but I could not repeat such situations to find out the reason.
