### ISSUE TITLE
Sub-Cap weapons cannot be added to capital bays of the same type

### ISSUE THREAD

**Issue by Logion567** [MegaMek/megameklab#1086]
MML version .49.7
Windows 10
latest Adoptium

these are 2 issues with Warship construction. 

no matter what unit availability settings i have Screen Launchers do not appear. 
![screen launcher](https://user-images.githubusercontent.com/98195429/162659107-0083b60f-85a0-4e3b-8038-17c0a3e19fa3.png)

also even though there is open room for it, MML won't let me add Sub-Cap ACs/Lasers to a full scale-capital weapon bay. it only gives the option for making a new Sub-Cap weapon bay, even though it is an option in TacOps. ![Sub Cap Weapons](https://user-images.githubusercontent.com/98195429/162658981-b63e79a5-990b-45fd-89f6-7b180ee890b7.png)

**Comment by SJuliez** [comment]
Screen launchers do appear in the latest dev version; therefore changing the name.
