### ISSUE TITLE
Naval/Hydrofoil/Submarine Combat Vehicle cannot have Lifeboat

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#1088]
### Environment
Ver 0.49.7

### Description
Naval, Hydrofoil, Submarine Combat Vehicle can use **Lifeboat** by 277, TechManual, but it is not on the list of valid other equipment. If you load the vehicle with this type and has a lifeboat or more, MegaMekLab says the unit has invalid equipment.

These units are not able to choose the number of life boat on Structure/Armor tab unlike dropship/small craft and jumpship/warship/space station either.

**Comment by Windchild292** [comment]
This is according to Tech Manual, 6th edition, pg 227.
