### ISSUE TITLE
New Mek, File-> Save As option does not provide user with the correct file extension

### ISSUE THREAD

**Issue by larret** [MegaMek/megameklab#1107]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MegaMekLab 0.49.7

### Description
MegaMekLab -> (Main Menu) -> New Mek 
File menu -> Save As
The correct file extension i.e. mtf , is not suggested to the user, and hence Loading (File -> Load -> From File) the same file (with no extension at all) later, a user may receive error message stating "Unsupport file suffix" .

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/8711925/megameklab.log)

**Comment by SJuliez** [comment]
On Windows, I can't reproduce this. For me, a new Mek unit will reliably show New Mek.mtf as the suggested file name, both as the window title of the MML main window and when trying to save it either with Save or Save As.

**Comment by HammerGS** [comment]
The only time I've seen this is if I'm working on multi units in a row and sometimes the .mtf extension disappears (or I've deleted it). But only in this very specific circumstance.

**Comment by Thanat0sNihil** [comment]
![image](https://user-images.githubusercontent.com/37569877/224578440-e2ee747b-0166-4f10-b744-bf6c808c04d7.png)

This occurs for me 100% of the time on a Windows 10 machine with the following jdk version, on both 49.11 and 49.12:
![jdkver](https://user-images.githubusercontent.com/37569877/224578468-2ed8442d-e030-49a7-a05b-74069ef8f63b.png)
