### ISSUE TITLE
49.8 Docking collars improperly listed in blk files, not appearing on ship

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#1110]
Attempting to mount docking collars on WarShips (probably others as well) does not work in this version. They will appear in the display, but disappear when the ship is next loaded and do not appear on the record sheet if exported without loading.

Doing a little digging, this is because mml 49.8 changed the data tag in the blk file from "dockingcollar" to "Docking Collar", which the program doesn't seem to recognize. Manually changing every instance of "Docking Collar" in the blk to "dockingcollar" allows a record sheet to be exported with the docking collars correctly displayed, but as soon as you open, edit and save the file again in 49.8 you're right back where you started.

**Comment by silver2191** [comment]
was trying to make a custom space station and jumpships and is having the same problem.

**Comment by HammerGS** [comment]
Have a few confirmations of this on the Discord.
