### ISSUE TITLE
[49.8] Omni Units - Equipment Adding as Fixed Instead of Omni

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megameklab#1124]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
	Build Date: 2022-05-27T12:45:51.888427300
	Release Date: 2022-02-18
	Today: 2022-06-07
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 8 GB

### Description
When adding equipment to locations on an Omni unit (tested on mech, tank, and aerospace) it is adding the equipment as "fixed" by default instead of Omni, and I have to right click -> change to pod mount on every single piece of equipment, which gets extremely tedious very quickly.

### Files
![FixedEquipment](https://user-images.githubusercontent.com/101755917/172408566-076f4484-56f4-4652-bca5-8a463b494273.PNG)

**Comment by HammerGS** [comment]
As mentioned in Discord, design choice and not something we'll change.
