### ISSUE TITLE
Disappearing structure and armor crits when adding lower arm and hand actuators 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#1137]
I was customizing a Night Gyr and wanted to add lower arm and hand actuators.  With autofill unhitables enabled, the lower arms displaced unhitable crits to other locations, while the hands made the unhitables they replaced completely disappear.  Despite this, the design still passed validation even though a FF armor crit and an ES crit was missing.

**Comment by neoancient** [comment]
This is the same underlying issue as #1121.

**Comment by neoancient** [comment]
Fixed by #1138
