### ISSUE TITLE
Uncaught Exception when trying to add endo-steel to a Hellbringer Prime 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#1152]
As title says.  Log file attached.

[MMLUncaughtException.zip](https://github.com/MegaMek/megameklab/files/9177530/MMLUncaughtException.zip)

**Comment by HammerGS** [comment]
Pretty sure it’s fixed with this https://github.com/MegaMek/megameklab/pull/1138

**Comment by neoancient** [comment]
Yup. Same issue.
