### ISSUE TITLE
RFE make 'auto fill unhittables' and 'auto compact' saveable  option

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#1156]
### Environment
Ver 0.49.8

### Description
This makes me headache all the time when I design a mech. It is always active when I start one and I have to disable both of them manually each time. Isn't it need to be active all the time? I think that it should be turned off by default, for it puts the unhittables through where I want to put the equips and forces to change the location of the equips when I remove it on the location. It is more a problem than a handy addon.

**Comment by HammerGS** [comment]
The current code follows the guidelines we’ve been provided to determine crit placement. 

We need more details to determine if it’s a bug or simply a feature that isn’t liked.

**Comment by foij00** [comment]
Seconding request.  MML now autofills unhittables before you even have a chance to place other crit items, like weapons, heat sinks, etc.  It forces me to turn the autofill off before adding anything from the equipment tab.

**Comment by gsparks3** [comment]
> it puts the unhittables through where I want to put the equips

Just to check ... you're aware that when this change was made, it was also set up so that dropping an item "into" a slot containing a roll-again crit will automatically move that crit somewhere else, right? You can just drop your equipment wherever you want it, and the "unhittables" will automatically move out of the way as needed.

**Comment by foij00** [comment]
Thanks for the info, that helps.  However, I most frequently use MML to build canon mechs from official record sheets (before those units get uploaded to Megamek in a dev release), and I'd prefer not to 'chase' the unhittables around the mech to drag them to the correct position as listed on the canon record sheet.  I also figured out that turning off autofill and then using the reset button gets me what I want as well.

**Comment by binaryspica** [comment]
Yes it doesn't allow me to place it where I want. Also just fill the space that what I want by default is very annoying as well. Why it is automatically and cannot be disabled by default? If you really want to fill it automatically you can just hit 'Fill' button once. But for now it makes me to manually click 'Auto Fill Unhittables' and 'Auto Compact' manually to disable it each time I edit a mech.

**Comment by HammerGS** [comment]
While I use these and they do take some getting used too. I’m seeing continuous comments and requests around these. 

Could we look into making them an option that is saved?

**Comment by Sleet01** [comment]
@HammerGS I'd like to take a stab at this, targeting 0.49.15, if that's okay?

**Comment by HammerGS** [comment]
> @HammerGS I'd like to take a stab at this, targeting 0.49.15, if that's okay?

Sounds good.

**Comment by Sleet01** [comment]
^^^ This should have gone into a different PR; I'll see if I can tease them apart.

**Comment by SJuliez** [comment]
Closing this as the selection of those buttons is persistent now.
