### ISSUE TITLE
Intro date check: Heavy Ferro-Aluminum Armor 0.49.8

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#1158]
I was building a dropship rated for standard tech for 3053.  Heavy Ferro-Aluminum armor was selectable from the armor type dropdown despite Sarna.net putting its intro date "in the early years of the Jihad".  I don't have book with intro dates to verify this, but Sarna seems to indicate that Heavy FA introduction was at least around 3067 and not in the 3050s.

**Comment by HammerGS** [comment]
Per IntOps it’s introduced in 3056 +/- 5 years as experimental if using variable tech option. 

If not it’s considered Standard tech with the same intro years. 

For maximum granular detail we recommend using Variable Tech level to see the progression. But this does fit better for RPG campaign style play.
