### ISSUE TITLE
Incorrect Infantry weapon damage values.

### ISSUE THREAD

**Issue by Boret98** [MegaMek/megameklab#1160]
Using Standalone version of MegaMekLab 0.49.8 on Windows 11. 

When equipping an infantry unit, certain weapons damage values do not match those shown in the damage column. 
For example an infantry platoon equipped with ONLY "Rifle (Federated-Barrett M42B)" should have a damage per trooper value of 1.02 but it has a value of 0.6 as shown in the picture
![image](https://user-images.githubusercontent.com/65916377/186186493-c3ec7282-9f84-4d0e-93f8-dc43d38cc0dd.png)

Infantry weapon damage can be verified in page number 350 of the TechManual (2020 version)

**Comment by gsparks3** [comment]
This is not a bug, but rather implementation of a recent errata.
![image](https://user-images.githubusercontent.com/59574316/186189636-bca6266b-833a-4c52-95f1-01f088a9d38e.png)

**Comment by HammerGS** [comment]
We still need to show the weapon damage but as gspark3 says it's now capped per errata.
