### ISSUE TITLE
Black Knight BLK-NT-4D and Medium Shield.

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megameklab#1162]
49.7

Odd issue with MegaMek data. I printed a sheet for the Black Knight BLK-NT-4D which has a medium shield. Per TO:AUE medium shields have a DA of 5 and a DC of 18, but the sheets shows a DA of 4 and a DC of 17.

**Comment by HammerGS** [comment]
[Black Knight BLK-NT-4D.pdf](https://github.com/MegaMek/megameklab/files/9440608/Black.Knight.BLK-NT-4D.pdf)
Tested and can confirm. 

Shield values are correct in the fields below in MiscType.        
- misc.baseDamageAbsorptionRate
- misc.baseDamageCapacit

Sample RS
[Black Knight BLK-NT-4D.pdf](https://github.com/MegaMek/megameklab/files/9440615/Black.Knight.BLK-NT-4D.pdf)

**Comment by strategoslevel3** [comment]
So they are correct in the game but the sheet exports incorrectly?

**Comment by HammerGS** [comment]
It appears so.

**Comment by AlphaSled** [comment]
Wait, no, please don't correct this. This is working as intended, we previously had a ticket to make sure the sheets export this way.
Per TacOps:AU&E p.100, DA and DC are reduced by one with each missing actuators.

**Comment by HammerGS** [comment]
Thanks AlphaSled

**Comment by strategoslevel3** [comment]
No - this is not what it says. TO:AUE pg 103 

“ Critical hits to the shield subtract 1 from the DA and 5 from the DC, while hits to the actuators of the arm mounting a shield subtract 1 from DA and 1 from DC (double for the shoulder).”

It does not say missing actuators.

**Comment by pheonixstorm** [comment]
@HammerGS  @strategoslevel3 

Construction Rules p100
Shield: Shields come in Small, Medium and Large sizes, and may only be mounted in arm locations. Regardless of size, only 1 Shield may be mounted per arm. Shields
have no special actuator requirements, but each missing arm or hand actuator in the arm containing the shield reduces its DA and DC by 1 (see p. 103). Shields are
hard-mounted, and so Shield-based movement modifiers apply to the unit at the time of construction.

This should clear it up.
