### ISSUE TITLE
Record Sheet Change Request - Engine Ratings

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#1169]
This ticket is a request to add engine ratings to all applicable unit types. 

The change would largely be to facilitate gameplay when using certain core or optional rules such as with trailers, booby traps, and engine explosions, reducing the number of products a player needs to bring to the table when using said rules.

Ideally, to avoid player confusion, the engine rating would be listed on a new line for 'Mechs rather than being put on the crit table. This could take the same form as it currently does for vehicles, meaning that a 'Mech's engine would appear below its ammo as (for example) "Engine Type:  300 XL" Note that this change would demand the creation of a new engine type line for aerospace units, as their engine is not currently listed. This could appear in the same place as where engines are listed on vehicles.

**Comment by SJuliez** [comment]
Is this the desired result:
![image](https://user-images.githubusercontent.com/17069663/199693132-1c9399b4-fbb7-4365-8043-bf412d86662e.png)
![image](https://user-images.githubusercontent.com/17069663/199693163-f364a9ef-b683-41df-91eb-f2357aae93cf.png)
![image](https://user-images.githubusercontent.com/17069663/199693245-a96352b7-c6cc-4cb7-a38c-e1b6270708f8.png)
![image](https://user-images.githubusercontent.com/17069663/199693274-133f5deb-ee80-43bd-9429-171c69b8e397.png)

**Comment by AlphaSled** [comment]
Yep, that's fantastic! Thank you!
