### ISSUE TITLE
VTOL Jet Booster not showing

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#117]
Per this Reddit post 
https://www.reddit.com/r/battletech/comments/7j65m7/vtol_jet_booster_in_megameklab/

I checked it out in MiscType and everything looks ok, posting here for someone to double check the MML code.

Nothing in the logs.

**Comment by neoancient** [comment]
Superchargers and VTOL jet boosters are implemented as variant types of MASC. The equipment tab filters out any MASC equipment that is not a supercharger, but didn't provide the same exception for the jet booster.
