### ISSUE TITLE
Conflict between XLFE, NullSig, and CLPS

### ISSUE THREAD

**Issue by RogueRougeRout** [MegaMek/megameklab#1171]
### Environment
0.49.10 Standalone/MekHQ Package
Windows 10
Java Version: 11.0.16

### Description
When changing engine type (standard, xl, xxl, etc.) after adding both NullSig and Chameleon LPS the program doesn't update the critical slots correctly and provides an error. It doesn't update the cost so it is likely failing to change the engine type all together.

### Files
<img width="1920" alt="Pre Change 1" src="https://user-images.githubusercontent.com/113552175/190265699-0618470f-21aa-4efc-9d93-cc7255f4c964.png">
<img width="1920" alt="Pre Change 2" src="https://user-images.githubusercontent.com/113552175/190265707-f8a4ee0f-90e9-42fb-9f9d-9ee6e2152bd6.png">
<img width="1920" alt="Post Change 1" src="https://user-images.githubusercontent.com/113552175/190265722-fee2d9cc-f4a2-4435-9de2-d8e7b5a0bab3.png">
<img width="1920" alt="Post Change 2" src="https://user-images.githubusercontent.com/113552175/190265734-845cb223-d0c7-4dc6-ae1b-cc0c2ea8fdc1.png">
[megameklab.log](https://github.com/MegaMek/megameklab/files/9570086/megameklab.log)

**Comment by Thanat0sNihil** [comment]
Issue still exists in 49.11 and 49.12, also effects Void Signature System. Can consistantly reproduce by adding one the listed stealth systems to a mech and then changing from whatever engine the mech has at the time the stealth system was added to one one that takes up more crits in side torsos (so XL->XXL also works). at least some of the time this will also result in crits from the stealth systems disappearing, persistent across reloading the .mtf
![missingvoidsig](https://user-images.githubusercontent.com/37569877/224579482-80e5b201-7604-4732-8dab-78cbc020a43b.png)


[megameklab(1).log](https://github.com/MegaMek/megameklab/files/10952329/megameklab.1.log)

example .mtf with missing crit, converted to .txt for github:
[Shadow_Fox_SFX-1.txt](https://github.com/MegaMek/megameklab/files/10952330/Shadow_Fox_SFX-1.txt)
