### ISSUE TITLE
Record Sheet Change Request - Armor Types and Vehicles

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#1176]
Vehicles currently only display their armor type if it has a direct effect on core gameplay; eg: reflective armor.

However, displaying all non-standard armor types will facilitate the usage of certain optional rules (Acid warheads, for example) while allowing for more accurate campaign-level play. As such, I'd like to request that all armor types except for "Standard" be printed on vehicular record sheets.

**Comment by AlphaSled** [comment]
If this is looked into in the future, I'd like to add a p2 if isn't too much to ask.

Special armor/structure types are currently a bit hard to see on record sheets. If possible, framing the text (and moving/enlarging it one vehicle record sheets) would help fix this.

What things currently looks like: 
![Capture](https://user-images.githubusercontent.com/17106678/197239601-c6c9ec11-efab-4c9e-bfd6-b044a67df5a1.PNG)

A (poor) mock-up of what I'm envisioning: 
![Capture2](https://user-images.githubusercontent.com/17106678/197239703-a02bb726-1dbc-48b7-9eab-1ea961311f09.png)

If BattleMech armor and structure could be treated the same way as well, that'd be absolutely fantastic.

**Comment by AlphaSled** [comment]
And to expand on this further, would it be possible to change the armor type on vehicles from "Ballistic" to "Ballistic-Reinforced" for consistency versus 'Mech sheets?

**Comment by SJuliez** [comment]
I opted for the grey background if that's ok. I could try giving it the diamond edges.
![image](https://user-images.githubusercontent.com/17069663/200114005-5a09aa51-a4db-45a3-893b-035c71eaa0c0.png)

Note that on US paper format I'll have to move the unit drawing downwards as there's no space below "ARMOR DIAGRAM". Same for Meks (and possibly others).

**Comment by AlphaSled** [comment]
Will moving the art downwards create any cascading issues? For example, will it force any other text to be moved, or force the art/some text to be shrunk?

Otherwise that's really great, thank you for tackling this! Grey is perfectly fine for the background, but I do think that diamond edges would be fantastic (if possible, and if it's not too much work) to maintain visual consistency with the box above it.

**Comment by SJuliez** [comment]
Is it acceptable to display Standard Armor like this:
![image](https://user-images.githubusercontent.com/17069663/202297955-4e48335f-0413-43e2-bc29-b76a55a901d3.png)
Otherwise I'd have to look how to remove the grey background.

**Comment by SJuliez** [comment]
OK the ISO/A4 are done, I only had to move the quadvees, one vtol and one vehicle armor image by a few pixels without any other issue. Now on the US letter, the fun begins; on fighters, I'll have to move the "ARMOR DIAGRAM" and the armor type by a few pixels upward (and to the side to accomodate the centered armor type, same as on A4):

![image](https://user-images.githubusercontent.com/17069663/202306321-962d076a-0d9d-4006-8e35-b5af45f1ceb9.png)
to
![image](https://user-images.githubusercontent.com/17069663/202306129-60f8f561-ed5b-45ef-be04-c2694e33f9c0.png)

**Comment by SJuliez** [comment]
Here it's getting difficult:
![image](https://user-images.githubusercontent.com/17069663/202307193-fbb02900-db21-4b05-ad46-c442b808823b.png)
I could try moving the Rear Armor () to the side so I can move the whole unit silhouette down. Happy to get input.

**Comment by HammerGS** [comment]
I think shifting the Rear Armor to the left side of the tail boom, then shift back a little.

**Comment by AlphaSled** [comment]
Yep, that suggestion for VTOL sheets entirely works for me.
The text shift on fighter RS also looks good.

**Comment by SJuliez** [comment]
For this one I would scale down the armor diagram by about 5% if that's alright: (this is the dual turret, standard weight RS, I've changed the Xuan Wu to have dual turrets for testing)

![image](https://user-images.githubusercontent.com/17069663/202751659-760259ba-457c-4efa-9c2a-40d80fca77c2.png)

![image](https://user-images.githubusercontent.com/17069663/202751594-deb19995-28ae-42ff-a3bd-1abb1a2818dd.png)

**Comment by AlphaSled** [comment]
Yeah, that looks entirely fine. Compromises do have to be made for this to work, and I think that's the best path to take here.

**Comment by AlphaSled** [comment]
Having just given this a test run, this looks absolutely fantastic. A full heartfelt thanks for your work on this, Juliez.

Would it be unreasonable for me to request one final addition? If you have time and/or energy, it'd be for composite and reinforced structure to be highlighted in the same way on 'Mech record sheets.

**Comment by HammerGS** [comment]
Just to clarify the same gray style replacing the existing text.

**Comment by AlphaSled** [comment]
Yeah, spot on. Thank you, Hammer.
