### ISSUE TITLE
Plasma Rifle -- Unneeded (IS) Label

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#1179]
v.49.10

The Plasma Rifle is currently labelled with a (IS) tag on Mixed design record sheets.
Would it be possible to delete this tag, as no Clan Plasma Rifle exists?

**Comment by gsparks3** [comment]
MML currently has an unofficial Clantech "Plasma Rifle" (that doesn't really work the same way as the IS Plasma Rifle anyway). Might be easiest to just remove it.
