### ISSUE TITLE
Clan CASE Costs and BV Calculation

### ISSUE THREAD

**Issue by snrdg102417** [MegaMek/megameklab#118]
When reviewing a Clan's Mech carrying explosive ammo the Validate/Cost Breakdown/Breakdown Current Unit does not appear to shoe the CASE cost even though the BV Calculation has a zero (0) for Explosive Weapon/Ammo Penalty.

"BT TechManual PDF CAT 35002 2007-2013 The Topps Company, Inc. Corrected Third Printing Published by Catalyst Game Lab under Step 1: Calculate Defensive Battle Rating right column are directions for handling explosive ammunition and Gauss weapons, pp 302-303 referencing CASE*.

Page 303: The requirements with asterisks (*) has the following note: "* – It is assumed Clan ’Mechs have CASE installed. If the design specifically did not pay the C-bill cost to install CASE then treat a Clan-built ’Mech as an Inner Sphere ’Mech for the purpose of these calculations."

The Asterisk (*) note appears to confirm the details provided on TM p. 210 that Clan units, with the exception of ProtoMechs, are presumed to automatically fitted with CASE in all location that store explosive ammo or explosive equipment (such as Gauss Weapons).

Is the cost of Clan CASE being included in the Cost Calculations?

If the cost of CASE is included which component is it added to?

**Comment by neoancient** [comment]
The cost calculations were not accounting for CASE. It is now listed in the equipment section.

**Comment by snrdg102417** [comment]
Hello neoancient,

Thank you for checking on the CASE cost and not having the system included in the equipment readout. However, I do have a related based on the italicized portion of the Catalyst Game Labs instructions on p. 303 which is 

The requirements with asterisks (*) has the following note: " – It is assumed Clan ’Mechs have CASE installed. _If the design specifically did not pay the C-bill cost to install CASE then treat a Clan-built ’Mech as an Inner Sphere ’Mech for the purpose of these calculations._"

Can Clan units capable of using CASE opt not to have the system installed which is what I believe the highlighted section seems to indicate?

**Comment by neoancient** [comment]
Yes, the rules allow it. MegaMek does not have support for excluding CASE from Clan units at this time.

**Comment by snrdg102417** [comment]
Morning from WA neoancient,


Thank you for the quick reply and information the current MegaMek does not allow Clan units from not having CASE installed and that my understanding of the Catalyst Game Labs rule is on the mark.


Tom Rux
