### ISSUE TITLE
Mixed tech dropships force change battle armor bays when saved and reloaded

### ISSUE THREAD

**Issue by Wpmz** [MegaMek/megameklab#1182]
### Environment
MekHQ v0.49.10
Java Vendor: Eclipse Adoptium
Java Version: 11.0.16.1
Windows 10 21h2

### Description
If you create a mix tech dropship with Inner Sphere tech base, you are able to add BattleArmor (Clan) bays to it and the unit passes validation. However when you save and reload the unit, the BattleArmor (Clan) bays will have been changed to BattleArmor (IS) bays, or sometimes to BattleArmor (CS) bays. BattleArmor (CS) does not get forcibly changed to BattleArmor (IS) on reload and works properly.

Similarly if you create a mix tech dropship with Clan tech base and add BattleArmor (IS) or BattleArmor (CS) bays, it will pass validation  and save correctly but when you reload it, the bays will have been forcibly changed to BattleArmor (Clan). 

This is most noticeable when you create a mixed tech clan tech base dropship and load it with BattleArmor (IS) and use up all the available space. When you reload it, it will say it is an invalid unit and might load incorrectly because it has forcibly changed BattleArmor (IS) to BattleArmor (Clan) which weighs more so the units is now overweight. 

### Files
[BA Bays Bug Dropship.zip](https://github.com/MegaMek/megameklab/files/9883536/BA.Bays.Bug.Dropship.zip)

**Comment by Sleet01** [comment]
Taking social lock.

**Comment by Sleet01** [comment]
We are not saving the tech base of the different kinds of BA infantry bays at save time, nor do we currently expect such a value when we read them back in.  I imagine this is the only equipment type where this information is not correctly stored, however; it appears that weapons, internal structure, etc. are properly storing this information.

My preference is to force all bays to use 5 fields (as opposed to the variable 2 ~ 4 we currently use, for reasons that are not apparent to me) which will significantly simplify encoding / decoding.
In this proposal, fields are:
```
Size          Doors         Bay Number          Infantry Type          Additional Information Bitmap
e.g.
800           1                  -1                              foot                          7
```
(bitmap format tbd, but would allow setting e.g. "Mixed Tech: Clan Base" _and_ "facing: northeast" _and_ "ComStar", or somesuch)

I would also add a read-time only converter to allow decoding older-format blk files, but enforce the new format when writing.

e.g.:
1. read a BLK file.
2. if a transporter line exists, check its fields.
2.a.  If 2 ~ 4 fields, normalize it to 5.
3.  Read the 5 fields.
4.  Populate the Mounted

If more fields should become necessary in the future, we can append them at the end of the current list of fields and write another normalizer for the 5-field version.
