### ISSUE TITLE
RS Mech sheet style match for special structure 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1196]
Linking to this issue #1176 

From Greekfire 
Having just given this a test run, this looks absolutely fantastic. A full heartfelt thanks for your work on this, Juliez.

Would it be unreasonable for me to request one final addition? If you have time and/or energy, it'd be for composite and reinforced structure to be highlighted in the same way on 'Mech record sheets.

**Comment by SJuliez** [comment]
There is no room left for moving anything here. I can only scale down the silhouettes. 
![image](https://user-images.githubusercontent.com/17069663/203656428-b62f7a5e-1a25-4cf8-a6f2-df10ed9b3c8e.png)

**Comment by Maingunnery** [comment]
Would it be possible to put the type next to it?
In the example I have reduced the title, but a font reduction might also work.

![203656428b](https://user-images.githubusercontent.com/43098653/203842289-e648499a-2670-4076-8f71-a9ac596fe1bf.png)

**Comment by SJuliez** [comment]
Well as a draft I just reduced the armor diagram by 3% and the structure by 2% and moved it and came up with this version:
![image](https://user-images.githubusercontent.com/17069663/203842610-ce627072-4e17-4239-a08f-b5709e422dbb.png)

**Comment by HammerGS** [comment]
We already have the reference between the ankles. Could that be shrunk and have the box put around it. But the new version looks good as a screenshot.

**Comment by SJuliez** [comment]
At least the text "Standard Structure" would be too wide there. This way the text width is at least no worry. I am also trying to scale down that structure text and box a little, then I can scale up the Str diagram again.

**Comment by SJuliez** [comment]
Example of a Mastodon C:
![image](https://user-images.githubusercontent.com/17069663/203844375-664193fc-6ee3-4194-83c3-2f5210010615.png)

**Comment by SJuliez** [comment]
That's about it. If a little more space between armor and structure is desired, I can do that by scaling it all a bit further down.

**Comment by SJuliez** [comment]
But that's artistic freedom rather than rule content, so I'd take input for that.

**Comment by AlphaSled** [comment]
If it can help simplify things, the only structure types that need to be accounted for here are Reinforced and Composite. If Standard, Endo, or anything else isn't present and highlighted, no biggie. There's no real need to have the word "Structure", either---that's already captured by the "Internal Structure Diagram" header.

With that said, I do like having the text immediately below the header for consistency and clarity. I'd specifically request that Maingunnery's suggestion not be adopted, though (even though it was a good idea) as having the header be "Structure Diagram" only distances the language on the sheet from what's used in most rulebook products.

Would it be possible to scale down the armor name box as well (EG: where the Ferro is written on the Mastodon) to align with the size of the other boxes and to potentially claw back another percent or two of diagram size?

**Comment by SJuliez** [comment]
With the box being where it is, it doesn't matter much if it states all structure types and writes "Standard" or "Standard Structure". I could remove the box when it isn't necessary but I'd rather not try scaling up the diagram programmatically (well, for now). 

Yes, I can adopt the size of the box for the armor type. The question is, would we rather have a little space between armor and structure or scale it up as far as possible instead?

**Comment by HammerGS** [comment]
I think keeping it simple and printing all structure types is the way to go. Creates a consistent look across all sheets. 

To my eye I like the bit of space.

**Comment by AlphaSled** [comment]
Yeah, regaining some space isn't a bad thing. 
What's the final percentage drop in diagram size?

**Comment by HammerGS** [comment]
I think it was this drop which would be pretty small. 
> Well as a draft I just reduced the armor diagram by 3% and the structure by 2% and moved it and came up with this version

**Comment by SJuliez** [comment]
Yes it's about these percentages iirc. Its best "experienced" by switching between these two pdfs.
[atlasorig.pdf](https://github.com/MegaMek/megameklab/files/10094938/atlasorig.pdf)
[atlas2.pdf](https://github.com/MegaMek/megameklab/files/10094940/atlas2.pdf)

**Comment by SJuliez** [comment]
Please add any change requests now if possible because the changes need to be ported to a lot of sheet SVG files.

**Comment by AlphaSled** [comment]
I believe this should now cover everything. Thanks, Juliez!
