### ISSUE TITLE
[RFE] Split gear between head and center torso

### ISSUE THREAD

**Issue by MaxMahem** [MegaMek/megameklab#1197]
According to page 57 of the TechManual, "Any ranged weapon occupying 8 or more critical slots may be split between any two adjacent locations (not including the legs)." When using a small cockpit, compact engine, and compact gyro there can be a total of 10 critical spaces combined between the head and center torso, allowing a few pieces of equipment to qualify to be split between them. However, this is not currently implemented.

**Comment by pheonixstorm** [comment]
Didn't even know that was a construction rule. Was that in previous editions as well? I've only ever seen splits between arm/torso.

**Comment by HammerGS** [comment]
Confirmed with CGL that you can split crits to the head from the torso.

**Comment by SJuliez** [comment]
From the CT only?

**Comment by HammerGS** [comment]
Confirm only 2 locations. Head is only considered adjacent to the CT.
