### ISSUE TITLE
Glitch with assigning Gauss to Omni's in the arms

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#12]
I suspect part of the issue is probably in MegaMek.  But there is a way to trick MML into allowing you to but a Gauss rifle in the arm with hands and Lower Arm Actuators which per pg 58 of TM isn't allowed.

Steps to recreate

1)Start MML and set up a Clan OmniMech
2)Head to the equipment tab and buy Gauss Rifle
3)In the Assign Crit Tab put the Gauss into the arm. Notice the Hand and LAA are removed.
4)Right click on the empty slot below the Upper Arm Actuator and select add hand
5)Tada - Hand and LAA back in place.

There should be some type of block that prevents that action.

**Comment by arlith** [comment]
The code to remove the lower arm and hand actuators is actually in MM.  This code was firing to remove the actuators, however MML never checked for this when allowing the actuators to be added back.  I added some code to explicitly check this case.
