### ISSUE TITLE
Radical Heatsinks System Not Adding Heat Capacity Correctly

### ISSUE THREAD

**Issue by masterjayell** [MegaMek/megameklab#1202]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Windows 10 Java11/adoptmium megameklab 48.0
(Delete the above lines)

### Description
Adding radical heatsink system does not add +1 heat capacity per heatsink - adds a percentage instead. Looks like 40% of total heatsinks.
can be duplicated
(Delete the above lines)

### Files
Won't let me add file but if you open a new mech and add it you'll see it doesn't add +x heatsink capacity per total heatsinks.
(Delete the above lines)

**Comment by neoancient** [comment]
The heat in the status bar is estimated heat rather than maximum, and uses the calculation used for calculating BV. In BV calculations, radical heat sinks increase heat capacity by 40%. This is working as intended.
