### ISSUE TITLE
Rules deficiency; Laser AMS THB version

### ISSUE THREAD

**Issue by HuntingTarg** [MegaMek/megameklab#1204]
### Environment
MegaMekLab 49.10 (Standalone)
Windows 10
Adoptium Java SDK Runtime environment 11.0,17.8

### Description
Unable to separate crit locations of Tactical Handbook version of Laser Anti-Missile System, GUI alias (AMS (THB) .  This should be possible without location restriction according to Tactical Handbook pgs. 68-69. .

### Files
No error or log files provided; this is a feature issue, not a functionality issue or bug (AFAIK).
![MML__AMS(THB)Bug_Screenshot_01](https://user-images.githubusercontent.com/53635722/207201750-18399386-d4eb-4fe7-918e-78c2dd0db771.jpg)
![MML__AMS(THB)Bug_Screenshot_02](https://user-images.githubusercontent.com/53635722/207201770-6c56be13-5608-4d67-a412-d958db923502.jpg)

### Notes
If this is to be implemented, it would be important to distinguish which crit is the computer and which crit is the laser, and to indicate in the case of multiple systems which computer controls which laser, for purposes of facing and firing arcs.  This is likely not a simple fix, because it would lead to additional coding in MegaMek so that location-separated systems are handled properly in combat.

**Comment by HammerGS** [comment]
Sorry. We are only providing support for official equipment and the THB stuff is unofficial and been replaced by Total Warfare rules.
