### ISSUE TITLE
Laser AMS THB version; numerical/calculational clarity & accuracy

### ISSUE THREAD

**Issue by HuntingTarg** [MegaMek/megameklab#1205]
### Environment
MegaMekLab 49.10
Windows 10
Adoptium Java SDK Runtime Environment version 11.0.17.8

### Description
Heat stat for the Tactical Handbook version of the Laser Anti-Missile System is inaccurate.
The heat for the two different versions of the Laser AMS (Tactical Handbook and Maximum Tech) are calculated differently in the official boardgame rules ( IDK if it is calculated accurately in MegaMek during play).  In any case the MegaMekLab 'Heat' stat should reflect this, however it does not:  The highest probability result from rolling 2d6 (Maximum Tech rules) is 7 ;  The highest probability result from rolling 3d6 (Tactical Handbook rules) is equal for 10 and 11 according to anydice.com , however the heat listed and calculated is 3 for the THB version.  This should be amended in order to reflect the different rules applied to the different systems.  Also of note that damage for the two systems (in terms of offensive combat damage) is N/A, because neither of these weapons can be used offensively with an Inner Sphere Tech Base.

### Files
No log or bug report files provided; this is (ostensibly) a feature issue, not a functionality or compatibility issue, a design flaw, or a bug.

![MML_AMS_Heat_RulesDiscrepancy](https://user-images.githubusercontent.com/53635722/207205356-85f9a6da-2a6f-4e0d-a8e3-9b3f670e15b7.jpg)

(screenshot capture highlighting added for easy readability)

**Comment by HammerGS** [comment]
Same reasoning as #1204
