### ISSUE TITLE
Digital Record Sheet - accessibility

### ISSUE THREAD

**Issue by FlintPeter** [MegaMek/megameklab#1213]
Question / Feature Request, 

Is there a chance for another function in Megameklab, where you can open a file and it only allows editing of remaining armor ( X damage taken to location of Y total armor, the user only gets to edit X ), marking heat, and destroyed internals, ect. for the use with screen readers or using at a tabletop as a digital record sheet?

**Comment by HammerGS** [comment]
This isn't something MML would be able to do as it focuses on printing record sheets. But you should have a look at 

Flechs Sheets
https://sheets.flechs.net/
