### ISSUE TITLE
RFE - Trailers and Ammo

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1216]
Putting this here but while working on the updated Long Tom from the Rec Guides. I'm building the trailer components and while I can add a variety of the "other" equipment I can add straight ammo.

I'm thinking we should allow trailers to carry ammo.

**Comment by SJuliez** [comment]
What is the exact problem? I tried, built a tank, marked it as trailer, removed the engine, added an AC/5 and AC/5 ammo. Seemed to work so the problem is something else I guess?
