### ISSUE TITLE
49.11 No clan PPC capacitors?

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#1220]
The option for mounting a PPC capacitor to a clan PPC appears to have been removed in this version, though as far as I recall it was present in prior versions.

**Comment by HammerGS** [comment]
Not see this. 
![image](https://user-images.githubusercontent.com/13752452/212324120-3fb71ebb-10c9-4115-a3ad-92f3e16f99f3.png)


Please provide steps to recreate.

**Comment by LiamsGhost** [comment]
Sorry it took me a bit to get back to you. It appears the introduction date for the clan version of the capacitor was listed as earlier in the prior version of megameklab, which is what threw up the errors with my file with this version. (it was trying to find clan capacitors in 3095 when IO and this version doesn't allow them to be available until 3101). 

So as near as I can tell there's no actual error in the program.

**Comment by HuntingTarg** [comment]
This connects back into #831 regarding the equipment rules and how MML actually treats PPC capacitors with regard to techbase and availability.  I submit that this is neither an explicit code bug nor an independent issue, and should be closed.

**Comment by HammerGS** [comment]
Addressed missing PPC's with this fix. 

https://github.com/MegaMek/megamek/commit/422774bb1de56b1f837014896eda73dcf1d60194
