### ISSUE TITLE
MML not adding w/Artemis to Record sheet when printing. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1223]
Looks like MML's aren't adding the w/Artemis note when print the RS. The unit file and ammo shows them present. 

See The SturmFeur (WoB) or Patton XL variant for units as an example. 

![image](https://user-images.githubusercontent.com/13752452/212193411-1a3ab793-e26f-4cd0-bba3-47b1c4d35ca8.png)

**Comment by SJuliez** [comment]
The Sturmfeur WOB reports as invalid and misses the MML Artemis. I can't find a Patton XL.
