### ISSUE TITLE
Version 0.43.6 Small Craft free heatsinks

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#123]
Small craft are supposed to use the same equation to calculate free heatsinks as civilian dropships of the same type, however the military check box is still available when switching to a small craft, and is enabled by default. It has to be manually disabled in order to create an accurate small craft.

**Comment by neoancient** [comment]
The military/civilian checkbox remains visible for small craft because TM states that they make the distinction along with dropships (p. 183), though I'm not aware of any rule where it would make a difference. It appears to be a matter of fluff.

**Comment by LiamsGhost** [comment]
Umm... sure there is. The heat sinks I just mentioned. All small craft regardless of type use the free heatsink equation of civilian dropships of the same type. If the military check box in megameklab is selected, however, it uses the military dropship equation for free heatsinks, which results in free heatsinks they shouldn't get.

**Comment by neoancient** [comment]
Yes, I fixed that in the commit linked above. I added the note about the civilian/military checkbox because I double-checked whether I should also hide it for small craft and I documented my findings here.
