### ISSUE TITLE
[49.11] 0 Max Bay Doors on Large Fixed-wing Support Vehicles

### ISSUE THREAD

**Issue by HIMP-Dahak** [MegaMek/megameklab#1230]
### Environment
49.11, the mekhq package download
Windows 11
Will add java version as soon as able

### Description
Issue: Large Support vehicles using the Fixed Wing flight type will always show 0 max doors for transport. I have not checked if medium and small suffer the same. 
Rules: Per TM errata, "Transport bays for any unit type other than infantry must assign a minimum of 1 bay door each, to allow for entry and egress from
the vessel ... For all other vessels, the maximum number of bay doors is equal to 7 plus the vessel’s total weight (in tons) divided by 50,000
(rounded up). "
Reproduction: Load an existing 200t fixed wing support such as the KC-9. Alternatively, create a large support, selective motive type "fixed wing" and a weight of 200t. Then check transport tab. 

### Files
Can attach log when back at computer, if needed. No errors specific to this issue. (There is an error when you click the door count of a bay while you have more doors assigned than max doors)
KC-9 is a built in unit demonstrating this issue.

**Comment by Sleet01** [comment]
There's another, related issue: it's not possible to _change_ cargo bay door counts for fixed-wing support vehicles, except from 1 to 0.

**Comment by Sleet01** [comment]
This is actually a bug in MegaMek common code.
