### ISSUE TITLE
RS - Indicate that Trooper 1 has the SSWM

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1232]
Current on BA RS a SSWM is indicated on the weapon. Is there a way to get a indicator that it's assumed to be on Trooper 1.  Either text indicating in the Type or on the armor graph of the Trooper 1. 

![image](https://user-images.githubusercontent.com/13752452/215871269-970541d6-8c4d-47ad-b18e-f5d548d11d70.png)

**Comment by SJuliez** [comment]
I have no idea how to add this to the armor bar. A very easy solution is to append it to the SSW text like this:

![image](https://user-images.githubusercontent.com/17069663/216843279-7352fc2a-a0d0-4413-9216-4253b52b70bd.png)

**Comment by HammerGS** [comment]
Text to the trooper it is. :)
