### ISSUE TITLE
[49.12] Can't reach Squad Member 6 when assigning Ind. Equipment

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1239]
![image](https://user-images.githubusercontent.com/13752452/224506093-faf96d1a-a31b-41d1-8542-eae196cb7cd9.png)

You can't scroll down to Trooper 6 to add Individual Equipment, nor does the drag work.

**Comment by SJuliez** [comment]
Can you reproduce that? I get a scrollbar on the right, so no problems.

**Comment by HammerGS** [comment]
Working in .13
