### ISSUE TITLE
AS Card Conversion report nonfunctional "This is an intentionally calculations report"

### ISSUE THREAD

**Issue by Thanat0sNihil** [MegaMek/megameklab#1240]
### Environment
What version of MekLab does your issue apply to?  4**9.11 and 49.12 standalone**
What operating system are you using?  **Windows 10 Home**
What java version are you using? 
![jdkver](https://user-images.githubusercontent.com/37569877/224578742-3a00250c-6283-448b-b0e2-6e27e1ce09c9.png)

### Description
Any time I try to view any mech's Alpha Strike conversion report (under preview-> AS Card -> Conversion Report) I get a window with the message "This is an intentionally calculations report" and not other content. This occurs for all designs I have tried it on whether custom or canon. 
![canonASblank](https://user-images.githubusercontent.com/37569877/224578978-37276913-1443-4402-a12d-d9b979a90d98.png)
![customASblank](https://user-images.githubusercontent.com/37569877/224578985-d9d142ec-43f6-4476-8857-a61c1ce8e58e.png)

### Files

[megameklab.log](https://github.com/MegaMek/megameklab/files/10952289/megameklab.log)

**Comment by HammerGS** [comment]
As a workaround you should be able to see the conversion report in MegaMek.

**Comment by Morkath** [comment]
It also appears to work correctly if you are viewing from load from cache search results, as long as you don't load the mech into the editor.
