### ISSUE TITLE
The BattleMech Turret (Head) construction does not account for a rule involving torso-mounted cockpits.

### ISSUE THREAD

**Issue by JoshVandeleuv** [MegaMek/megameklab#1246]
This issue is occurring in the 0.49.12 version of MekLab which is bundled with MekHQ in the Windows environment.  Java's 'About' on my computer describes my Java environment as Version 8 Update 361, or build 1.8.0_361-b09.

- - -

The edition of Tactical Operations which I have access to describes some construction rules for turrets on page 346.  Copied directly: "_BattleMech head turrets (available to quad or biped ’Mechs) require a turret critical slot in the center torso. **A ’Mech must be using a torso-mounted cockpit (see p. 301) to mount a head turret.**_"  (Page 301 does not reference turrets, it simply provides rules for torso-mounted cockpits).  I believe that the phrase "_mount[ing] a head turret_" must refer to mounting the critical slot for a turret in the head, as the only other interpretation I can think of is that a torso-mounted cockpit is required to mount turreted weapons in the head, and I don't believe this is the case.  MML's current construction rules do not follow this interpretation either, as head-mounted weapons can be turreted without a torso-mounted cockpit in the current edition.

Therefore, if the mech being edited in MML has a torso-mounted cockpit, it should be able to 'mount a head turret', but when selecting the location for the equipment 'BattleMech Turret (Head)', the Center Torso is the only listed option, and attempting to click-and-drag it to the head results in the 'Invalid Location' message "_BattleMech Turret (Head) can't be placed in HD: BattleMech Turret (Head) must be placed in the center torso._"

In the interest of thoroughness, this was tested in both Experimental and Unofficial tech levels (since Torso-Mounted cockpits are Experimental technology and thus no lower tech level would allow for testing) and in every combination of Clan, IS, and mixed tech, as well as with and without the presence of a valid weapon to turret-mount which could have been placed in the head (a simple Medium Laser for mixed and IS, an ER medium laser for a Clan tech base).  The exact same message was received in each test, stating that the turret could only be placed in the center torso.
I believe that the construction rules for Head Turrets in TO:346 directly contradict this admittedly edge-case limitation in MegaMekLab and I request that an alteration is made such that the BattleMech Turret (Head) critical slot may be placed in the HD location when the mech is using a Torso-Mounted Cockpit.

I admit that I cannot provide a canonical example of this: while some canonical mechs exist which mount both a head turret and torso-mounted cockpit, research on Sarna (for I do not have access to the relevant source books) did not reveal any instances of the HD-mounted Head Turret- one instance specifically mounted the turret critical slot in the center torso, in fact.  Despite this, in the absence of errata stating otherwise, I believe that construction rules allow for a mech to be made such that the turret's critical slot is in the head, as long as a Torso-Mounted Cockpit is also used.
- - -

As this is a rules issue and not an issue which generates an error report, I am not including any reports or files.

**Comment by ShadowDefcon** [comment]
Yes, the Head Turret Critical must be in the Center Torso. However, between the Engine Crits, Gyro Crits, and the two slots needed for the Torso-Mounted Cockpit(Cockpit and Sensors), the only ways to use a Head Turret is to also use either a Compact Engine, Compact Gyro or both. Without the Compact Engine/Gyro, you cannot use a Head Turret.

To add a Head Turret, select **Torso-Mounted Cockpit** from the Cockpit options and the **Compact** from either the Engine or Gyro Options. Now click on the Equipment Tab and look for _'BattleMech Turret(Head)_' under Other Equipment. Add it, then when you go to the _'Assign Criticals'_ tab and you will find BattleMech Turret(Head) under 'Unallocated Equipment'. Move the BattleMech Turret(Head) to the Center Torso, move all your weapons you want into the head, then right-click each one and select 'Mount Weapon In Turret'.

**Comment by HammerGS** [comment]
Closing per directions to fix.
