### ISSUE TITLE
Suggestion: Create an option to relax construction rules to make illegal designs

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#125]
Sometimes I run scenarios with "boss battles" that involve illegal units.  Usually I edit unit files by hand, but I think it would be a neat feature if there was a way to get MML to relax its construction rules and output to BLK or MTF files.  I imagine other users would like to play out their alternate universe battles with such units.

**Comment by neoancient** [comment]
The purpose of MegaMekLab is not to create and edit units, but to apply the construction rules to the process. Setting the tech level to unofficial will relax some of the universe details (year and tech base), but if you are looking for a general unit editor that doesn't apply the rules you are looking for a different program.
