### ISSUE TITLE
Combat Vehicle Chassis Modifications (Flotation Hull) not valid for WIGE

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1256]
Dev 49.13 

Building the Swallow Spotter from RS3150.  The Combat Vehicle Chassis Modifications (Flotation Hull)  is reporting not valid for WIGE. Construction rules on pg 114 TO:AR have it valid. 

_"The flotation hull option is only available to Hover, WiGE, and VTOL Combat Vehicles, as well as Conventional Fighters, at no cost in weight or space
(though flotation hull designs will increase the unit’s final cost)."_

I haven't tested with Hover, or VTOL Combat. 
[Swallow Attack WiGE (Spotter).zip](https://github.com/MegaMek/megameklab/files/11493923/Swallow.Attack.WiGE.Spotter.zip)

**Comment by SJuliez** [comment]
The code says:
// Per errata, WiGE vehicles automatically include flotation hull
Is this true?
In any case this is easy to allow and harder to automatically add.

**Comment by gsparks3** [comment]
TW page 55, at least as of 9th printing, all WiGE vehicles treat water hexes as clear terrain and act as naval vessels while landed on water. The existence of the chassis mod for them is a bit of a legacy issue in the _tabletop_ rules, now. I think there are still some canon sheets that list it (at least for SVs? less certain about CVs).
