### ISSUE TITLE
Implementation of Mech Manufacturers and Equipment Manufacturers Database for Fluff Tab

### ISSUE THREAD

**Issue by mkruer** [MegaMek/megameklab#1259]
### Environment
megameklab-windows-0.49.12

### Description
Battletech has a rich lore surrounding Mech Manufacturers and Equipment Manufacturers. However, keeping track of this lore when designing custom Mechs can be challenging. To address this, I propose adding a Mech Manufacturers and Equipment Manufacturers Database with comprehensive information on various components, manufacturers, and weapons. This database should include the following:

#### Mech Manufacturers, Designs and Equipment Database:
- Manufacturers: A comprehensive list of existing manufacturers with associated details, such as primary factories, chassis/frame 
options, engines, armor types, jump jets, communications, and targeting tracking systems.
- Manufacturer Details:  Essential information, such as manufacturer name, history, specialties, and primary factory location.
- Weapons Manufacturers: A catalog of manufacturers specializing in Mech weapons, including weapon items and models.
- Custom Manufacturer Creation: Users can create their own manufacturers within the Database.

### Benefits
- Streamlined Design Process: Access to a comprehensive Database eliminates extensive research, allowing users to quickly select lore-aligned manufacturers and components.
- Improved Lore Consistency: The Database ensures that custom Mechs adhere to established lore, enhancing the immersive experience.
- Enhanced User Experience: The streamlined process reduces research time and effort, enabling players to focus on creativity and engaging design.
- Increased Customization: The custom manufacture feature and user-defined manufacturers foster individuality, expanding customization options beyond the existing lore.
- Improved User Experience: The streamlined Mech design process saves time, allowing players to focus on creativity and immersive design.

**Comment by HammerGS** [comment]
This is an impossible request. BattleTech has 35+ years of canon data in the game. CGL is moving away from this type of data. If you check Sarna which is one of the most complete open source information sources it's incomplete and they have a large team of volunteer contributors/

We are a dev team with one data person me and a few coders. It's taken me hundreds of hours to just get the little bit of fluff that units have. 

Your are welcome to create the database, cross reference it and provide it to us. But this isn't something the MegaMek team is going to do.

**Comment by HuntingTarg** [comment]
> This is an impossible request. BattleTech has 35+ years of canon data in the game. CGL is moving away from this type of data. If you check Sarna which is one of the most complete open source information sources it's incomplete and they have a large team of volunteer contributors/
> 
> We are a dev team with one data person me and a few coders. It's taken me hundreds of hours to just get the little bit of fluff that units have.
> 
> Your are welcome to create the database, cross reference it and provide it to us. But this isn't something the MegaMek team is going to do.

I concur with this response.  As a player from the Succession Wars era, I can attest to the immensity and diversity of this information.  A database of this scope would be its own separate project.  I have lots of sourcebooks, so if you want to pursue this project hit me up @mkruer .
