### ISSUE TITLE
LAM split crit weapons erroneous warning 0.43.6

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#126]
I mounted an AC/20 in the torso of an LAM and I keep getting an error saying that I cannot mount it since its criticals are being split.  As shown in the screen shot below, the AC/20 is not being split.

![image](https://user-images.githubusercontent.com/18338059/34327208-984713a4-e88c-11e7-81f3-e42f3aaa8f7d.png)

**Comment by neoancient** [comment]
I can't reproduce it. Could you please include the steps you took in building it?
![image](https://user-images.githubusercontent.com/16927464/34341067-46f36e34-e955-11e7-904c-f546ec7d59b2.png)

**Comment by neoancient** [comment]
Nevermind. I played around with it more and was finally able to duplicate it and find the problem.

**Comment by neoancient** [comment]
Drag and drop was assigning splittable equipment to two locations even if all the primary location had enough space. This would have gone away if saved and reloaded, but that doesn't help with validation during the design process.
