### ISSUE TITLE
RFE: Make Cargo Lifter size configurable

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megameklab#1269]
### Environment
MegaMek Version: MekHQ v0.49.13 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description
Cargo Lifters (Page 166, _TechManual_, sixth printing), unlike all other manipulators, have a configurable size: their weight may be configured in multiples of 30 kilograms, each bestowing 500 kilograms of carry capacity.

Note, however, that Cargo Lifters must be mounted in pairs: in practice, this means that their (combined) weight may be configured in multiples of 60 kilograms, yielding a total of 1000 kilograms of carry capacity each.

---

Since it isn't equipment with critical slots, this may be tricky to implement. Perhaps make it configurable via context menu, similar to the number of shots in ammunition? They're already shown in the "Assign Criticals" tab, so this seems like the best bet.

**Comment by SJuliez** [comment]
I believe this is implemented.
