### ISSUE TITLE
Superheavies and Clan Endosteel/Endo Composite

### ISSUE THREAD

**Issue by ShadowDefcon** [MegaMek/megameklab#1303]
MegaMek HQ 0.49.14
Windows 10
Java SE 20.0.1

When using either Clan Endo Steel or Clan Endo Composite Internal Structures on a Super Heavy Mech, they have their full allotment of criticals(7 and 4) in the 'Assign Critical' tab. They should only have 4 slot(Endo Steel) and 2 slots(Endo Composite)

**Comment by HammerGS** [comment]
https://bg.battletech.com/forums/index.php?topic=70587
