### ISSUE TITLE
Multiple Missile Ammunition Types in Protomechs

### ISSUE THREAD

**Issue by BBQMech** [MegaMek/megameklab#1304]
### Environment
Tested in both 49.14 and 49.12 of the HQ package, using Windows 10 and Java Version: 11.0.14

### Description

When attempting to equip a protomech with multiple types of missiles as shown here:
![image](https://github.com/MegaMek/megameklab/assets/143133056/b9d2b4e8-9f6e-4e04-882e-ef0203667492)

MML has failed to load them as shown here:
![image](https://github.com/MegaMek/megameklab/assets/143133056/b0f577d5-fd28-4e72-84ff-27751b311f36)

This seems to occur only with missiles, and happens regardless of size of launcher, type of missile or rules selected.

### Files
Here is my log file.
[megameklab.log](https://github.com/MegaMek/megameklab/files/12433222/megameklab.log)

**Comment by hj084021** [comment]
not unique to MMLs, applies to most alternate missile loads, including frag missiles. happens, from what I know, on .48, and .49.15
