### ISSUE TITLE
MML included with MHQ doesn't display Equipment Tab properly

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/megameklab#131]
MML 0.43.7 Beta from MHQ build

When you click on the Equipment tab it does not display. If you mouse over items they will draw.

Reproduction... open MML click Equipment tab
Work around... copy the standalone .exe to MHQ folder.

[MML_log.txt](https://github.com/MegaMek/megameklab/files/1615724/MML_log.txt)

**Comment by scJazz2** [comment]
It is possible that this is an issue with Bloodwolf's build setup as both times this problem has occurred it happened in his Beta builds.

**Comment by neoancient** [comment]
This is a MekHQ packaging issue.
