### ISSUE TITLE
[49.13] Tsemp One Shot fails to load for Celerity CLR-04-R

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/megameklab#1317]
18:46:05,569 INFO  [megameklab.MegaMekLab] {main}
megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:58) - Starting MegaMekLab v0.49.13
	Build Date: 2023-05-23T14:36:10.293482600
	Today: 2023-09-25
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.20
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_GB
	Total memory available to MegaMekLab: 1 GB

I came across this error message while browsing Megameklab
![image](https://github.com/MegaMek/megameklab/assets/67933202/b00932d5-8ed5-4727-ba98-ca1f58a3796f)

After loading the unit, adding the equipment and putting it on the right torso, I still can't validade the unit. No log shows any error message.

![image](https://github.com/MegaMek/megameklab/assets/67933202/8e5e2efc-587c-4c8c-9968-545a2a81e42c)

Searching for TSEMP OS gives one result, a Hellion variant, that loads properly. I don't know if there are any more mechs that use the weapon, so no extra info.

Searching "fails to load" on github yielded this solved issue: #297.

**Comment by SJuliez** [comment]
Fixed in 0.49.16
