### ISSUE TITLE
MUL id key in .blk files includes a colon?

### ISSUE THREAD

**Issue by IanBellomy** [MegaMek/megameklab#1319]
The MUL id key in .blk files appears to consistently include a colon, e.g. `<mul id:>`— is this intentional?

**Comment by neoancient** [comment]
It uses the same string as the mtf file format, which uses the colon.

**Comment by IanBellomy** [comment]
🤔 Colons are used as delimiters throughout .mtfs
e.g.  
````
Config:Biped Omnimech
TechBase:Clan
era:2945
````
And no tags in .blk files other than `<mul id:>` -- even those similar to mtf keys like `<year>`, `<armor>`, and `<type>`--  include colons.
