### ISSUE TITLE
Aero heat sinks added as pod-mounted on non-omnifighter.

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megameklab#132]
### Environment
MekLab 0.43.6, via mekHQ
What operating system are you using?  Windows
What java version are you using?  Java version 1.8.0_121

### Description
Creating a custom Ironsides aerospace fighter (default 10 double heatsinks) trying to add 6 double heatsinks adds omnipod heatsinks despite being set to inner sphere tech.  Attempted via mekhq and through the independent exe in the mekhq folder.  Other fighter craft that are changed from single to double heatsinks work fine (included).

![aero heatsinks](https://user-images.githubusercontent.com/34722287/34906144-ef617a6e-f834-11e7-9d3e-ce681212a64d.png)

[glitch (3).zip](https://github.com/MegaMek/megameklab/files/1628332/glitch.3.zip)

**Comment by neoancient** [comment]
Aerospace units don't distinguish between IS and Clan heat sinks, only single or double. It was adding them as pod-mounted because it didn't check whether it was an omnifighter (which is available to IS or Clan in the right year) before comparing the current total to the base.
