### ISSUE TITLE
RFE: Include version number in MTF/BLK file when saved

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1324]
When troubleshooting unit files it would be helpful to know what exact version the file was made on. 

Is there a way to set up a tag that only shows in the file saving the version of MML it was made on.

**Comment by Sleet01** [comment]
There's actually already a "version" field in these files, but it seems to be manually incremented when people tweak the files themselves.

It should be quite simple to add a "created_by_version" field to the files.

**Comment by HammerGS** [comment]
Yeah, that's exactly what I'm hoping for.
