### ISSUE TITLE
[0.49.15] ISO A4 size PDF export doesn't have enough room for weapon ranges

### ISSUE THREAD

**Issue by orffen** [MegaMek/megameklab#1325]
This issue doesn't appear in the current stable release (0.48.0), however fonts aren't correctly used in that version (mix of selected fonts and Times).

### Environment
This issue is present in both Standalone and HQ MekLab. It doesn't appear to be OS-specific; I've confirmed the issue on both MacOS and Windows.

### Description
When exporting PDF in US Letter size:
![image](https://github.com/MegaMek/megameklab/assets/2225985/affcc0e7-a033-4df5-8eaf-b5b2978f986d)

When exporting PDF in ISO A4 size:
![image](https://github.com/MegaMek/megameklab/assets/2225985/d1efd2ae-875e-454d-bd18-ada53d9306cc)

This doesn't appear to be font-specific; I have the same issue when using other fonts.

**Comment by Baudster** [comment]
I have played around with the problem a bit, as it also occurs in the more recent versions. The error seems to have occurred with the following [commit](https://github.com/MegaMek/megameklab/commit/a4621bdfb6369806c942e674e12d9413f075725d#diff-acabedcb3fbf811fbaca2b1a091194ed4333b80e64f4044258e6f2fbd759d456).

The svg iso templates of all mechs (Biped, LAM, etc) seem to be affected.

### Workaround

You can take the svg files from the previous [commit](https://github.com/MegaMek/megameklab/commit/077f6c17508ba985ef4dcc3590475ee2c7afc23d) and overwrite the templates in more recent versions with them. In my first impression it seems to solve the problem.
