### ISSUE TITLE
49.15 MegaMekLab - Vehicle Sponsons cause Clan Vees tech level to switch to Unofficial

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megameklab#1328]
### Environment
The HQ Version of MML / 49.15
Windows
Java 11

### Description
When creating a Clan unit in MML in the 3040 era [don't know how many years are affected by this], if you equip a Vehicle Sponson Turret to the unit, it will change the unit's tech level over to Unofficial. 
![image](https://github.com/MegaMek/megameklab/assets/132851640/276346f2-1132-4c6c-a9ac-cf12a0e919ee)
![image](https://github.com/MegaMek/megameklab/assets/132851640/f77a6bc0-50a7-4bcc-8c62-c4563089838e)
![image](https://github.com/MegaMek/megameklab/assets/132851640/ba2f2c03-4246-49a8-863e-7458af355d1f)
As you can see with the above images, all I have done is added in the VST equipment and the tech level has switched over to Unofficial. Nothing else has been done to the unit. 
![image](https://github.com/MegaMek/megameklab/assets/132851640/5587e3cb-309a-4536-9c57-4c57290e7f88)
![image](https://github.com/MegaMek/megameklab/assets/132851640/d0854cad-2ffc-47d7-861a-1f48b01121ed)
These two images are the same situation but with a unit set to 3145 era. Once again, only the VST is added and the tech level does not change. 

The process is extremely easy to replicate. Open up a new MML. Click create new combat vehicle. Set it to Clan origin with Experimental tech level and the 3040 era. Equip the VST [ensure its actually 'equipped' in the crits]. And assuming my Lab isn't having a unique issue your unit should switch to Unofficial.

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/13230837/megameklab.log)
There isn't anything in the Log but I attached it to showcase that fact.

**Comment by neoancient** [comment]
I can reproduce this reliably in 0.49.15, but it does not occur in the current code.

**Comment by RaozSpaz** [comment]
This is actually caused by a mixture of things. I had put up an issue relative to this and discovered that it is relative to the unit only having Standard or lower tier equipment. Due to how the code processed it it was . . . well. Weird. However in the newest version thanks to Sleet's talents the issue has been fixed. Sponsons now cooperate with any tech level properly.
