### ISSUE TITLE
49.15 No method to add advanced fire control system to industrial mechs

### ISSUE THREAD

**Issue by TimberWolfD** [MegaMek/megameklab#1330]
### Environment
MekHQ 49.15
Windows 10 (AMD64)
Java: 19

### Description
There appears to be no way to add advanced fire control systems to IndustrialMechs.
![IM Cockpit AFCS 1](https://github.com/MegaMek/megameklab/assets/143316586/1dffcec4-2a5f-46a8-91b4-38f0331e86e3)
Existing units with AFCS load correctly with their cockpits showing AFCS in the cockpit critical block.
![IM Cockpit AFCS 2](https://github.com/MegaMek/megameklab/assets/143316586/58e2c834-4252-4c76-9a94-ce5584e1ab51)

I have tried changing cockpit types in the "Structure/Armor" tab, but I can find no method there.
I looked through the "Equipment" tab using "Show All" and enabling "Unavailable" equipment, but I could not find either AFCS or Industrial Cockpit (Adv. FCS).
In the "Assign Criticals" tab I tried right clicking on the cockpit with no effect (except to bring up armoring the cockpit if the tech level permitted it). I also tried to right click on the empty head critical with no effect.

### Files
[mekhq.log](https://github.com/MegaMek/megameklab/files/13243735/mekhq.log)
[megamek.log](https://github.com/MegaMek/megameklab/files/13243736/megamek.log)
[megameklab.log](https://github.com/MegaMek/megameklab/files/13243738/megameklab.log)

**Comment by HammerGS** [comment]
Looking back in the history I think we've lost the cockpit tag in the files.
