### ISSUE TITLE
[0.49.15] Extended fuel tank vehicle equipment 'other' vs 'show all' filter

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megameklab#1346]
Bundled Megamek with MekHQ 0.49.15
Windows 10, Java Version: 11.0.13

Extended fuel tank should show up under 'other equipment'. Currently it only displays when 'show all' is clicked.

![image](https://github.com/MegaMek/megameklab/assets/55139229/0e6795a8-cd2d-4661-b0ad-7011cc158f7d)

![image](https://github.com/MegaMek/megameklab/assets/55139229/50386ada-8edc-4bed-a2bc-d2162437df0f)

**Comment by SJuliez** [comment]
It shows up under Industrial, as it is listed under industrial equipment in TM.

**Comment by SJuliez** [comment]
Closing this as I can see no error. May be reopened if there is further input.
