### ISSUE TITLE
Tariq mounted infantry cannot have support weapons

### ISSUE THREAD

**Issue by foij00** [MegaMek/megameklab#1359]
49.17

Trying to build the Tariq-Mounted Platoon (LRR) in HB:Major Periphery States (page 200).
http://www.masterunitlist.info/Unit/Details/5177/tariq-mounted-platoon-lrr

I can't mount a Light Recoilless Rifle as a support weapon (unless I force it by hand editing the .blk file).  However, the canon unit referenced obviously has a support weapon.  The only beast type that will allow one or more support weapons is elephants.

**Comment by HammerGS** [comment]
Lots of those units predate the construction rules. 

TacOps pg 108
After determining a beast-mounted infantry unit’s creature type, the platoon may be armed per standard conventional infantry construction rules. **Note, how-
ever, that infantry mounted on Large-size creatures may not carry support weapons,** while infantry mounted on Monstrous-sized creatures may employ up to 3
support weapons per beast.

**Comment by SJuliez** [comment]
Is there a solution for this? MML seems to implement the rules correctly, so do we close the issue?

**Comment by HammerGS** [comment]
Per this errata closing 
https://bg.battletech.com/forums/index.php/topic,8672.msg200202.html#msg200202
