### ISSUE TITLE
Cannot load DropShip design after adding weapon quirks

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megameklab#1364]
### Environment
MegaMek Version: MekHQ v0.49.17 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

When assigning weapon quirks to the Sub-Capital Missile Bays of the design in the attached BLK file, MegaMekLab produces a design that it is then incapable of loading.

[Peterson.txt](https://github.com/MegaMek/megameklab/files/13811503/Peterson.txt)

**Comment by SJuliez** [comment]
I can load it. But the extension must be .blk

**Comment by Saklad5** [comment]
> I can load it. But the extension must be .blk

You can load that file, then add then add weapon quirks, then load it again?

**Comment by SJuliez** [comment]
Ah ok found the problem. Easily fixed.
