### ISSUE TITLE
49.17 Sponson Turrets / Standard Tech / Variable Tech Level - Causes issues with Era and Unit loading/saving

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megameklab#1365]
### Environment
Version: 49.17 [Full Suite]
System: Windows
Java: 11

### Description
Issue: I redesigned several vehicles that I utilized in 49.15 in 49.17 in order to try out a new clean campaign. After making all the different builds, I went into MHQ to start my campaign and when going in to purchase them, I noticed a few of the variants for the builds didn't show up in the list. 
![image](https://github.com/MegaMek/megameklab/assets/132851640/67554a8a-31d6-428f-afc3-7a154d2bcc0a)
The campaign date is 3012 and the Argentum is not showing up despite having an earlier production date. After some cooperation with Phoenix to try and narrow down what was going on we believe we found the issue. 

Upon attempting to load any of the attached vehicles with VTL turned off, they load just fine. When you preview the unit however the Argentum's base variant shows a 3074 availability date. 
![image](https://github.com/MegaMek/megameklab/assets/132851640/9ffefb3d-ffb5-4686-a829-43a49a720e7b)
This is despite it still showing the unit's set production date in the list on the left side of the screen. 
The Ferrum on the other hand shows up just fine in both MML and MHQ
![image](https://github.com/MegaMek/megameklab/assets/132851640/211bcda5-c6e3-4094-8897-755eca92cd94)

Based on evidence gathered by Phoenix, it seems that the issue somehow derives from a vehicle using Sponson Turrets while also only using other standard equipment. As the Ferrum uses a Fuel Cell engine and the Argentum HE uses a Sniper Cannon, they both have no issue equipping and saving a sponson loadout. The base Argentum though only uses standard equipment and is causing there to be odd issues somewhere with the eras/tech level.

### Files
[Issue Files.zip](https://github.com/MegaMek/megameklab/files/13813950/Issue.Files.zip)
This folder contains all 3 of the vehicles in question. I have other vehicles I have made as well but they mostly just replicate the same issues.

**Comment by Sleet01** [comment]
@RaozSpaz The zip contains an empty directory, but I think I can repro this from the info provided.

**Comment by RaozSpaz** [comment]
[Related Files.zip](https://github.com/MegaMek/megameklab/files/14562854/Related.Files.zip)
I double checked the folder this time. It should contain all my custom units so it should cover all the files needed to load the campaign [for ease of checking].
