### ISSUE TITLE
Uncaught java.lang.NullPointerException when closing mech selection window

### ISSUE THREAD

**Issue by FixDis** [MegaMek/megameklab#1369]
### Environment
MegaMek v0.49.17 on Windows 11
Eclipse Adoptium Java Version: 11.0.21

### Description
Opening and closing the Load Existing Unit screen and Load Unit from Cache always causes the error message: Uncaught java.lang.NullPointerException

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/13815715/megameklab.log)

**Comment by HammerGS** [comment]
Fix pending. Duplicate of https://github.com/MegaMek/megameklab/issues/1370
