### ISSUE TITLE
RFE Summary View Improvement Suggestions

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1372]
The Summary view is a great addition. Opening this as I didn't get a chance to suggest some future improvements.

Add Gyros - They are located in Mech.java starting at lines 124 and 2937

Add Cockpits - They are in the various classes - Mechs for example, start at 2969

Would this be a place where you could generate the earliest possible year for a unit?  Basically review the Introdate of all equipment on a unit and determine the earliest date possible a unit can exist. For example the equipment might allow a intro date of 2500, but you can't see that unless calculated by hand.

**Comment by SJuliez** [comment]
We can generate the earliest year. Some questions: 
- Is it useful to have all ratings directly listed or could some be left as a tooltip?
- Are the full ratings useful or are derived values more useful like the earliest year?

**Comment by HammerGS** [comment]
> We can generate the earliest year. Some questions:
> 
> * Is it useful to have all ratings directly listed or could some be left as a tooltip?

I think tooltip works nicely

> * Are the full ratings useful or are derived values more useful like the earliest year?

I think this is the tricky one, I think the full ratings are useful, but derived values can with players wanting to build out very specific era builds.
