### ISSUE TITLE
[0.49.17] Targeting Computer can get stuck unallocated even though it is showing on assign criticals chart

### ISSUE THREAD

**Issue by dxz6228** [MegaMek/megameklab#1373]
### Environment
Running Megamek 0.49.17.
Java version is 11.0.19, from Oracle.
Running on Windows.

### Description
On already made units, removing and re-adding/moving targeting computer can get it stuck in limbo where it is listed as unallocated, but is in fact taking up critical slots on assign crits chart.
At that point, removing it only removes it from the list of equipment, but it stays locking up slots on the crit chart.
For illustration:
![изображение](https://github.com/MegaMek/megameklab/assets/38220488/c605fd08-f04b-4985-8dff-84fde9b6e808)
No tarcomp.
![изображение](https://github.com/MegaMek/megameklab/assets/38220488/af1a7230-e027-476a-838b-801071c87870)
And yet there it is in right torso.

### Files
Providing log files in case it's helpful... I also recorded the **exact** sequence of actions taken to get to the bug, this was me reproducing it.

https://github.com/MegaMek/megameklab/assets/38220488/012fe819-ba63-4bb1-94f0-0a7237482a56

[megameklab.log](https://github.com/MegaMek/megameklab/files/13850197/megameklab.log)
[megamek.log](https://github.com/MegaMek/megameklab/files/13850198/megamek.log)

**Comment by pavelbraginskiy** [comment]
Fixed by MegaMek/megamek#5222, turns out to have the same cause as a different bug I fixed earlier.

**Comment by HammerGS** [comment]
Per Discord closing.
