### ISSUE TITLE
1.53 : Mixtech does not allow you to select mixtech armor

### ISSUE THREAD

**Issue by Question2** [MegaMek/megameklab#14]
If you have a vehicle set to mix tech IS, you will not be able to select any clan armor (after clicking clan standard for example, MML just selects IS standard instead). If you have it set to mix tech clan, you cannot select any clan armor (same thing happens, MML just forces you to use the clan version instead).
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/275911/megameklablog.txt)

**Comment by BLOODWOLF333** [comment]
Verified, MML will only allow you to use the base tech version of the armors.  Im not sure what rulebook covers mixed tech?  (looked in TW, TO, & BT Compendium)

**Comment by pheonixstorm** [comment]
This is nearly the same issue as the one posted here https://sourceforge.net/p/megameklab/bugs/181/

**Comment by wildj79** [comment]
@BLOODWOLF333 Mixed tech is covered in TO, p. 377

**Comment by BLOODWOLF333** [comment]
"Any unit may be constructed using a mix of Clan and Inner
Sphere technologies, including those described as tournament-
legal (with rules described in TechManual), advanced or
experimental. All such items follow their relevant construction
rules when installed, including any requirements for heat sinks
and power ampli ers. Both structural items (such as internal
structure, cockpits, musculature and engines) and non-structural
components (such as weapons and heat sinks) may be
taken from di erent technology bases. However, as the original
rules for such items pre-supposed their incompatibility,
players must use their judgment to resolve any discrepancies
in the rules regarding their use."

It doesnt say you cant use clan armor on an IS mech or IS armor on a clan mech..........kinda vague.

**Comment by HammerGS** [comment]
I believe the issue here is more to do with the selector screen out things that it shouldn't.  But that's something Arlith would need to review.

**Comment by neoancient** [comment]
MML allows mixing armor types on 'Mechs and explicitly offers mixed types in the dropdown for vees, so it appears that it was intended to allow it on vees. Armor is set by the display name (Standard, Ferro-Fibrous, etc) and selects either IS or Clan based on the `Entity`s armor tech level. This was not being set prior to assigning the armor type.
