### ISSUE TITLE
[0.49.17] MegaMekLab not printing fluff images on mech record sheet when image is only in user folder

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megameklab#1407]
I have set a user folder and filled it with mech fluff images using the appropriate file structure: [Folder]/images/fluff/Mech/[unit].png Fluff images are displaying correctly in the unit selector in MegaMek and MegaMekLab.

When attempting to print a record sheet from MegaMekLab, instead of getting the fluff image on the sheet as expected, I get the default hud.png. I tried this with several units, accounting for .jpg and .png file formats, double checking names etc. All test units had images that displayed correctly in the unit selector screen. Copying the image file from my user folder into the mekhq-windows-0.49.17\data\images\fluff\Mech folder resulted in a correctly printing record sheet.

Further testing conducted: I deleted everything from mekhq-windows-0.49.17\data\images\fluff\Mech folder, printed an Albatross record sheet. Nothing showed up in the image space, since hud.png had been deleted. Copied the Albatross.png from my designated user folder to mekhq-windows-0.49.17\data\images\fluff\Mech and printed an Albatross again. Image showed up correctly on the record sheet.

**Comment by SJuliez** [comment]
I cannot reproduce that problem. To clarify: It should be [User Folder]/data/images...

**Comment by stonewall072** [comment]
I don't quite remember what all was going on here and there was some follow up discussion on the Discord that might have led to a resolution.  

Yes, that's what my path is. As I said, images were showing up correctly in the unit selector, it was only on printing that there was an issue, so not an issue with the folder path. But for what it's forth, the issue seems resolved and this can be closed.
