### ISSUE TITLE
[0.49.18] Battle armour weight calculation only counts one point of armour

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/megameklab#1439]
Bundled Megamek with MekHQ 0.49.18
Windows 10, Java Version: 11.0.13

For example an Elemental should have 250kg for 10 points of basic Clan armour. It looks like the suit is (9x25)=225kg underweight.

![elemental](https://github.com/MegaMek/megameklab/assets/55139229/b3f6a2cd-dbc6-43b1-b0f8-42d967727a99)

![image](https://github.com/MegaMek/megameklab/assets/55139229/603d8d5b-b0c1-49f2-a90e-e4881aa8a018)

**Comment by Sleet01** [comment]
It looks like BAs are returning the weight of one point of armor their _type_ of armor, rather than the total weight of their _actual_ armor, when queried.

**Comment by Gribbly1** [comment]
> It looks like BAs are returning the weight of one point of armor their _type_ of armor, rather than the total weight of their _actual_ armor, when queried.

That's exactly what I reported with separate examples.
