### ISSUE TITLE
Feature Request: Fluff tab for units

### ISSUE THREAD

**Issue by Retry2000** [MegaMek/megameklab#144]
In addition to the designs themselves, a player may wish to add fluff to their design to explain what it is, where it came from, why it came to exist, et cetera.

Either before or after the Preview tab, add a fluff tab.  The stuff entered into this tab wouldn't affect anything in the actual game but bits of fluff could be entered into it, such as:
(Note: not comprehensive)

A "fluffy" 2D artwork (like the Unseen Mech artwork, for example)

An actual 2D counter that would be used in MegaMek (idk how feasible it would be, but if MML could support creating a custom 2D counter for a given Design chassis/model within the MML program itself for streamlined transfer into Megamek instead of either sticking with one of the generic 2D models or having to create one outside of the program in, say, MS Paint and find the place to paste that new model, that'd simply be excellent).

Entries for written fluff of the design history: Overview, Capabilities, Battle History, Deployment, Variants, Notable Crew (etc).
This wouldn't do anything in MM, but if you, say, saved the design as a HTML or text file so you can export it, the fluff could be pasted on the bottom of the actual design specifications.

**Comment by neoancient** [comment]
There are fields for history, deployment, and a couple other things that are stored in the unit file. It would be simple enough to add a miscellaneous field, or probably not too difficult to add custom user-defined fields. Dealing with graphics and selecting the sprite to use is another matter.

**Comment by Xeno426** [comment]
The fields should nirror the common fields in the TROs, IMO. Similar to how SSW does its fluff tabs. Fields for manufacturing info would be great as well.

**Comment by HammerGS** [comment]
Closing this and referencing it in #37
