### ISSUE TITLE
[0.49.18] Cannot open 'Equipment' tab for aerospace units

### ISSUE THREAD

**Issue by MJM4444** [MegaMek/megameklab#1445]
Environment: HQ's MekLab, Windows, Java Version 11.0.18

### Description
Cannot open the 'Equipment' tab for aerospace units

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/14466185/megameklab.log)

**Comment by Sleet01** [comment]
This is being tracked in another issue: https://github.com/MegaMek/megameklab/issues/1429

Closing as duplicate.
