### ISSUE TITLE
Feature Request: Design Quirks Tab

### ISSUE THREAD

**Issue by Retry2000** [MegaMek/megameklab#145]
While it's possible to designate design quirks to custom designs with MM by using the "save quirks to chassis/model" feature, MML could benefit from an extra tab for certain units that can benefit from Design Quirks between the Preview and Critical Assignment tabs.  A single MML generated design would have the quirks inherent in the design's file itself so MM can read it without having to manually use the "save quirks to chassis" feature instead, which is useful if you're wanting to reuse a custom unit in several MM patches as they come out.

The Quirk tab could simply be a list of design quirks, a description of what they do, and a checkbox that activates/deactivates the quirk for your chosen design, sort of similar with how the Manei Domini Implants & Specializations works in the Conventional Infantry design section.  When checked, Quirks would get added to the file itself as something like
<quirk>
[quirkname
</quirk>

**Comment by mwberlindeu** [comment]
I tried to add a quirk to a design in version 49.8 but I did not find a "save quirks to chassis" menu item. Did I overlook something?

**Comment by HammerGS** [comment]
Quirks are managed via MegaMek at this time nothing can be done in MegaMekLab.

https://github.com/MegaMek/megamek/wiki/How-do-I-add-Quirks-to-Customs-Units
