### ISSUE TITLE
[0.49.19 Nightly] Add unit sprites to MML unit selection

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megameklab#1453]
### Environment
megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:53) - Starting MegaMekLab v0.49.19-SNAPSHOT
	Build Date: 2024-03-12T01:07:05.468231
	Today: 2024-03-12
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMekLab: 4 GB

### Description
The new functionality of picking sprites in MML directly is awesome, but it would help if the MML unit selector showed the unit sprite. This becomes an issue when picking a sprite from cache, because you have to guess which variant is the sprite you want (or open the data folders and find the sprite file individually).

![image](https://github.com/MegaMek/megameklab/assets/101755917/99e0300d-8346-4adf-969a-2e4259d5ad2d)

**Comment by SJuliez** [comment]
done :)
