### ISSUE TITLE
[0.49.18] Equipment tab error with Jumpships and Dropships

### ISSUE THREAD

**Issue by Laudern** [MegaMek/megameklab#1459]
### Environment
MegaMekLab and HQ- Version
Windows 10 Pro, Version 22H2
Java Version: 17.0.10

### Description
When klicking on the Equipment tab on Jumpships or Dropships it puts out this Error and doesnt open. First discovered in HQ MekLab, but same Error in standalone.
![grafik](https://github.com/MegaMek/megameklab/assets/29519463/18541e8b-bd0f-4fac-b353-eb9cd63b6f5c)

### Files
Provide the megameklab.log file for any NPE's or errors that MekLab might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklab.log file
And provide the unit's file that the issue relates to if this is a unit-specific bug.
(Delete the above lines)
[megamek.log](https://github.com/MegaMek/megameklab/files/14623614/megamek.log)
[megameklab.log](https://github.com/MegaMek/megameklab/files/14623615/megameklab.log)
[mekhq.log](https://github.com/MegaMek/megameklab/files/14623616/mekhq.log)

**Comment by Sleet01** [comment]
This is likely already fixed by a previous patch to Aerospace handling, but I will double-check...

**Comment by Sleet01** [comment]
Confirmed; this has been fixed in the dev branch already.  Closing as "fixed"; the behavior should be corrected in the next release.

**Comment by Laudern** [comment]
Great. Thank you!
