### ISSUE TITLE
Feature Request- Option to allow extinct equipment.

### ISSUE THREAD

**Issue by Chichengunga** [MegaMek/megameklab#146]
I'm playing a custom faction in MekHQ that uses equipment throughout all years that are made unavailable after a certain time (enhanced ERPPC to be specific). 

Is it possible to have a toggle to allow extinct equipment to be through into a design? I can get around this by editing with a text editor later but would be preferable not to have to.

**Comment by Dylan-M** [comment]
You can already do this. In MML's File->Configuration section there is a checkbox for "Show Extinct Tech" under the Tech Progression tab.
