### ISSUE TITLE
Clan Endo-Composite is showing wrong crit slots.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#147]
Received a PM about the fixed bug here - https://github.com/MegaMek/megamek/pull/909

### Description
Hi, I just saw that you fixed the problem with Clan Endo-Composite not appearing in the new version of MegaMekLab. It now appears in the list, but if you select it it has seven crits like the IS version, and not the four crits of the Clan version.

Tested in RC3 and it's giving 7 crits.

**Comment by neoancient** [comment]
Fixed in MegaMek/megamek@6664fa0.
