### ISSUE TITLE
RISC APDS ammo display in Equipment Tab

### ISSUE THREAD

**Issue by foij00** [MegaMek/megameklab#1470]
49.18

Under the "Current Loadout" area in the Equipment tab, the display for both RISC APDS and its ammo are the same.  It also occurs under the "Unallocated Equipment" area in the Assign Criticals tab.  See attached example.  Need to display the 1 ton ammo slot asRISC APDS Ammo.
![Clipboard01](https://github.com/MegaMek/megameklab/assets/45526752/38f87e85-62cd-4d75-9d87-03afdfb322ec)

**Comment by HammerGS** [comment]
Known issue and is largely fixed for the next dev release.

**Comment by PhoenixHeart512** [comment]
@HammerGS Can confirm, already fixed in 49.19.1
![image](https://github.com/MegaMek/megameklab/assets/101755917/fa5c6ffa-f440-4545-b138-745adf9e200c)
