### ISSUE TITLE
[0.49.18] Conventional infantry weapons from Shrapnel are duplicated

### ISSUE THREAD

**Issue by EvilAtlas** [MegaMek/megameklab#1475]
### Environment
HQ's MekLab 0.49.18
Windows & Mac
Java 11.0.14.1

### Description
Conventional infantry weapons from Shrapnel magazines each show up twice in the weapon selection menu.
![image](https://github.com/MegaMek/megameklab/assets/94950654/68530899-a7b8-4078-a485-6a92b4a383de)
Issue can be reproduced by opening MegaMekLab and either choosing "New Infantry Unit" or loading an existing infantry unit.

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/14912765/megameklab.log)

**Comment by SJuliez** [comment]
This appears to be fixed.
