### ISSUE TITLE
NullPointerException when clicking the equipment tab on all aircraft / spacecraft

### ISSUE THREAD

**Issue by Ell-Mill-Lancer** [MegaMek/megameklab#1476]
Megameklab 0.49.18 (MekHQ Meklab)
Windows 10
Java version 20.0.1
Megameklab log: [megameklab.log](https://github.com/MegaMek/megameklab/files/14924470/megameklab.log)

This issue has affected Aespace/Conventional fighter, Dropship/Small craft, Jumpship/warship/space station, Primitive Aero, Primitive Dropship and Primitive Jumpship.

When I click on the "Equipment" tab I get the following error:
![NullPointerException](https://github.com/MegaMek/megameklab/assets/128006763/8ce2c365-35e4-4f82-88eb-2aa7503ac5a3)

To reproduce the issue I restarted my pc and Megmeklab, it happened again when I clicked the "equipment" tab on the above craft.

Meks and all ground vehicles/ infantry/ battlearmour are unaffected.

**Comment by IllianiCBT** [comment]
This should be fixed as of 49.19
