### ISSUE TITLE
Error when customing dropship equipment.

### ISSUE THREAD

**Issue by TawnyFroggy** [MegaMek/megameklab#1477]
Environment
MegaMekLab v0.49.18

Description
Get a Null Pointer error when trying to switch to the "equipment" tab while customizing a dropship in MegaMekLab. Seems to be any dropship, custom or base. Usually just doesn't switch to the equipment tab and lets you do anything else just fine. Sometimes chains the error message and forces terminating the program without saving. Does not happen when I try it on 0.49.17
![image](https://github.com/MegaMek/megameklab/assets/166643302/e8a3a386-68dc-443a-9a6c-a270b789406a)

Logs
[megameklab.log](https://github.com/MegaMek/megameklab/files/14935289/megameklab.log)

**Comment by IllianiCBT** [comment]
Fixed as of 49.19 :)

**Comment by TawnyFroggy** [comment]
Oh hah, sorry. I somehow didn't see .19 was released.

**Comment by IllianiCBT** [comment]
> Oh hah, sorry. I somehow didn't see .19 was released.

You're good. It's not out just yet, but this bug has been already fixed in the current Nightlies (which will become the 49.19 release).
