### ISSUE TITLE
Support Vehicle Export to Clipboard Includes HTML

### ISSUE THREAD

**Issue by JohnLangford** [MegaMek/megameklab#1479]
### Environment
0.49.18 from HQ's Meklab on Linux (Ubuntu).  openjdk version "11.0.22" 2024-01-16

### Description
When building a support vehicle -> VTOL -> Small, clicking on "Export ... to Clipboard" and then pasting reveals http elements in the upper portions of the pasted material.

### Files
An example is: 
Hoverbike (Laser)
<p>
<b>Mass: </b>0.5 tons<br/>

<b>Movement Type: </b>VTOL<br/>

<b>Power Plant: </b> Fusion<br/>
<b>Cruising Speed: </b>129.6 kph<br/>
<b>Maximum Speed: </b>194.4 kph<br/>
<b>Armor: </b>BAR 2</b><br/>
<b>Armament:</b><br/>
  		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6 Machine Gun (Portable)<br/>

<b>Communication System: </b>Unknown<br/>
<b>Targeting & Tracking System: </b>Unknown<br/>
<b>Introduction Year:</b> 3030<br/>
<b>Tech Rating/Availability:</b> D/X-E-D-D<br/>
<b>Cost:</b> 9,526 C-bills<br/>
</p>
	

  
Type: Hoverbike
Chassis Type: VTOL (Small)
Technology Base: Inner Sphere (Standard) 
Mass: 500 kg
Battle Value: 42
	
Equipment                                         Mass (kg)
Chassis/Controls                                  75.00000000000001
Engine/Trans.                                     250.0
    Cruise MP:12
	Flank MP:18
Heat Sinks                    0                     0.0
Fuel                                                0.0
Armor Factor (BAR 2)          0                    13.0

                          Internal   Armor   
                          Structure  Value   
     Front                   1         0     
     R/L Side               1/1       0/0    
     Rear                    1         0     
     Rotor                   1         0     
	

Weapons
and Ammo              Location    Tonnage   	
None
	
Cargo
    None

Notes: 
Features Ultra-Light Chassis and Controls Modification

**Comment by pavelbraginskiy** [comment]
Can't reproduce in 49.20 Snapshot, only getting plaintext. 

Can you check again in a newer version?

**Comment by pavelbraginskiy** [comment]
Got it, didn't realize at first you were talking about the TRO export.
