### ISSUE TITLE
No option to double-up on Ammo in Superheavy Mech Crits

### ISSUE THREAD

**Issue by Retry2000** [MegaMek/megameklab#148]
Pg.163 Interstellar Operations:
Ammunition: In the case of ammunition bins, every critical
slot of ammo placed in the torsos, arms, or legs of a superheavy
’Mech may carry up to two slots of ammunition. This rule does not
change the number of shots provided per ton of ammunition; it
merely reflects the number of ammo slots that may be “doubled 
up” in one critical space. Only ammunition of the same weapon
type may be combined in this fashion, but if the weapon in
question uses multiple ammo types, the different types (by ton)
can be combined in the same Superheavy critical slot. (In such a
case, the controlling player must always keep track of the different
ammo types that are sharing the slot.)

This ability to double-up ammo slots does not appear to exist for Superheavy Battlemechs in MML yet.

**Comment by neoancient** [comment]
![image](https://user-images.githubusercontent.com/16927464/37556498-0d65817e-29c5-11e8-844b-342c6728da45.png)
If you drag it to the location and drop it on a slot already containing one ton ammo for the same base weapon type it will share the slot.
