### ISSUE TITLE
0.49.18 Unable to View Equipment tab

### ISSUE THREAD

**Issue by Eruhin** [MegaMek/megameklab#1482]
### Environment
What version of MekLab does your issue apply to?  MekHQ's Megameklab
What operating system are you using?  Windows 10
What java version are you using?  Java 11.0.17

### Description
Whether I start a new unit, or load an existing unit, when I click on the "Equipment" tab, I receive an error, and the screen does not switch to the "Equipment" view.  When I mouse over where labels and buttons would be on the "Equipment" view, the labels and buttons will show up, displayed on top of the screen I was on when I clicked the "Equipment" tab.  
I sampled at least one unit of each unit type, and this issue appears to impact Warships, Dropships, Jumpships, Space Stations. Aerospace Fighters, Small Craft, and Conventional Fighter. 

[megameklab.log](https://github.com/MegaMek/megameklab/files/14949489/megameklab.log)

**Comment by IllianiCBT** [comment]
Known issue, fixed for 49.19
