### ISSUE TITLE
Feature Request: Lift certain restrictions on "Unofficial" Technology Level

### ISSUE THREAD

**Issue by Retry2000** [MegaMek/megameklab#149]
Some unit design exists in universe lore that are technically illegal by the current construction rules, including the Champion LAM & Scorpion LAM.  What if the Scorpion & Champion LAM were successful, paving the way for quad & even tripod motive types for LAMs, or LAMs heavier than 55 tons?  There are also other what-ifs that are less canonical that could be explored, such as what if the Clans didn't find the Superheavy Battlemech to be dezgra and experimented with the idea, or with Tripods.

The unofficial tech level is ideal for these what-ifs, and should allow the lifting of certain construction restrictions, to allow for construction of these what-if designs that are otherwise restricted to certain weights or tech basis (while otherwise retaining the same construction rules as described in the rulebooks).  Such restrictions include the following:

LAM:
  Clan Tech Basis
  60+ tonnage restriction
  Quad/Tripod Motives

QUADVEE:
  IS Tech Base

SUPERHEAVY MECH:
  Clan Tech Base

BATTLE ARMOR:
  IS VTOL/UMU MP

**Comment by scJazz2** [comment]
The unofficial designation exists to cover a bunch of stuff that was printed but never became canon (or was kicked out of canon). I think a better choice would be to add "Illegal" as a type.

**Comment by neoancient** [comment]
Some of this can be achieved by using a mixed tech base. There is no difference between a mixed tech LAM and a theoretical Clan LAM. You can do the same thing with superheavies and quadvees in most cases. The only cases where it would make a difference is if you are using a structure that has a different number of critical slots for IS or Clan, in which case you can either leave the extras unassigned (Clan superheavy) or make sure you have some open critical slots (IS quadvee).

Allowing different leg configurations for LAMs would require adding support for them in MegaMek, which would be a lot of work that I would consider much better spent implementing remaining legal units.

As to the request in general, I you refer you back to my comments on #125:
>>>The purpose of MegaMekLab is not to create and edit units, but to apply the construction rules to the process. Setting the tech level to unofficial will relax some of the universe details (year and tech base), but if you are looking for a general unit editor that doesn't apply the rules you are looking for a different program.

To this I will add that the unit files are plain text and are not difficult to figure out. You can create any unit that MegaMek is capable of understanding by editing the file.
