### ISSUE TITLE
[RFE] Make <ctrl>-<s> open "Save As..." dialog when model or variant name is changed

### ISSUE THREAD

**Issue by Sleet01** [MegaMek/megameklab#1490]
### Environment
Version: 0.49.19
OS: Ubuntu 22.04 Linux
Java Version: 17.0.10

### Description
I've experienced this issue myself, and other users have related similar complaints:  When editing a unit in MML with the aim of creating a new variant file, after editing the model or variant name, the \<ctrl\>-\<s\> shortcut does not do the expected action of creating a new file using the new model and/or variant name, but instead overwrites the originally loaded file with the updated version.

This would be acceptable if the user were to leave the model and/or variant name as-is, indicating an update to the existing unit.  But changing either of those fields indicates that the user intends to create a new unit.

The requested functionality would be:

1. When \<ctrl\>-\<s\> (or \<alt\>-\<f\>, \<s\>; or File -\> Save) is selected, compose a new filename from the model and variant fields (as is done for Save As).
2. Choose whether to Save or Save As based on the generated filename:
2.1: If the newly-generated filename matches the current filename (the two name fields have not been changed) save over the original file.
2.2: If the newly-generated filename _does not_ match the current filename, fire the Save As event instead.

This has two benefits over our current save system:
A. users can avoid accidentally overwriting files when they mean to create new variants.
B. creating a new series of Omnimech configurations from a "base" or "template" config is simplified, as each configuration will differ in variant name from the base version.

This may seem like an inconsequential change from the current functionality, but will save quite a bit of work for users who need to do a lot of file editing and end up relying too much on muscle memory for loading and saving files.

**Comment by pavelbraginskiy** [comment]
What is the expected behavior if the unit is loaded from a file not matching its name, and the name isn't changed?
Say I load a mek called 'UrbanMech UM-R60' from a file called 'Atlas AS7-D.mtf', and try to save it without changing the name?

**Comment by Sleet01** [comment]
> What is the expected behavior if the unit is loaded from a file not matching its name, and the name isn't changed? Say I load a mek called 'UrbanMech UM-R60' from a file called 'Atlas AS7-D.mtf', and try to save it without changing the name?
> 
> What if I change the name to 'Atlas AS7-D' and try to save it, should Save As trigger?

In the first case, using the approach I suggested, Save As would trigger.
In the second case, using the approach I suggested, Save As would _not_ trigger.  So my approach is bad.  But the person who did this is also bad :)

I am hesitant to introduce a state-tracking variable to MML, but we could record the original Chassis and Variant field values on load, and only trigger the Save As if those values don't match the initial values (ignoring the filename mismatch completely).  This would be slightly more work to implement correctly, but not a lot.

**Comment by pavelbraginskiy** [comment]
So we want Save As to trigger in any scenario where the original name doesn't match the filename?

**Comment by Sleet01** [comment]
> So we want Save As to trigger in any scenario where the original name doesn't match the filename?

That was my assumption, but your questions make me think that we just want Save As to automatically trigger whenever the Chassis or Variant field in the UI has been changed at the time that Save is requested.
