### ISSUE TITLE
CASE II Year availability bug

### ISSUE THREAD

**Issue by BlivetWidget** [MegaMek/megameklab#15]
On the equipment tab, CASE II says it's available in 3064 but won't show up unless the unit's year is set to 3081 or later.  Currently on MML 0.1.54 because 0.1.55 is too bugged to show the equipment tab.

**Comment by HammerGS** [comment]
Inner Sphere CASE II is available in 3064 when your Tech Level on the first tab is set to Experimental.  It doesn't become Standard until 3082

Thanks for the heads up on 0.1.55

**Comment by BlivetWidget** [comment]
Gotcha, sorry for the confusion on availability year.  Just getting back into BT after a couple years off.

**Comment by HammerGS** [comment]
No worries.  I you see other things your wondering about you can ask on either of the forums.

http://bg.battletech.com/forums/index.php?board=29.0

or

http://megamek.info/forums/index.php

**Comment by BlivetWidget** [comment]
I put something in the CBT forums a day or so ago regarding 0.1.55.  I added a few maybe-bugs to it as I continue to play around.  I don't want to spam the tracker here with maybe-bug reports, but if that's the procedure I'm happy to bug hunt that way.

I have to say, I think I preferred the old system of level 1, 2, and 3 rules.  The availability year thing, with unshown changes in tech level, can make for a confusing re-introduction.  CBT has also gone a bit nuts with how spread-out the rules are among different books.

I think I have a real availability bug now.  Looks like the Large Laser Prototype is only available under Unofficial Rules, no matter the year.  From Blake Documents- Jihad Secrets it seems to me that it should have the same dates as the other laser prototypes.

**Comment by HammerGS** [comment]
MM has a Era Specific (Unofficial) tech level where equipment that is based off specific era play or equipment that until recently (with the launch of IO) wasn't detailed in lots of fluff.  A lot of the primitive/prototype stuff fits into this category.

We are currently working through IO and upgrading all the equipment to use the new tech progression.  Under these rules all the canon equipment will be getting ratings based on IO including name changes to match what IO has.  The only equipment that will be left Unofficial is some of the fan weapons and equipment that has been included.

So in the case the Large Laser Prototype will be renamed - Primitive Prototype Large Laser be Experimental from 2306-2310 at which point the standard large laser will start to replace it as an experimental weapon per IO. It in turn progressing from Experimental to Common between 2306-2320

But this is a large undertaking and is taking lots of time.  In addition we still have to resolve how this will impact units as they move through time.

**Comment by BlivetWidget** [comment]
Okay, so what you're saying is... to ignore bugs like the prototype large laser availability, because all of that is being reworked as we speak.

It's the change in Tech Level through time that looks to be a headache from my perspective.  [Technology Ratings](http://www.sarna.net/wiki/Technology_Rating) are constant through time, while [Availability Ratings](http://www.sarna.net/wiki/Availability_Rating) change over time.  To be honest, now that those two systems are in place they should have done away with separate Advanced vs Experimental categories.  They should have only Intro, Tourney, and Advanced Tech Levels.  Anything in Advanced could then just be broken down into Technology Rating and Availability.  "Experimental" is really just another way of saying something has a really low Availability.

But I'm just ranting now.  You didn't make the system, you're just trying to operate within its framework.
