### ISSUE TITLE
MekLab is counting armor crit slots as extra tons of armor when costing units

### ISSUE THREAD

**Issue by sirbayer** [MegaMek/megameklab#1502]
### Environment
MekLab 0.49.19
Windows
Java SDK 17.0.10 (64-bit)

### Description
When MekLab is calculating the CBill cost for a given unit, it is incorrectly calculating the price, because it is counting all the crit slots of armor as instances of that same type of armor. This is most easily viewed on the King Crab KGC-000:
![image](https://github.com/MegaMek/megameklab/assets/5484128/7166ffa2-4956-460b-b425-be37a0640c59)
![image](https://github.com/MegaMek/megameklab/assets/5484128/f7533524-568f-4367-996d-3af354a98005)
![image](https://github.com/MegaMek/megameklab/assets/5484128/8ef0cd4f-4815-4723-a588-02c0c5c25c69)
The cost of this incorrect line-item appears to be equal to the cost of that tonnage of armor (e.g. 14 tons of Ferro-Fibrous armor does, in fact, cost 280,000 CBill).
This also happens on units with Standard armor, and even Stealth, but those only count as one slot.
This doesn't seem to be an omni-present issue - I didn't observe it on combat vehicles, at the very least.

**Comment by Gribbly1** [comment]
Similar issue with BA

![image](https://github.com/MegaMek/megameklab/assets/55139229/5244d518-022a-400c-a391-68f25c8cc533)

**Comment by Gribbly1** [comment]
Looks like the fix removed ammo costs from units.

**Comment by gsparks3** [comment]
Where are you looking for ammo costs? IIRC, MML always calculates "dry costs" nowadays (no ammo).

**Comment by Gribbly1** [comment]
Comparing to 49.19
