### ISSUE TITLE
RFE:  Add a "Custom" Filter to show only my customs

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megameklab#1508]
Title.  On the screen below, cant even see my 4 Centurion variants because there are so many canon ones.  A filter to show only custom mechs would be really nice.  Could do it with some sort of filter, or even simplier - just show mechs that appear inside the "Customs" Folder.

As an aside - should probably add an empty "Customs" folder to the default build and point to it as the initial MML save path...  Keeps us from having to explain that step every time.  

Thank you.

![image](https://github.com/MegaMek/megameklab/assets/23645569/5df9315d-c655-4e8d-80fb-b8bf03409328)

**Comment by Gribbly1** [comment]
![image](https://github.com/MegaMek/megameklab/assets/55139229/4c9afdcd-7b0d-4819-ba7d-93338012a952)

Setting 'canon' to 'No' in advanced search should display customs

**Comment by Thom293** [comment]
Thank you Gribbly.  Will close!
