### ISSUE TITLE
Turret disappered

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/megameklab#153]
### Environment
MMlab in mekhq-0.43.10-R4
Windows 7

### Description
While trying to update one of my older VTOL Omni Designs in MML (fixed crits to pod) I realized that the Turret section is not showing in Assign Criticals Tab. What´s more the Base Chassis Turret Weight is resetting to 0 even if saving the changes.

### Files
megameklablog isn´t showing any problems so i didn´t include it.
![mmlab](https://user-images.githubusercontent.com/18350902/39086162-ef993200-458d-11e8-931b-c4b83637932a.PNG)
![mmlab2](https://user-images.githubusercontent.com/18350902/39086164-efb4846a-458d-11e8-8add-5456b3b7b520.PNG)

[Garuda Heavy VTOL DFO.zip](https://github.com/MegaMek/megameklab/files/1934755/Garuda.Heavy.VTOL.DFO.zip)

**Comment by neoancient** [comment]
This was fixed with PR #154
