### ISSUE TITLE
Null point exception when exporting or trying to print Warship PDF

### ISSUE THREAD

**Issue by JoeJohnJordan** [MegaMek/megameklab#1537]
Version 49.19.1, Null Point exception when exporting or trying to print a warship to PDF.
![image](https://github.com/MegaMek/megamek/assets/112347372/0f8214d9-1915-4cfc-a4d1-141a8b074d37)

**Comment by Sleet01** [comment]
@JoeJohnJordan I'm not able to repro this specific bug with my 0.49.19.1 install and the provided files.

[Archive.tar.gz](https://github.com/user-attachments/files/15977900/Archive.tar.gz)

I do see the "While parsing file Urban Defense Tractor UDT-742.blk, could not find armor_type block." message with the other two files; this also occurs on 0.49.20-dev.
