### ISSUE TITLE
Cannot load gun emplacments

### ISSUE THREAD

**Issue by evanger** [MegaMek/megameklab#1570]
Using MegaMekLab 0.49.19.1 on Windows 11 version 23H2 (OS Build 22631.3880).

Trying to load from cache

![image](https://github.com/user-attachments/assets/ba7c15d8-eaaf-4dd9-aae9-eb1bfbb76eff)

...get this error

![image](https://github.com/user-attachments/assets/7f88dae2-b922-4732-a4df-605f47ee9d7c)

... then software closes

![image](https://github.com/user-attachments/assets/3e19cd93-7766-4fbe-a4f8-913b9fb88601)

**Comment by evanger** [comment]
To be fair, I am a brand-new user and might be missing something

**Comment by HammerGS** [comment]
MegaMekLab doesn't support Gun Emplacements. 

https://github.com/MegaMek/megamek/wiki/What-Units-does-MegaMekLab-Build-and-Print
