### ISSUE TITLE
RFE: Display heat dissipation with radical heat sinks 

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megameklab#1584]
Currently, units with radical heat sinks have a somewhat unhelpful Total Heat Dissipation value printed. Consider this Doloire: 
![image](https://github.com/user-attachments/assets/ff8896c9-42bf-4a48-b10b-f090a4c90178)

It can sink 32 heat when the RHS is off, or 48 with it on. It _never_ sinks 39 heat. 

It would be more useful to display this as `Total Heat (Dissipation): 43 (32 [48])`, similar to how movement points are displayed with multiple values when a unit is equipped with MASC or other such equipment. 

Similarly, this should also be used for Coolant Pods.

The RISC Emergency Coolant System might say something like `20 [26+x]`, but I'm open to ideas for more elegant notation.

**Comment by HammerGS** [comment]
I'm open to it, and kinda like it. But we'd have to run it past CGL

**Comment by Saklad5** [comment]
I just thought to make an RFE for this, and found someone already did. I think reusing the format for MASC and Superchargers would make more sense, wherein you put the enhanced heat dissipation in parenthesis.

With ten double heat sinks, a radical heat sink system, and a maximum of 24 heat generation, this could look like `24/20(30)`.
