### ISSUE TITLE
[49.20] Incorrect intro / availability for light ferro, heavy ferro

### ISSUE THREAD

**Issue by i-am-biosterous** [MegaMek/megameklab#1586]
### Environment
MegaMekLab v0.49.20
Windows 10 10.0
Java Version: 17.0.1

### Description
While making a 'mech with Tech level set to Standard and Year set to 3050, Light Ferro-Fibrous is available in the Armor Type dropdown. This is 17 years too early. It should have an introdate of 3067 (TechManual [2020 printing], p. 205).

Likewise, while making a 'mech with Tech level set to Standard and Year set to 3051, Heavy Ferro-Fibrous is available in the Armor Type dropdown. This is 18 years too early. It should have an introdate of 3069 (TechManual [2020 printing], p. 205).

![image](https://github.com/user-attachments/assets/38a11bf3-4d28-4f57-a7ca-ec6a081d0110)

![image](https://github.com/user-attachments/assets/3d8e0f0b-2b66-41fc-ab7d-4457091196e8)

**Comment by HammerGS** [comment]
MegaMekLab and MegaMek use the Tech Progression from Int Ops, combined with the Tech Progression Tables from TRO: Prototypes and NTNU RS.  This can also depend on if your using Variable Tech Level, or Standard Progression. 

<img width="659" alt="image" src="https://github.com/user-attachments/assets/90dc5769-3ff1-4808-9632-aff0618ec26e">
