### ISSUE TITLE
Nightly: megameklab-startup not working

### ISSUE THREAD

**Issue by repligator** [MegaMek/megameklab#1587]
### Environment
Linux
Java 17
MegaMekLab Nightly CI 1578

### Description
megameklab-startup does not work. When run in CLI it gives the following output:

```
Error: Could not find or load main class megameklab.MegaMekLab
Caused by: java.lang.ClassNotFoundException: megameklab.MegaMekLab
```
Running MML from the jar file works just fine.

**Comment by rjhancock** [comment]
Fix is in the OIF PR.

**Comment by SJuliez** [comment]
I assume this is fixed, therefore closing this. Please re-open if not fixed.
