### ISSUE TITLE
Nightly: Dropship NPE - megamek.common.Aero.getEngine()" is null

### ISSUE THREAD

**Issue by repligator** [MegaMek/megameklab#1588]
### Environment
Linux
Java 17
MegaMekLab Nightly CI 1578

### Description
Received the NPE when trying to preview or export a PDF of the attached BLK file.

### Files
[RMS Titanic Titanic.blk.zip](https://github.com/user-attachments/files/16517461/RMS.Titanic.Titanic.blk.zip)
[megameklab.log](https://github.com/user-attachments/files/16517463/megameklab.log)

**Comment by repligator** [comment]
Different file, different version of MML, same NPE.

### Environment
Linux
Java 17
MML Code Revision: b1b0bee27fee84bfe1af4375aba9a5423258cea7

[megameklab.log](https://github.com/user-attachments/files/16755134/megameklab.log)
[NPE Ship Prime.blk.tar.gz](https://github.com/user-attachments/files/16755137/NPE.Ship.Prime.blk.tar.gz)

**Comment by Sleet01** [comment]
This is a weird one for a few reasons:

1. I can't repro it on the latest code using the provided files,
2. Large Aeros don't even show the Engine Type block in their record sheets so this is sort of wasted effort in the print code,
3. It shouldn't be possible for an Aerospace unit of any kind to be valid without a set Engine, which we definitely check for.

Nevertheless, the NPE shows that it is possible to hit this state, and it is _conceivable_ that the call to get a unit's engine entry might return a `null` value, so I'll safety this.

**Comment by repligator** [comment]
I normally run MM/MML/MHQ from IDEA, but I have some nightlies installed on an old Thinkpad. When I open the attached files on the computer I normally use, running the latest MML from IDEA, they work fine. But there haven't been any commits in time between the https://github.com/MegaMek/megameklab/commit/b1b0bee27fee84bfe1af4375aba9a5423258cea7 and the present version of MML. Is it possible something changed in MM?

**Comment by Sleet01** [comment]
It's possible, yeah.  The code MML is calling at the bottom of that stack of calls is actually in MegaMek.
I'm just finishing up adding a unit test for this, then I'll try rolling the MM code back a bit and see if I can get a reliable repro with your files.
