### ISSUE TITLE
RFE: Show minimum crew requirements for combat vehicles

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megameklab#1591]
### Environment
v0.50.0-SNAPSHOT (2024-08-12 evening's nightly)
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
Show minimum crew requirements for combat vehicles as is done with support vehicles.

### Files

**Comment by RaozSpaz** [comment]
Unlike support vehicles this value doesnt change erratically and this is effectively unnecessary. A CV needs 1 crew member per 15 tons of weight.

**Comment by DynamicWorlds** [comment]
> Unlike support vehicles this value doesnt change erratically and this is effectively unnecessary. A CV needs 1 crew member per 15 tons of weight.

I misread or misremembered something apparently.  Understandable not to waste time on it, then

**Comment by SJuliez** [comment]
While it's not unthinkable to simply display the crew requirement, even if it is straightforward to calculate, I think it has no effect on construction on CV and so is probably not really important. Therefore closing this. Please re-open if this does seem useful, after all.
