### ISSUE TITLE
Pulse Laser Weight Problem

### ISSUE THREAD

**Issue by Shade-Zaku** [MegaMek/megameklab#1593]
[Templar TLR1-O (Shade).pdf](https://github.com/user-attachments/files/16647235/Templar.TLR1-O.Shade.pdf)

Windows 10

Issue with Templar TRL1-0 (Grayson). Was not able to reproduce issue with Rakshasa 2D, but I can get the problem to occur with any Templar unit

Pulse Weapons of any type are gaining extra weight when applied. Adding a single small pulse laser / Small X-Pulse Laser adds an extra ton for a total of 2 tons for a one ton weapon. Adding a second small pulse laser will correctly register as 1 ton, but adding another small pulse laser will again increase to 2 tons. 

Medium Pulse Laser / Medium X Pulse Laser issue is the same. It will add an extra ton for a total of 3 tons instead of 2. 

Large Pulse Laser / Large X Pulse Laser is the worst. Weight reads as 7 tons, but when adding weapon to the Templar, will add an additional 2 tons to read as 9. Unlike the other two, which read the correct weight with every other pulse laser of that type added, the large pulse laser will continue to register as a 9 ton weapon instead of a 7 ton.

Equipment Added when problem appeared:
Case
x2 Light Gauss Rifle 
x2 Er Medium Laser
Targeting Computer
x2 Medium X Pulse Laser 
x2 Light Gauss Rifle Ammo 
x1 Half Machine Gun Ammo
Machine Gun

**Comment by RaozSpaz** [comment]
You have a TC attached. You are probably going into other weight brackets for the TC increasing its weight.

**Comment by SJuliez** [comment]
Closing this as I think there is no issue here, as pointed out. Please re-open if TC weight is applied incorrectly.
