### ISSUE TITLE
0.50.0(/0.49.20?) Bug: Armor Tech Rating reverting to B

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/megameklab#1596]
### Environment
v0.50.0-SNAPSHOT (2024-08-20 evening's nightly and earlier) Unsure if pre 0.50.0 or not.
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
When trying to make a support vehicle with armor tech rating C, it keeps saving the unit as having armor tech rating B, which makes the unit invalid due to being overweight.
To reproduce, load unit, change to armor tech rating to C, save, and then reload unit.

### Files
[Buggy (Dune)FC.zip](https://github.com/user-attachments/files/16701433/Buggy.Dune.FC.zip)

**Comment by DynamicWorlds** [comment]
Update: manually editing the .blk file does work

**Comment by DynamicWorlds** [comment]
Did some more testing, and found that it occurs for all tech levels, saving as tech rating B no matter which tech rating is selected.

I'm also now 95% certain that this bug came into being with 0.49.20 as I remember needing to go back to an earlier version of megameklabs because of a bug I think was this one and I'm sure that was pre 0.50.00.  Unfortunately, I can't currently check it as I switched my Java version for the nightlies.

**Comment by johnboyjjb** [comment]
Units modified in MekHQ in 49.20 give the error when loaded into MML or MM. MM throws an invalid because the unit becomes very overweight but keeps the armor points as defined.

**Comment by johnboyjjb** [comment]
[Merkava Heavy Tank BS2.zip](https://github.com/user-attachments/files/16934711/Merkava.Heavy.Tank.BS2.zip)
This was kosher in 19.18(?) and then the start date for armor changed.
Now it shows invalid in MM. So I loaded it into MML and fixed it so it shows valid. But it won't show as valid in MM.

**Comment by Nehvar** [comment]
I might have some more light to shine on this since I just likely ran into this bug myself.  When saving an aerospace fighter with Clan Ferro-Aluminum armor the relevant output in the .blk is --

> <armor_type>
> 19
> </armor_type>
> 
> <armor_tech_rating>
> 0
> </armor_tech_rating>

-- but the program is looking for --

> <armor_type>
> 19
> </armor_type>
> 
> <armor_tech>
> 2
> </armor_tech>

-- to properly load the configuration.  If I don't edit the .blk each time I save to fix this it will load the configuration with IS Ferro-Aluminum instead of Clan Ferro-Aluminum, resulting in it being overweight.  This happens regardless of tech base.

**Comment by Nehvar** [comment]
Just found out that the exact same issue is occurring with ground vehicles and Clan Ferro-Fibrous armor.

**Comment by Sleet01** [comment]
Fixed by https://github.com/MegaMek/megamek/commit/62a30063077d5964af37f086c2327cd1916f8d1d; closing.
