### ISSUE TITLE
[nightly] Megameklab tarfile in latest nightly (1596) has mixed case issues

### ISSUE THREAD

**Issue by azhais** [MegaMek/megameklab#1599]
### Environment
MegaMekLab standalone, nightly build 1596

### Description
The megameklab.bat and megameklab executables have two copies with different cases in the latest tar

![megameklab_bin_case](https://github.com/user-attachments/assets/434cb266-964c-467d-8b66-e70fd6d9d4bc)
![megameklab_case](https://github.com/user-attachments/assets/21a7e998-8c86-487c-8613-7025ac1e9343)

**Comment by rjhancock** [comment]
This issue should be resolved in the next Nightly. I've checked the latest code (which includes modifications to build scripts) for duplicate files and there are none.

**Comment by SJuliez** [comment]
I'm going to assume this is solved. Please re-open if not.
