### ISSUE TITLE
Vehicle Sponson Turret missing for Support Vehicles

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1604]
The vehicle sponson turret is missing from the Other equipment list for Support Vee's. 

Per TO:AuE it's a CV and SV piece of equipment. It's indicated as support vehicle in MiscType.

**Comment by pavelbraginskiy** [comment]
For SVs it's a checkbox in the Structure tab (near where the checkbox for Omni goes on other unit types).

I actually opened  #1464 previously to "fix" this issue.

**Comment by HammerGS** [comment]
Right. Forgot about that.
