### ISSUE TITLE
Font Rendering

### ISSUE THREAD

**Issue by pmjdebruijn** [MegaMek/megameklab#162]
Hey,

Running MegaMekLab 0.44 on Ubuntu 16.04 with openjdk version "1.8.0_171", results in font rendering that is very different from all other applications.

Running MegaMekLab like this, gives better results (although still not quite identical):
$JAVA -Xmx512m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -jar MegaMekLab.jar

**Comment by SJuliez** [comment]
Closing this as this doesnt seem so much an error report as a note for Ubuntu users.
