### ISSUE TITLE
[50.0] Gurteltier (Both Variants) Missing from the MegaMekLab unit list.]

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megameklab#1622]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/cfe63b25-5f1e-4c5f-a93a-cfe174da6ef0)
When trying to locate the Gurteltier MBT, neither of its variants are available for access in MML. This unit was available in a prior version [49.19.1] and is a canon unit. So should be available. I am unsure as to how it suddenly vanished from the list.

### Steps to Reproduce

Simple
1. Launch MML
2. Activate all options
3. Type Gurt in the search bar. See no results.

### Operating System *

Windows 10

### Java Version *

Eclipse Adoptium 17.0.12

### MegaMek Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Sleet01** [comment]
I've marked this as a good first issue because it's already been solved in MegaMek; we just need to port the solution to MegaMekLab.
