### ISSUE TITLE
[0.50.0 and on] Support Vehicles Become Invalid When Saved, BAR Level Edition

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/megameklab#1631]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

When you save a support vehicle, its armor BAR and tech ratings change such that the armor weight is larger and causes the vehicle to be overweight, and the armor is too dense to be used without the armored chassis mod. Details below.

Tested in 0.50.0 and a recent nightly.

It's likely this is related to #1596.
It's possible this is related to #1489.
This might be what's causing the Sherpa variants to be invalid, or other support vehicles.

### Steps to Reproduce

1. Start MML and hit "New Support Vehicle"
2. First Page: Set Tonnage to 50, Cruise MP to 5, Fuel Mass to 5. Give the unit a Chassis and Model for the filename.
3. Armor page: Select BAR 7 Armor, maximize armor, auto-allocate armor. The armor tech level will be D by default.
4. Transport page: Click 'Use Remaining Tonnage for Cargo'
5. Press Validate Unit - validation passed
6. Save the file. Load the saved file. Say you don't want to save the file again.

The warning dialog will appear saying:
![2024-10-04_103051](https://github.com/user-attachments/assets/001e3ff3-c30b-4d39-8d96-9fbae74f11e9)

7. Hit OK and note that the armor tonnage on the first page has jumped up.
8. Go to the Armor Page again. Note that the armor type has changed to BAR 2, tech rating B, and the tonnage has increased.
9. You can now only select BAR 2 or BAR 3 armor.
10. Select 4 tons of rating B BAR 3 armor and hit Auto-Allocate
11. The unit is now under tonnage so go to the transport page and add another ton of cargo space.
12. Save and load the file again. It works this time, without being invalid.

These are the relevant blk files:

[Broken Step By Step.zip](https://github.com/user-attachments/files/17262221/Broken.Step.By.Step.zip)

### Operating System *

Linux

### Java Version *

17.0.12

### MegaMek Suite Version *

v0.50.0

### Custom MegaMekLab Version

v0.50.01-SNAPSHOT 2024-10-02

### Attach Files

megameklab.MegaMekLab.initializeLogging(MegaMekLab.java:81) - Starting MegaMekLab v0.50.1-SNAPSHOT
    Build Date: 2024-10-03T03:24:04.067850647
    Today: 2024-10-04
    Origin Project: MegaMekLab
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.1-203.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MegaMekLab: 1 GB
    MM Code Revision: a53044ee0763666eba74cdeaf511e150d291b1f0
    MML Code Revision: ec3384545ca567ddab36a47e886315bf1b77ab49
    MHQ Code Revision: 7eb17ed577293cf4fe52daeba4b0e9bf3223f902

Nothing of note appears in the log files.

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by UlyssesSockdrawer** [comment]
I've been able to reproduce this issue.

Steps to Reproduce
(1) - Open the Sherpa Armoured Truck in MML
(2) - Change nothing on the design. Add a variant name of whatever (I used 2).
(3) - Save the design to your customs folder somewhere. Close MML.
(4) - Reopen MML and try to load the design. Design shows as invalid for being 7 tons overweight.

**Comment by HammerGS** [comment]
Here is a screen shot of the failed unit. 

![image](https://github.com/user-attachments/assets/c6b44ca9-baa0-414b-baa9-833d2cddb02e)

**Comment by Sleet01** [comment]
@UlyssesSockdrawer NP, I'll take a look this evening.

**Comment by Sleet01** [comment]
It appears that this is more fallout of the armor / equipment updates, as I see _similar_ but not _identical_ issues in 0.49.19.1.

Interestingly, loading the Sherpa in recent releases does not show BAR 10 as a valid armor, even with Armored Chassis set, but saving off a copy of the .BLK file from MML keeps BAR 10 _iff_ no armor changes are made.  So I'd guess we are seeing a UI issue here.

**Comment by UlyssesSockdrawer** [comment]
With the Sherpa in particular, I believe it's meant to be BAR8 rather than BAR10, so there is an issue there with save/load of that vehicle at least.

**Comment by Insert25c** [comment]
Not sure if this is 100% related, but I'm hitting a similar issue on .50.01's MML building a condor variant. I save it when its valid, but when I reload the unit in MML (haven't tried it on MHQ) its says its invalid with 1 additional ton of armor. I've "fixed" the armor and saved it, but it comes right back with the extra ton. Ive removed 1ton of equipment and saved, but it just added another ton.

[Condor Heavy Hover Tank MB 1C.zip](https://github.com/user-attachments/files/18103888/Condor.Heavy.Hover.Tank.MB.1C.zip)

**Comment by gsparks3** [comment]
> Not sure if this is 100% related, but I'm hitting a similar issue on .50.01's MML building a condor variant. I save it when its valid, but when I reload the unit in MML (haven't tried it on MHQ) its says its invalid with 1 additional ton of armor. I've "fixed" the armor and saved it, but it comes right back with the extra ton. Ive removed 1ton of equipment and saved, but it just added another ton.
> 
> [Condor Heavy Hover Tank MB 1C.zip](https://github.com/user-attachments/files/18103888/Condor.Heavy.Hover.Tank.MB.1C.zip)

From testing, this vehicle has 9.5 tons of Clan FF (182 points), but when loaded in MML, loads as having 10.5 tons of armor (and is thus overweight). Suspected cause: the 182 armor points are being loaded as if they are IS FF instead (10.15625 tons, rounded up to 10.5). Issue seems related, but not identical, and may need to be split into its own issue.

**Comment by Sleet01** [comment]
This is now working correctly in 0.50.02-SNAPSHOT; closing.
