### ISSUE TITLE
[0.50.01 NIGHTLY - CI1635] Saving a Dropship Design with Mech Bays; Bays Disappear when the Design is Loaded

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/megameklab#1632]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

I suspect this bug is caused by the mech -> mek conversion.

When customising or creating a new dropship, it loses any mech bays assigned to it when it is saved. When the unit is reloaded, all bays except the added mech bay will be present and the tonnage shows as free on the design.

Loading existing designs such as the Union works fine in MML, so this seems to only apply to saving the custom.

This only applies to customising dropships from what I can see. No NPE is thrown.

### Steps to Reproduce

1. Load an existing, or create from scratch, a new dropship.
2. Add bays of different types, including mech bays.
3. Save the design.
4. Reload the design
5. Mech bays disappear from the design when it is loaded again, either in MML, MHQ, or MM.

### Operating System *

Windows 11

### Java Version *

17.0.12

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMekLab Version

50.01 CI1635 Nightly

### Attach Files

N/A

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Makaze2048** [comment]
Can confirm that the underlying issue is that it's writing out "mekbay" to the blk file which results in them disappearing when read back in. If you manually change to "mechbay" then things work fine. So assuming this is a result of the mass renaming

**Comment by UlyssesSockdrawer** [comment]
Thanks - I'll add to the bug catcher for name changes.
