### ISSUE TITLE
Sword is labelled as Advanced equipment instead of Standard

### ISSUE THREAD

**Issue by Da-Nuker** [MegaMek/megameklab#164]
MekLab 0.44.0 , Windows, Java8 1.7.1 64-bit

The BattleMech Sword is listed as Advanced Equipment and cannot be mounted on a standard tech 'Mech even after 3060.

In Interstellar Operations Pg 38, Universal Technology Advancement Table, it is listed as having a Common Date of 3060 and thus should be Standard Tech.

Existing 'Mech designs with Swords are not affected as they are labelled as Standard Tech in games.

**Comment by neoancient** [comment]
The entry in MegaMek was missing the common date.

**Comment by neoancient** [comment]
Fixed by MegaMek/megameklab@345b7f7
