### ISSUE TITLE
EDP Armor not showing up

### ISSUE THREAD

**Issue by Attaxalotl** [MegaMek/megameklab#1641]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Electric Discharge Protomech Armor does not appear in MegaMekLab.
<img width="1679" alt="Screenshot 2024-10-24 at 22 49 48" src="https://github.com/user-attachments/assets/33f9321d-2185-4a05-b770-f1419e68a2e2">

### Steps to Reproduce

1. Open MegaMekLab
2. Open a New Protomech
3. Open up the Armor Type dropdown Menu

### Operating System *

Mac

### Java Version *

Version 8 Update 421

### MegaMek Suite Version *

v0.49.19.1

### Attach Files

[logs copy.zip](https://github.com/user-attachments/files/17516202/logs.copy.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
Working in 0.50.0

<img width="830" alt="image" src="https://github.com/user-attachments/assets/70848269-38e5-4c28-8c3c-f23316f161f5">
