### ISSUE TITLE
Superheavy "Bad Engine" Pop-up

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megameklab#165]
### Environment
MegaMekLab 0.44.0
OS X 10.13.5
Java ~(no idea, it doesn't say in megameklablog.txt?)~ 8 Update 171?

### Description
Can't dismiss the "Bad Engine" pop-up when designing a superheavy mech with greater than maximum allowable engine size (600).

### Files
No errors in the log.

**Comment by neoancient** [comment]
I can't reproduce this. What was the order of steps that brought this about?
What I did was set the weight to 125 and the walking speed to 4, then tried both raising the walking speed to 5 and setting the weight to 150. In both cases I got the message box, but was able to dismiss it and the values were reset to the previous legal values.

**Comment by ndrwstn** [comment]
I can reproduce the error following your steps. Clicking OK doesn't get rid of the dialog (though I suspect it might be dismissing/reappearing, because the engine weight text moves a bit) and I'm forced to force-quit and restart.

What can I do that might help?

**Comment by neoancient** [comment]
Not being able to reproduce it leaves me in the position of having to trace through the code and see if I can guess, unless someone else is able to produce it and can figure it out. That's pretty labor-intensive and it'll be a while before I have the time to devote to it. In the meantime, watch your engine weights :)
