### ISSUE TITLE
Incorrect minimum doors required for cargo bays

### ISSUE THREAD

**Issue by Setsul** [MegaMek/megameklab#1667]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

A: The number of Doors on a Cargo Bay on Large Craft can not be reduced below 1.
B: This can also cause an IllegalArgumentException on saved (canonical) units that possess Cargo Bays with 0 Doors.
C: This also makes it impossible to add further Cargo Bays to Large Craft that are using the maximum number of Doors.

### Steps to Reproduce

A1. Add a Cargo Bay to a Large Craft.
A2. Try to reduce the number of Doors below 1.
A3. It won't work.

B1. Load any unit with a Cargo Bay with 0 Doors. E.g. Overlord (2762)
B2. Click on the Cargo Bay's number of Doors.
B3. IllegalArgumentException.

C1. Load any unit that uses its maximum number of Doors. E.g. Overlord (2762)
C2. Select Cargo as Bay type to add.
C3. "Add Bay" is unselectable/greyed out.

Cargo Bays are expected to behave like Infantry Bays, with **no** Doors being required.

### Operating System *

Linux

### Java Version *

Temurin 17.0.13+11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMekLab Version

v0.50.01

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Sleet01** [comment]
This will likely need updates in two places:
1. the MML UI, specifically around bays;
2. the `megamek/common/Bay.java` class (and subclasses) where minimums and maximums are defined.
