### ISSUE TITLE
Armored Chassis doesn't allow for BAR armor above 7

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#1668]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMekLab documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

We still have issues with Support Vehicle Armor. Working on fixing the Sherpa Canteen and it has an armored chassis but the armor caps out at BAR 7. 

![image](https://github.com/user-attachments/assets/c2605531-4e65-4c38-a38d-9655d66fd54c)

We need to add a check for armored chassis then allow the higher BAR armors. 

### Steps to Reproduce

Load the Sherpa and try to set the armor. 

### Operating System *

Windows 11

### Java Version *

Java 17

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMekLab Version

50.02 Nightly Dec 22

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Sleet01** [comment]
Fixed by https://github.com/MegaMek/megamek/commit/62a30063077d5964af37f086c2327cd1916f8d1d; closing.
