### ISSUE TITLE
Omni Vehicle Turrets Not Retaining Base Weight

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megameklab#167]
Environment
MegaMekLab 0.44.0
OS X 10.13.5
Java ~(no idea, it doesn't say in megameklablog.txt?)~ 8 update 171?

Description
Designing Omni-Vehicles with Turret; the base weight isn't being retained correctly.

Files
No errors in the log.

**Comment by neoancient** [comment]
The weight is not being retained at what point?

**Comment by ndrwstn** [comment]
I was fighting with this issue this afternoon with a couple omni-tanks, and now I can't reproduce it. I think it had to do with vehicles that didn't utilize it's turret in one configuration.

I'm sure I'll run into it again. I can re-open/start a new one when I have a more specific process to follow.

**Comment by ndrwstn** [comment]
Found it. My process is to create an omni-vehicle "base" (without any pods) and save it. This isn't retained when re-opening the file. Since the base turret weight must be assigned with the chassis, this means I have to go back to figure out what my turret weight is each time.

This may not be a bug, but the implementation could be improved.

**Comment by neoancient** [comment]
I used MML to create an empty chassis for the Badger omnitank, saved it, then reloaded, and the turret weight was set. I don't see any problem.

[Badger Chassis.blk.zip](https://github.com/MegaMek/megameklab/files/2221756/Badger.Chassis.blk.zip)

**Comment by neoancient** [comment]
Closing due to no problem found.
