### ISSUE TITLE
Replace Java-based open dialog with OS native dialog

### ISSUE THREAD

**Issue by ndrwstn** [MegaMek/megameklab#174]
### Environment
Environment
MegaMekLab 0.44.0
OS X 10.13.5
Java 8 update 171

### Description
File -> Load -> From File uses a Java-based open dialog; it would be preferable to use OS Native dialogs.

**Comment by neoancient** [comment]
Per this forum post: https://megamek.org/bb/showthread.php?tid=2637
OSX no longer has the ability to print to PDF through the Java print dialog. Switching to OS native would restore the functionality.

**Comment by rjhancock** [comment]
Updating URL to forum: https://forum.megamek.org/showthread.php?tid=2637
