### ISSUE TITLE
Equipment Table getting stuck on one equipment type.

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#178]
### Environment
MegaMekLab Version: 0.44.0
-Downloaded from github, alone, on the day this issue was created. 
OS: Windows 10 Home
Java: Java 8, Build 1.8.0_181-b13. 

### Description
Switching the selected equipment type in the Equipment window may bug the tables. 

I wanted to check if there is any weapon dealing 14 damage. 
With a fresh download, I stuck with the preselected mech, chose "Experimental" and "Mixed Inner Sphere", then switched to Equipment, chose "All Weapons", and sorted by damage. The result was that weapons were sorted by type, then by damage, and that wouldn't change anymore. I then tried just a specific weapon type, and I get the issue at the latest after the third switch. I have not been able to reproduce the issue without sorting by damage. 
Afterwards, only a restart helps - Whatever weapon type I'm stuck at, I can't get out of that selection. All other Tabs still work normally, though. 
Resizing may have happened at first usage.
![snipping](https://user-images.githubusercontent.com/19310656/43837257-3c81c0de-9b18-11e8-8859-b5a23a0319db.PNG)

I will try to reproduce this on a different PC running Windows 10 N Professional on Sunday. 
(Assuming this is the right place to report this)

**Comment by ndrwstn** [comment]
I've had that problem using MacOS. I believe I end-run it by checking/unchecking "show unavailable" as that seems to force a refresh of the table. A similar problems occurs when you use the filter box too much.

**Comment by wildj79** [comment]
As always, logs would be useful.

**Comment by UB-JM** [comment]
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2270858/megameklablog.txt)
Like this? 

I've now retried and shortest I can do is starting the program, going to equipment, and filtering by damage. At the latest after 2 switches (energy -> ballistic -> missile) it bugs out.

**Comment by wildj79** [comment]
Thanks, the logs were exceptionally helpful here. Looks like the sorter is crapping out on weapons that have AoE damage. Those weapon types have an `A` after the damage value, which insn't being parsed correctly. Should be a relatively easy fix.

**Comment by sixlettervariables** [comment]
Closed by #179
