### ISSUE TITLE
Long Tom Artillery Missing From Equipment Selector on Dropships

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#180]
With both Stable .44 and Dev .45.  Nothing in Logs.  If added manually to the blk file they will load.

Only Arty that shows to add is the Arrow IV.

**Comment by UB-JM** [comment]
Not saying you're wrong, but I just downloaded a fresh Stable .44 and I can select them in the equipment database, see them in "Current Loadout", and assign them to a facing. 
Of note, they are advanced. I do think it's rather irritating that LTCs are 'Experimental', but artillery was always advanced as far as I remember. 
It also loads fine.

**Comment by pheonixstorm** [comment]
Hammer, I could not replicate that issue in 0.44 or 0.45

I did have another issue crop up though. If I clicked on the manual BV text box it would reset the year to 2465. That kept happening in 0.44

**Comment by HammerGS** [comment]
Simple Text Level fixed here.

https://github.com/MegaMek/megameklab/issues/180
