### ISSUE TITLE
Cruise Missile Ammo on Dropships erratic allocation behavoir

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#182]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Stable 0.44 / Java 8

### Description
I'm trying to equip a 4000 Top Dropship with a Cruisemissile 50. 
Adding the cruise missile worked fine, with the usual hassle when trying to separate it from the Long Toms. 
But adding Ammo exhibited unusual behavoir. I first added the Cruise Missile in it's own bay, with 10 shots, and added them through the RMB context menu. That worked fine. 
Then I added 2 shots more, and dragged them over to the ship. 
Now I have 11 shots allocated, and 12 in the equipment tab, but none left for allocation. 
There is one missile left in "System" that doesn't show up on the crit allocation list. 

### Files
In the picture below, I removed two shots from the Dropship - 17 total, 15 equipped. It now shows the full 17 in the list on the right, yet still 15 in the ships nose. 
![image](https://user-images.githubusercontent.com/19310656/44093475-f35c5f98-9fd3-11e8-93a0-a258727971bf.png)
In fact, it turns out removing those shots has duplicated them - there's now 32 shots. 
I had to restart MML here because the Java UI broke. Loaded, deleted extra shots, added 2 more:
![image](https://user-images.githubusercontent.com/19310656/44093721-9bc5cc3c-9fd4-11e8-82a2-2b03cf58ad42.png)
Then dragged one of them over to the ship: 
![image](https://user-images.githubusercontent.com/19310656/44093745-abfe1186-9fd4-11e8-9a6d-05f04e5b2ab4.png)
As you can see, none left in "Unallocated Equipment", but : 
![image](https://user-images.githubusercontent.com/19310656/44093790-c92cab00-9fd4-11e8-992f-ddfe6766662e.png)
it's still there.
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2287030/megameklablog.txt)
The log doesn't seem particularly helpful, though maybe I'm overlooking something. :/

**Comment by neoancient** [comment]
The way MML identifies ammo that is part of a one-shot launcher is that it is unallocated and it contains a single shot in that slot. This hits a snag for cruise missiles, which have only a single shot in a slot to begin with, so when you allocate everything but the last shot it is seen as ammo for a one-shot launcher and not listed in the equipment left to be allocated. I fixed a similar issue several months ago with Davy Crockett Arrow IV ammo, which is 1 shot/ton, and included an exception for cruise missiles in the vehicle build tab, but missed dropships at that time.
