### ISSUE TITLE
Vehicular Stealth Armour Requirements

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#184]
I'm starting to feel bad for generating an issue here every 2 days.
### Environment
Stable 0.44
Java 8

### Description
Vehicular Stealth Armour apparently ignored requirements in MML. 
It places a crit in the vehicle's body, but it doesn't count against the limit. It should require two crit slots if memory serves. It also doesn't mind no heatsinks being free, which I tested by modifying the Red Kite VTOL. Doing the same in SSW would result in the unit missing 11.5 tons due to heatsinks and ECM requirements (the latter being a matter of settings), but having the same amount of free space, while in MML it gains two free crit slots. 

No error logs have been generated.

**Comment by neoancient** [comment]
Equipment is only listed once regardless of the number of slots taken up, but vehicular stealth still counts as two slots against the limit.
With standard armor:
![image](https://user-images.githubusercontent.com/16927464/44224732-f2565580-a150-11e8-9b3e-0b39591ab73a.png)
With vehicular stealth:
![image](https://user-images.githubusercontent.com/16927464/44224751-039f6200-a151-11e8-97be-f3a45446378a.png)
 However I noticed that changing back to standard armor does not clear the crit slots.

**Comment by neoancient** [comment]
MML also does not add the ECM generator for you automatically, but it should be failing validation if it doesn't have one.
