### ISSUE TITLE
Can't add BattleArmor bays to IS DropShips or Small Craft

### ISSUE THREAD

**Issue by TrailblazerDan** [MegaMek/megameklab#190]
In V. 0.45.0, there is no menu option to add BA bays to Inner Sphere DropShips or small craft (you can do it for Clan ships)
![mmlabbug](https://user-images.githubusercontent.com/19875435/44869834-8d285700-ac5c-11e8-9ee9-5f0c97af88db.PNG)

**Comment by HammerGS** [comment]
Can you attach the blk file here, also what year are you building them in?

**Comment by HammerGS** [comment]
![image](https://user-images.githubusercontent.com/13752452/44870181-b5a85500-ac4c-11e8-8652-09f132aeb994.png)

As soon as I can't the date to say 3050 they appear.

**Comment by TrailblazerDan** [comment]
Sorry, my mistake!
