### ISSUE TITLE
MegaMekLab unable to load saved MTF files

### ISSUE THREAD

**Issue by gwaedin** [MegaMek/megameklab#191]
### Environment
MegaMekLab 0.0.0.19
MegaMek 0.35.21-dev
Windows 7 / Windows 10 (verified on two different PCs)
Java version 1.8.0_181

### Description
'Mech files saved with MegaMekLab as MTF files (verified as valid) cannot be opened by the program.
The following error is given:
_Warning:Invalid unit, it might load incorrectly!
Exception from class java.lang.ArrayIndexOutOfBoundsException: 12_
Verified not only with units modified within MegaMekLab but also with plain HMP files downloaded from Battletech Encyclopedia (such as that for the MAD-5S).

### Files
[megameklab.log](https://github.com/MegaMek/megameklab/files/2349959/megameklab.log)
[Marauder MAD-5S.zip](https://github.com/MegaMek/megameklab/files/2349965/Marauder.MAD-5S.zip)

**Comment by HammerGS** [comment]
OK, the issue is you're using a staggeringly outdated version of both Megamek and MegaMekLab.

The version of Megamek/MegamekLab you have is from January of 2011.  I'll post a link on your forum post.
