### ISSUE TITLE
Large Aerospace Unit Tonnage Doesn't Update at Bottom of Screen 0.45.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#194]
I haven't quite figured out what triggers it, but the remaining tonnage at the bottom of the screen stops updating.  MML still calculates it, though, and it can be checked with the unit validation tools.

**Comment by neoancient** [comment]
I've been able to reproduce it a few times and what I've found so far is that when it calculates the weight the list of weapons is empty. But I haven't been able to recreate it reliably enough yet to determine what's causing that.

**Comment by UB-JM** [comment]
I get it everytime I switch unit type. So my usual approach now is to switch from jumpship to what I want to create, add the necessary minimum crew accomodations, safe, reload, then work on it.

**Comment by neoancient** [comment]
When changing the type a new ship is created, but the status bar still uses the original ship which is no longer being modified.
