### ISSUE TITLE
Multiple Items of One Ammo Type Don't Add to Available Tonnage for Large Craft 0.45.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#195]
Available tonnage seems to stop updating when adding more than one item of ammunition for a given weapon type.  For an example, I can add one item of 0.5-ton MG ammo, 1 item of AC/2 ammo, and 1 item of Gauss ammo.  If I add any more items of ammo for any of those weapons, their tonnage won't be accounted for.

**Comment by neoancient** [comment]
If you add ammo of another type does it suddenly account for all the ammo it wasn't adding before? It may be a failure to refresh when the number of cells doesnt change.
