### ISSUE TITLE
Changing year of loaded warship disintegrates weapons bays 0.45.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#199]
Steps to reproduce:

1) Load a _Leviathan II_ battleship
2) Go to the "Assign Criticals" tab and note that all weapons are in bays
3) Change year to 3070
4) Go to the "Assign Criticals" tab and observe that the ATM-12s are no longer in a single weapons bay, nor is their ammunition.

**Comment by neoancient** [comment]
Two issues here:
1. The tech progression date on ATM Bays in MM is wrong. It had the bay introduced in 3071, so it gets removed when the date changes to year before it was introduced.
2. If a bay is removed the equipment should be removed from the location rather than dumped there.
