### ISSUE TITLE
Primary/Secondary weapon selection doesn't function

### ISSUE THREAD

**Issue by VictorMorson** [MegaMek/megameklab#2]
This is a long standing joint issue between Megamek and Megameklab, but thought I'd bug it.  When you assign weapons to infantry, the last gun you assign is what is used by the unit; you cannot select between the weapons.  Likewise you cannot tag in Megameklab which weapon should be the primary.

It seems as if one of two fixes should be considered:  Allowing infantry in Megamek to toggle between weapons, or for Megameklab to have a tick box to pick the sole weapon for the unit.  I was unsure which project to bug it under as a result.

Steps to re-produce:
1) Create an infantry unit
2) Give them a support weapon such an SRM
3) Give them a new primary weapon such as an auto pistol
4) Save the unit
5) Note the unit can only use the auto pistol on board, and does not even show the SRM.

**Comment by pheonixstorm** [comment]
How many support weapons did you assign?

**Comment by HammerGS** [comment]
As Phoenix mentions, the weapons are abstracted into MM, there isn't really choice of weapon to fire.

See TM Pg#152
**Determining Final Range Values**
Determining which sets of range values apply to a platoon is simple. If the platoon fields 1 Secondary Weapon or less per squad, the ranges, modifiers and Damage Type that apply to the platoon’s attack are those of the Primary Weapons. If the platoon fields 2 or more Secondary Weapons per squad, then it is the Secondary Weapons’ range, modifiers and Damage Type that apply.
Any to-hit modifiers for the use of point-blank weapon types or weapons with a Crew Value of more than 2 (or a value of “1E”) apply as well, regardless of the number of Secondary Weapons.

**Determining Final Damage Values**
For instance, if a 4-squad Inner Sphere platoon of 28 uses a Primary Weapon worth 0.21 damage points, but also has 2 troopers per squad carrying Secondary Weapons with a Damage Value of 0.43, the sum of all damage together is equal to the damage of 8 Secondary Weapons (4 squads x 2 per squad) and 20 Primary Weapons (28 troops per platoon – 8 per platoon assigned to Secondary Weapons = 20 troops using Primary Weapons), or 8 damage points for the full platoon ([8 Secondary Weapons x 0.43]
+ [20 Primary Weapons x 0.21] = 7.64, rounded normally [up] to 8).

**Comment by HammerGS** [comment]
Closing as invalid
