### ISSUE TITLE
Mass Driver Ammo doesn't use up weight

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#206]
### Environment
version 0.45.1
Windows 10
Java 8

### Description
Mass Driver Ammunition on Warships doesn't cost any tonnage in MML. 
It costs 1 ton to add however many shots , then when they are allocated completely to the ship, that ton vanishes again. 

### Files
Not sure what files could be handy here.

**Comment by neoancient** [comment]
Same issue as #194. The calculated weight in the status bar is that of the jumpship that is created when first switching to advanced aero, which should be replaced when switching to warship. The new ammo weight is added because unallocated ammo is calculated separately.
