### ISSUE TITLE
Warship Crew Accommodation Officer Count/Quarters

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#207]
### Environment
0.45.1
Java 8

### Description
It reads in the tooltip that one in 5 crew is an officer, yet it requires one in 6. 
I wasn't sure if that was a bug or the recommendation is just more generous than the rules.

Now, unto crew accommodations. 
The new aerospace module assumes over-allocated officer quarters are first class passengers. 
Now, if the ship has, say, 10 passengers, with second class quarters allocated, and 20 officers, with first class quarters, and I add one first class quarters, then, upon auto-calculating the required quarters, the system will assume there's a first class passenger, thus substract 1 from second class quarters (so far, so good) and add one to first class. Then, clicking again will do that again, though at some point the rations changed. I thought it was 1/2/4, etc, but it was erratic. 
When starting with 47/50 and adding 1 to 47, then clicking "Auto-Assign Quarters" several times, I ended up with 147/0.

**Comment by neoancient** [comment]
The same crew assignment view is used for small craft/dropships, which require 1/5, and JS/WS/SS, which require 1/6. I updated it to show both values.

The auto assignment was accounting for the extra first class cabin in both the officer count and the 1st class passenger count. The fact that the rules combine officer/1st class and crew/passenger steerage but separate standard crew/2nd class passenger, even though they are essentially the same, makes for a rather complex process to make sure everyone is accounted for, and even then can only make a guess what the user might want.
