### ISSUE TITLE
MMLs don't seem to need gunners (0.45.1)

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#208]
### Environment
version 0.45.1
Java 8

### Description
I've been playing around with dropships today and weapons, as they should, require gunners -- 1 for every 6 guns, if standard scale. MMLs, however, seem not to. 
I've been able to add as many as I want without them requiring extra gunners.

### Files
Not sure what file is required here, there certainly was no error. 
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2430750/megameklablog.txt)

**Comment by neoancient** [comment]
Because MML range depends on the ammo, the range returned by the weapon itself is zero, so it was being treated like point defense weapons (any with range of one hex or less), which don't require gunners.
