### ISSUE TITLE
Superheavy critical space

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megameklab#21]
It seems that crit slots for superheavy mechs are still not computed properly.  The critical slots required by the engine, armor and possibly cockpit components should be halved (in the rules it says it applies to everything except actuators and internal structure).  Right now in Megameklab it works only for heat sinks and equipment you add from the equipment panel.

**Comment by arlith** [comment]
When I tested it, internals (superheavy endo-steel) and engines worked.  What didn't work was armor and the gyro.  Halving armor crits was done in MM in commit MegaMek/megamek@6ff9bc9.  I also added the superheavy gyro in MegaMek/megamek@e2bb623.

I also found that the Engine and Gyro criticals, while technically correct, weren't always updated properly when switching between superheavy and non-superheavy.  I updated some code in MML fix this.

It seems like all of the critical accounting for superheavies works now.
