### ISSUE TITLE
Superheavy printing issue: Armor distribution wrong?

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megameklab#210]
### Environment

Standalone Megameklab 0.44 and 0.45.1
Tested on Linux (Fedora and Windows)
Java 8
(Delete the above lines)

### Description
Please see attached mtf.  It will not print.  When changed to the armor distribution on the stock Orca, it does  print.  It does not produce an error.  Not sure if this is a rules issue; the file does validate.
(Delete the above lines)

### Files
[godzilla.zip](https://github.com/MegaMek/megameklab/files/2476048/godzilla.zip)

(Delete the above lines)

**Comment by neoancient** [comment]
There was a logic error in assigning positions for armor pips that could leave it in an endless loop trying to find a place for the last pip.

I'm not sure when the next release will be, but in the meantime here's your record sheet printed with the fix in place.
[Godzilla_GJRA-King_of_the_Monsters.pdf](https://github.com/MegaMek/megameklab/files/2493001/Godzilla_GJRA-King_of_the_Monsters.pdf)
