### ISSUE TITLE
Quadvees have issues with Quadvee cockpits and XL/XXL engines.

### ISSUE THREAD

**Issue by Apocal43** [MegaMek/megameklab#215]
MegaMekLab 0.44.0
Windows 10
Java version 1.8.0_181

### Description

Designing a QuadVee in MML. When initially selecting the QuadVee type, the QuadVee cockpit will be present but XL or XXL engine (if selected by default) will not register the correct number and placement of engine critical slots. Swapping back to SFE and then to XL/XXL will result in correct assignment, but will revert cockpit to a standard cockpit. 

### Files

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2518404/megameklablog.txt)

**Comment by neoancient** [comment]
The switching of the cockpit was an easy fix. It was simply missing the entry for restoring the quadvee cockpit when resetting system criticals. But I don't understand the part about the placement of the XL and XXL engine slots. I could not reproduce a problem. The default engine type when switching between mech configurations is always standard fusion.
