### ISSUE TITLE
0.45.2 Quad Protomech engine weight

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#223]
I tried to create an 15 ton, 3/5 Quad ProtoMech, when I noticed that the engine weight wasn't being correctly calculated.

It seems like the program calculates the engine weight of Bipeds and Quadruped identically, however quads use a different engine weight calculation, see IO page 101. 

### Environment
megameklab-windows-0.45.2

**Comment by snrdg102417** [comment]
Hello Maingunnery,


IIRC the application is primarily geared to the TM in which ProtoMechs, TM p. 82, cannot be constructed as quadrupeds (quads).


Tom Rux

**Comment by neoancient** [comment]
The problem appears to be that it does not refresh the weight summaries when the configuration changes. If you change to 4 MP then back to 3 you will see the smaller engine weight. But there seems to be a rounding bug there, as a 3/5 quad has an engine rating of 45, and being less than 50 the weight is ER x 250 kg, which is 11,250 kg but it's showing 1,000.

**Comment by neoancient** [comment]
Actually scratch that bit about the rounding. I was working from memory. The master 250 kg x engine rating is for ratings below 40, so the 1000 kg is correct. It's just a matter of forcing a recalculaton when the configuration changes.

**Comment by Maingunnery** [comment]
little side note:
The below 40 calculations use 25 kg x rating, not 250 kg x rating, 250 kg is the weight for heat sinks.
