### ISSUE TITLE
 Equipment Abbreviations 

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#226]
### Environment
0.45.2

### Description
Weapons and equipment with very long names, make the record sheet more difficult to read and use (see attached file). 
The "Weapons & Equipment Inventory" becomes difficult to read. While problems in the critical hit table may also affect the heat table and internal structure diagram

[Long Name Mek.pdf](https://github.com/MegaMek/megameklab/files/2617563/Long.Name.Mek.pdf)

My suggestion is: 
If the name/type exceeds 20 characters, then use an abbreviation on the record sheet.

**Comment by Xeno426** [comment]
I recall the Nova Combined Electronic Warfare System used to be called "Nova CEWS" in older versions, but its name got lengthened, which ends up requiring that it gets a font size reduction when printing a unit with it.
Would be nice if some of that stuff used the older abbreviations.

**Comment by neoancient** [comment]
When equipment data from IO was incorporated we made all the names consistent with the name given in the IO tables. There is code in place for providing an alternate shorter name for equipment, but we haven't done a good job with using it and maintaining it, so it'll be a bit of work to make sure all the equipment with longer names has an alternate shorter name. But I agree that this needs to be done.

**Comment by HammerGS** [comment]
I'll start working through the shortnames, which looks like got deleted when IO was implemented

**Comment by UB-JM** [comment]
I'd like to add something to this admittedly rather old issue:
The names of certain equipment, canonical as it may somehow be, between different iterations of a technology. (I could swear I've mentioned this somewhere before, but I couldn't find it) 
F.Ex. ECM and Probes - ok, that's the only cases I've noticed so far:
"ECM Suite (Guardian)" , "Active Probe (Beagle)" , which, I guess, fits well with, say ECM Suite [Clan].
But then "Bloodhound Active Probe" and "Angel ECM Suite". As we don't have a grouping by type, maybe just add an alternative name to toggle or use in searches?

**Comment by SJuliez** [comment]
For Meks, this works pretty well now with many short names implemented. Closing this.

![image](https://github.com/MegaMek/megameklab/assets/17069663/9b743598-ade6-431f-8283-928076f1524d)
