### ISSUE TITLE
Quality of Life Request: Weapon Heat and Dissipation

### ISSUE THREAD

**Issue by SidAlpha** [MegaMek/megameklab#227]
Environment
0.45.2

Description
Printing record sheets do not have an easy to view quick reference total combined weapon heat and Mech heat dissipation. Tabletop Simulator Record sheets have a simple yet effective listing underneath the Mech cost and BV.

![flashman fls-8k](https://user-images.githubusercontent.com/45480171/49274280-ae9c0900-f42c-11e8-8850-3a9f5bb9d85c.jpg)

My suggestion is:
Placing a Weapon Heat and Dissipation values underneath the BV or somewhere easily identifiable in the Mech Data field.

**Comment by Xeno426** [comment]
SSW does this as well.

**Comment by popnfloss** [comment]
Is this ever going to be implemented?

**Comment by sixlettervariables** [comment]
As this is open source software, the core developers work on items as time allows. We also pick and choose what we work on. That being said, we're open to anyone working to add new features and improve the product, so I invite you to jump right in and help!
