### ISSUE TITLE
ERLL missing from Protomech list

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megameklab#229]
### Environment
0.45.2
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
When creating a Protomech, lasers like the ER Large Pulse, Large Pulse, Heavy Large, and Improved Heavy Large lasers all show up as potential weapons. The ER Large laser does not, however.
In fact, opening the Sprite 2 file gives a warning that the unit is invalid because the ERLL is not a legal protomech weapon.

**Comment by neoancient** [comment]
That's because the ERLL is not a legal protomech weapon and the others are. See Tech Manual, page 343.

**Comment by Xeno426** [comment]
You sure? Looks like it takes up one slot.
https://i.imgur.com/h1PY2xP.png

**Comment by Xeno426** [comment]
There's also this post.
https://bg.battletech.com/forums/index.php/topic,21827.msg512241.html#msg512241

>Any weapon that occupies 6 or fewer critical spaces on a Mech can fit on a Protomech (unless expressly forbidden otherwise, and so long as it meets all the other already-existing requirements: weight limits etc).  The next errata release will feature the proper corrections - for now you can find the newly-available weapons in the TechManual errata thread.<
