### ISSUE TITLE
Spheroid dropship side arc equipment assigned to wrong location

### ISSUE THREAD

**Issue by 2ndacr** [MegaMek/megameklab#234]
Using 0.45.2
Windows 10
 Java 1.8._60

Cannot validate any spheroid dropship as no matter what it says left and right side do not match, when they do match. I have tried with multiple different dropships. New build, modification of existing, always says left and right do not match.
![dropship problem](https://user-images.githubusercontent.com/37711394/49839272-006d5900-fd74-11e8-9260-d18fa9c50f06.png)
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2669991/megameklablog.txt)

Screen shot attached

**Comment by HammerGS** [comment]
Can you attach the BLK file of the ship.

**Comment by 2ndacr** [comment]
I did not save it, but I can sure create another one for you,

**Comment by 2ndacr** [comment]
[Intruder (3055).blk.txt](https://github.com/MegaMek/megameklab/files/2670273/Intruder.3055.blk.txt)

Hope that helps Hammer. I noticed that when you right click to add the equipment to the different section of the ship, it says AFT, AFT-Right and then AFT again...….no AFT Left, but pretty sure selecting AFT Right actually loads stuff in the AFT left section.

**Comment by 2ndacr** [comment]
I have tried on multiple stock spheroid dropships, they all will not pass validation. I juts loaded a stock Hercules from the cache and there are no weapons in it's AFT-Right bay

**Comment by neoancient** [comment]
The index offset for the aft side arcs needed to be increased by one when the system-wide/fuselage/hull location was added, and it wasn't. It's an easy fix, but unfortunately there is no workaround. This should only affect spheroid dropships and small craft in 0.45.2.
