### ISSUE TITLE
Aero recordsheet not printing correctly

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#238]
### Environment
45.2 was reported, but having the same issue with the Repo
Windows 10
Java 8

### Description
Reported via PM.

Finally getting down to layout on the TRO...and I noticed one of my designs is missing dots in almost all areas. It is an Aero fighter with the following...

Front = 200 (this shows)
L/R Wings = 173 (these don't show)
Aft = 145 (these don't show)

Any thoughts? I'm using 0.45.2 now...and checked to see if it would display, and still doesn't. This file was created in a previous version (can't remember which) of MML.

Attached are the BLK files and a sample RS printed from the Repo.

### Files
[Habu.zip](https://github.com/MegaMek/megameklab/files/2705403/Habu.zip)
[Habu Prime.pdf](https://github.com/MegaMek/megameklab/files/2705404/Habu.Prime.pdf)

**Comment by Dragon41673** [comment]
I'm guessing since no responses, no one has looked into this yet?

Thanks

**Comment by neoancient** [comment]
While working on the wing and aft armor layout I noticed that the nose armor has a maximum of 200, which is exactly what this unit has. It's also blocky and in my opinion unsightly so I reworked that part also to use available space. This is what I have now:
![image](https://user-images.githubusercontent.com/16927464/51859927-ed035680-22fd-11e9-8dd3-461bcab94dd3.png)

**Comment by Dragon41673** [comment]
That will work just fine...thank you!

**Comment by neoancient** [comment]
Fixed by #246
