### ISSUE TITLE
MML 0.45.2 Windows Mech Images won't print

### ISSUE THREAD

**Issue by fuzbuckle** [MegaMek/megameklab#239]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MekLab does your issue apply to?  Note whether it is the stand alone MekLab or HQ's MekLab.
Environment
MegaMekLab 0.45.2 Development release
Windows 10
Java version 1.8.0_181
	Platform Windows 10 10.0 (x86)

Description
When printing mech record sheets, the image I have selected doesn't print.  I have tried saving the image to both /data/images/fluff/mech, and /data/images/fluff/data/fluff/mech, as the last time I had this issue, megaMekLab was looking in the latter path for the issue.  Neither option worked.  

Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2719493/megameklablog.txt)
[Flamberge.pdf](https://github.com/MegaMek/megameklab/files/2719494/Flamberge.pdf)
![flamberge](https://user-images.githubusercontent.com/38213107/50574939-720f5480-0dc0-11e9-91ae-eb5537c1bfd5.png)

**Comment by fuzbuckle** [comment]
Environment
MegaMekLab 0.45.2 Development release
Windows 10
Java version 1.8.0_181
	Platform Windows 10 10.0 (x86)

Description
When printing mech record sheets, the image I have selected doesn't print.  I have tried saving the image to both /data/images/fluff/mech, and /data/images/fluff/data/fluff/mech, as the last time I had this issue, megaMekLab was looking in the latter path for the issue.  Neither option worked.  

Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/2719493/megameklablog.txt)
[Flamberge.pdf](https://github.com/MegaMek/megameklab/files/2719494/Flamberge.pdf)
![flamberge](https://user-images.githubusercontent.com/38213107/50574939-720f5480-0dc0-11e9-91ae-eb5537c1bfd5.png)

**Comment by neoancient** [comment]
This was fixed in 35eab1a
