### ISSUE TITLE
ATM Standard Ammo Long Range Incorrect on Printouts

### ISSUE THREAD

**Issue by olaughlj** [MegaMek/megameklab#240]
MegaMekLabs 0.45.2, Windows 10 Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

When printing out mechsheets with ATMs, the standard long range is listed as 4 instead of 15. The Short and Medium Ranges are correct for the standard ammo and the ranges are correct for ER and HE ammo.
Below is a screenshot from a printout for the Hellhound showing the issue.

![atm ammo](https://user-images.githubusercontent.com/6819344/50621237-96f3ec80-0ed2-11e9-9d02-adb0bf6c4a83.png)

**Comment by sixlettervariables** [comment]
Yep:
```java
        } else if (eqInfo.isATM) {
            if (row == ATM_STANDARD) {
                return "4";
```
