### ISSUE TITLE
Quad Protomech Armor Diagram

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megameklab#253]
### Environment
0.45.3
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
When printing quad protomechs, the armor diagram remains bipedal and armor for the legs becomes incorrect.

### Files
![boggart quad](https://user-images.githubusercontent.com/3220418/53019344-1f463680-341a-11e9-810f-6fe5fcd21b7b.PNG)

**Comment by neoancient** [comment]
It's not a bug. It just hasn't been implemented yet, along with ultraheavies and gliders.

**Comment by Xeno426** [comment]
Well shoot, that means I still can't get an accurate Sprite 3 record sheet.

**Comment by neoancient** [comment]
You might be able to do an ultraheavy as long as the number of weapons does not exceed what is allowed in a standard weight proto. I'm not sure about the capacity to print armor and structure pips.

**Comment by Xeno426** [comment]
Just checked, there aren't enough dots for all the armor. :(
