### ISSUE TITLE
Some issue to allocate the components of LAM

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#260]
### Environment
Ver 0.45.3
Windows

### Description
For now, in MegaMekLab, Land-Air Mechs are not able to put the ammo other than left arm(not even right arm!), and is not able to put any weapons nor tags on their either arm as well. 

I have checked Interstellar Operations but nothing says you can't puy any weapons on LAM's arms, but is there anything that I didn't aware of? There is no errata as well.

**Comment by neoancient** [comment]
I'm pretty sure that what's going on here is that while generating the preview text the LAM's mode is getting switched to get all the MP values and it's getting left in fighter mode. Then it's being identified as a fighter when checking where ammo can be allocated. The left arm of a mech has the same location index as the fuselage of a fighter.
