### ISSUE TITLE
Magnetic Pulse SRMs/LRMs are not available

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#266]
### Environment
ver 0.45.3
Windows

### Description
Per 370. Tactical Operations, Magnetic Pulse missiles are available for both standard LRMs, SRMs and MMLs, but neither missile launchers are able to have the ammunition for it. I have checked the year(Introduced in 3057 and extinct in 3065) tech base(it is Inner Sphere tech) and Tech level(Experimental) but nothing happens. Even if I checked 'Show Unavailable' on Equipment and 'Show Extinct Tech', and 'Unofficial Ignores Year' on Configration then change the tech level to Unofficial, it was no avail. 

I have checked Battlemech and Combat vehicle are not able to pick the ammo, but is it a bug or it is not introduced in Megamek?

**Comment by neoancient** [comment]
They're not implemented in Megamek. This is not an issue with MML.

**Comment by HammerGS** [comment]
Mag Pulse weapons aren't coded into Megamek. This should also be on the Megamek tracker.

**Comment by binaryspica** [comment]
Oops, sorry.
