### ISSUE TITLE
Bug of interaction with Partial Wing, Improved Jump Jet and Hardened Armor

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#271]
### Environment
Ver 0.45.3
Windows 7

### Description
You know:
-Partial Wing increases 'mech's jump MP(+2 to light and medium, and +1 to heavy and assault, in the standard atmosphere).
-A 'mech can have Improved Jump Jet up to its Run MP.
-Hardened Armor reduces 'mech's Run MP by 1(or anything else that negatively affects Run MP would be applied to the case).

Well, in the normal case, if you have Improved Jump Jet and Hardened Armor, you can't put Improved Jump Jet more than its reduced Run MP, rather than basic Run MP.  If you do so then it can't pass the validation.

But, with Partial Wing(both IS and Clan tech), you can put Improved Jump Jet at your maximum limit but it passes the validation. 

For example:

Walk/Run/Jump 2/2(3-1 due to Hardened Armor)/3(with Improved Jump Jet) should trigger error on the validation, but with Partial Wing, it is considered as a legal unit as a 2/2/5(light and medium) or 2/2/4(heavy and assault) MP.
The same thing happens on 3/4(5-1)/5 as well, making it a legal 3/4/7 or 3/4/6 MP unit depend on the class.

I think that the problem happens because the presence of Partial Wing prevents to check the final Run MP and base jump MP, but I am not sure about this.

I am just tested it on battlemech, and I didn't touched protomech but it may cause the same problem if it shares the same system.

**Comment by neoancient** [comment]
Hardened armor does not reduce the maximum number of improved jump jets (TacOps, p. 281). A unit with a base move of 2/3 can still mount three IJJs even with hardened armor, in which case it has a movement of 2/2/3. The bug is not that the unit with a partial wing passes, but that the one without the partial wing fails.

**Comment by binaryspica** [comment]
Oops, I should read the full errata rather than the second printed version. Thanks!

**Comment by neoancient** [comment]
That's part of the text as of the 2012 printing.
