### ISSUE TITLE
Detachable Weapon Packs Not Appearing As Available Equipment

### ISSUE THREAD

**Issue by Kojak3** [MegaMek/megameklab#275]
### Environment

Tried MML versions 44.0, 45.0, 45.1 and 45.3
Windows 10 OS
Java version 1.8.0_31

### Description

Despite all settings set necessary to make DWPs appear (rules level, BA weight, etc), DWPs do not appear as available equipment. The only way to make DWPs appear in the list that I can find is to load a unit that already has them; that said, as soon as you delete the DWPs from the design, they no longer appear in the list of available equipment either.

**Comment by neoancient** [comment]
I can't reproduce it. While it doesn't appear when I first switch to BA, if I set the rules level to advanced, raise the weight class to medium, and add enough MP to cover the MP reduction the detachable weapon pack appears in the equipment list.

**Comment by Kojak3** [comment]
Oh dammit, I can't believe I didn't think of adding MP. That's what it was. Never mind, this isn't a bug, please cancel this ticket.

**Comment by Kojak3** [comment]
Nvm, I see I can do that myself.

**Comment by neoancient** [comment]
I think it could be improved by making it set the minimum MP when installed rather than filtering it out based on what the MP is set as.
