### ISSUE TITLE
Wrong rounding for Partial Wing

### ISSUE THREAD

**Issue by Zakerst** [MegaMek/megameklab#280]
Environment: MekLab version 0.44, from the MekHQ download, operating in windows 7, the megameklablog.txt doesn't state java version, but found it to be Version 8 Update 201 (build 1.8.0_201-b09).

Description: the rounding of the partial wing appears to be off, possibly rounding twice? The stated weight of the partial wing is "5 percent of the ’Mech’s total mass (rounded up to the nearest half ton),.." (TO, 292) 5% or .05 of 55 is 2.75; rounded to the nearest half ton should be 3, but is showing 3.5. Seems to occur in other weights as well as I've been experimenting with the Partial Wing trying to make a decent/interesting 'mech utilizing it. 
[RequestedFiles.zip](https://github.com/MegaMek/megameklab/files/3031238/RequestedFiles.zip)

Thanks for looking into this.

**Comment by neoancient** [comment]
The problem is not that it's too heavy, but that it's too light because it's rounding in the wrong direction. The 5% is for a Clan partial wing. An IS partial wing is 7% of the total tonnage. For a 55 ton 'mech this is 3.85, which should be rounded up to 4 rather than down to 3.5.

**Comment by HammerGS** [comment]
This fix seems to have broken the rounding on the Agrotera AGT-1A.  It's a 50 ton Inner Sphere mech.  So the wing should be 50 * .07 = 3.5 tons, but it's round to 4 tons now.

```
Mech: Agrotera AGT-1A
Found in: data\mechfiles\mechs\3145\Liao\Agrotera AGT-1A.mtf
Intro year: 3108
BV: 1578    Cost: 10,642,500
Chassis: Agrotera AGT-1A - IS_Advanced (3108)
Movement: 6/9/6
Weight: 50.5 is greater than 50.0
Engine: 300 XL                                                     9.50
Structure: 83 (Endo Steel)                                         2.50
Standard Cockpit:                                                  3.00
XL Gyro:                                                           1.50
Heat Sinks: 10 [20]                                                0.00
Armor: 152 (Standard)                                              9.50
Equipment:
Jump Jet            LL                                             0.50
Jump Jet            LL                                             0.50
Jump Jet            RL                                             0.50
Jump Jet            RL                                             0.50
Actuator Enhanceme..LA                                             1.50
**Partial Wing        LT                                             4.00**
Jump Jet            LT                                             0.50
Jump Jet            RT                                             0.50
ER PPC              LA                                             7.00
Medium VSP Laser    RA                                             4.00
Medium Pulse Laser  RA                                             2.00
Small Pulse Laser   LT                                             1.00
Small Pulse Laser   RT                                             1.00
TAG                 HD                                             1.00
```

**Comment by neoancient** [comment]
It's a bit of floating point imprecision. 50 * 0.07 is coming out to slightly over 3.5, so when it gets rounded to the next half ton it ends up 4.0.
