### ISSUE TITLE
Issue printing BV to Record Sheet.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#281]
From this forum post - 
https://bg.battletech.com/forums/index.php?topic=64910.msg1494555#new

The BV calculations are considerably different. Nothing in the logs.

### Environment
What version of MekLab does your issue apply to?  45.4
What operating system are you using?  Windows

### Files
Printed from MML
[Mongoose C.pdf](https://github.com/MegaMek/megameklab/files/3045956/Mongoose.C.pdf)

Printed via a MUL and used in the RS Book
[Mongoose C from RS Tokasha.pdf](https://github.com/MegaMek/megameklab/files/3045958/Mongoose.C.from.RS.Tokasha.pdf)

MTF File
[Mongoose C.zip](https://github.com/MegaMek/megameklab/files/3045962/Mongoose.C.zip)

**Comment by neoancient** [comment]
The option to ignore the pilot when printing from a MUL won't print the name or the skills, but the default for calculating BV is to use the skills. A 38% increase in BV is what you get from having a standard Clan 3/4 pilot. It needs to apply the same logic there. So what to do with C3 adjustments? I think probably use the same logic. If we're ignoring the pilot we're going to ignore any C3 configuration (which may be present if the MUL is produced by the force generator.

**Comment by HammerGS** [comment]
Yes, we should ignore the C3 modifier
