### ISSUE TITLE
Cannot separate capital missile weapon bays on dropships 0.45.3

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#285]
I have an aerodyne dropship loaded with Barracuda missile launchers, four to each side.  I want to split the weapon bays so that two of the launchers are rear-facing.  However, MML won't let me split the bays and only changes the facing of the entire Barracuda missile bay.

**Comment by neoancient** [comment]
You create a split bay by assigning a launcher to a new bay explicitly.
![image](https://user-images.githubusercontent.com/16927464/56311204-12407d80-6113-11e9-912b-632ade716807.png)

**Comment by BLR-IIC** [comment]
Wow, I'm not sure how I missed that.  Thank you for responding to my apparently non-bug report :)

**Comment by neoancient** [comment]
It's easy to miss because it only shows up if you have a single item selected. When you have multiple items selected it can get complicated to try to come up with a list of possibilities that apply to all the selected rows, so you just get a list of locations.
