### ISSUE TITLE
0.45.4 Maximum armor on a primitive jumpship is too high. 

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#288]
As per the most recent errata, primitive jumpships have the same maximum armor allowance as warships of similar mass and structural strength (structure tonnage/50) . I am not certain what system megameklab is using to determine maximum armor allowance on primitive jumpships, but it's way too high.

**Comment by neoancient** [comment]
It was using the calculation for jumpships per the text in IO, but that number was wrong. I'm not sure where the number came from, but I guess it was a typo that was computing the maximum as vessel tonnage * SI points / 1800, which works out to SI tonnage / 1.8. While correcting that I noticed that space stations are also off by a factor of 10 and I've changed primitive jumpships to use the warship value as per the errata.
