### ISSUE TITLE
0.45.4 other problems allocating armor to primitive jumpships

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#289]
The armor bonus from structural integrity for primitive jumpships is being assigned as two thirds of its normal value, even when using standard armor

Under standard rules, the 2/3 armor value only applies when the ship is equipped with primitive armor. 

Also, in the case of retrotech vessels using armors other than standard, the data in the points per ton box does not correspond to what you are getting per ton, or what you should be getting per ton.

**Comment by neoancient** [comment]
The free armor points from SI are based on the tonnage of structure and have nothing to do with the type of armor installed. As for retrotech jumpships with advanced armor, there was one bug affecting the points per ton displayed and another was giving only the number of armor points you would get from primitive armor regardless of the type of armor selected.

**Comment by LiamsGhost** [comment]
Per the example on page 131 of interstellar operations, the primitive armor multiplier applies to the total number of armor points the vessel has, _including_ those points provided by structural integrity:

David then multiplies the 69 tons of armor he has opted for
by the standard Advanced Aerospace Unit Armor Weights for a 100,000-ton Inner Sphere JumpShip using standard armor, and finds that this yields 55 armor points [69 (armor tonnage) x 0.8 (standard armor for a 100,000 vessel) = 55.2, rounding down to 55]. He then adds the free 6 points to 55 for a total of 61. **Multiplying this total armor value by the Primitive armor factor of 0.66, he finds he has 40 armor points to allocate** [61 (non-Primitive armor points) x .66 (Primitive armor factor) = 40.26, rounding down to 40].

If the primitive armor multiplier didn't apply, then the program would be in error by not providing sufficient armor points for the structural integrity provided, as a primitive jumpship with an SI of 100 recieves only six free armor points instead of the ten it should get.
