### ISSUE TITLE
Jump Jet issue with modular armor

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megameklab#29]
Version 0.1.58
Made a 55 ton 5/8/5
Added modular armor and jump was listed a 2 and only one showed in assign crits tab.
Altering the number of jump jets seems to reset the one jump jet from any assigned critical slot back to the hopper waiting to be assigned.  
Trying to remove the jet from the movement arrows does not work and to remove the jet it must be assigned to a critical slot and right clicked for delete item.

Also trying to set the type of Jump Jet to anything other than standard or mechanical booster does not work.

The rules for it are in TO pg 280-281, and mention there is errata for it on Pg 17 of June 2016 Errata release.

**Comment by Dylan-M** [comment]
#33 and this are probably the same issue.
