### ISSUE TITLE
Quality of Life Request: Remember Load Path

### ISSUE THREAD

**Issue by mommmomm** [MegaMek/megameklab#293]
### Environment
megameklab 0.45.4 / win 10 / 64bit

### Description
Loading a unit from file always starts in the data/mechfiles directory. 
While it might be a reasonable assumption for first-time loads, whoever stores units in a different location (e.g. in a users documents folder instead of somewhere inside a programs directory hierarchy) has to manually change directories on every single load.

https://github.com/MegaMek/megameklab/blob/16915d7a9ddc6ac2e66c82a517434f636d5bd430/src/megameklab/com/util/MenuBarCreator.java#L1274

It would be great, if - at least for the current session, it doesn´t even have to be permanent - the last "load from file" directory could be used as a starting point for new loads. This would reduce the click-count a lot (especially for peoply with structured filesystems...) .

From my unserstanding, making filePathName a private class variable, initialized from  System.getProperty("user.dir").toString() + "/data/mechfiles/" only on the first access would perfectly do the trick, but I didn´t dig any deeper, so maybe it´s not that simple.

Best regards...

**Comment by mommmomm** [comment]
Rechecked in 0.47.1 - Load dialog now starts at the last load location (from the current instance). From my understanding, this is a positive side-effect from the newly structured file dialog loadUnitFile() etc.

From my point of view, the feature request ist thereby fulfilled - thanks alot, team!

**Comment by neoancient** [comment]
That behavior is system-dependent.
