### ISSUE TITLE
Vehicular Stealth doesn't contribute to heat sinks

### ISSUE THREAD

**Issue by harageth** [MegaMek/megameklab#298]
https://github.com/MegaMek/megamek/pull/1101 seems to indicate that this was already fixed (I certainly can't make head nor tail of that 4000 line java file... I can definitely see how the armor is being validated but I can't see how the heatsinks are being calculated) but I am still seeing the issue despite the fact it says it was fixed in the version I am running.

### Environment
I am running Version 0.44.0 on Mac Mojave 10.14.5
java version "1.8.0_91"

### Description
While attempting to create a sheet for the Strix (http://www.sarna.net/wiki/Strix) I noticed a weight discrepancy when finished. On further inspection I realized the issue was that it didn't assign the 14 heatsinks like TRO:3150 says it should have.
The rules for this are indicated in Tactical Operations pg 282

### Files
There are no errors being reported by the application and it says that the unit validates correctly

**Comment by harageth** [comment]
<img width="763" alt="Screen Shot 2019-05-26 at 3 48 15 PM" src="https://user-images.githubusercontent.com/2456170/58388205-aafad080-7fd0-11e9-873b-9d79bcca414a.png">
<img width="574" alt="Screen Shot 2019-05-26 at 3 48 34 PM" src="https://user-images.githubusercontent.com/2456170/58388206-acc49400-7fd0-11e9-9225-3649ee7feaac.png">

Forgot to upload the screenshots

**Comment by neoancient** [comment]
You are using a version that was released two months before the fix. The first version with the fix in place is 0.45.2.
