### ISSUE TITLE
LAM reports Walk MP same as its Jump MP

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#301]
### Environment
Ver 0.45.4
Windows 7

### Description

As title says, if a Land-Air Mech have a Medium Shield on its either of arms, its Walk MP on MegaMekLab is fixed to the same value as its Jump MP, and its Walk MP totally ignores -1 modifier by Medium Shield - but popup popped when pull the cursor to final Walk MP value it says '-1(shield).' If you change the Jump MP its final Walk MP is changed as well.

It also had a problem on MegaMek, though, but I will write the problem on there.

I suspect that the problem is occured because of 'Jump MP 3' rule of LAM construction. 

### Files

[Shadow Hawk LAM Shield Test 001.zip](https://github.com/MegaMek/megameklab/files/3253475/Shadow.Hawk.LAM.Shield.Test.001.zip)

**Comment by neoancient** [comment]
This happens regardless of whether it has a shield.

**Comment by neoancient** [comment]
I tracked it down to the TRO view generator, which switches it to airmech and fighter mode to get the MP, but fails to switch it back to mech mode. So after the first change is made that causes it to refresh the TRO view it shows safe thrust/max thrust/jump.

A separate issue is whether a LAM should be able to use a shield at all. According to this post, use of physical weapons by LAMs is limited to picking up a club, but they cannot be constructed with physical weapons: https://bg.battletech.com/forums/index.php?topic=52456.msg1236486#msg1236486
