### ISSUE TITLE
Double Sponson Weight

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#304]
### Environment
megameklab-windows-0.45.4
Java version 1.8.0_211

### Description
The current version of MML effectively doubles the weight of Sponson turrets.
The 10% of total capacity is for the L&R pair, not each individually: 
https://bg.battletech.com/forums/index.php?topic=33987.msg792520#msg792520

An possible related issue that could influence any solution is if either Vehicular Sponson Turrets can be pod-mounted or have a fixed capacity on Omni-Vehicles (like all turrets). My suggestion for the later case would be to move the Sponson turrets to the first tab with Chassis options so that it is with all the other turret options. 

### Files
[test-example.zip](https://github.com/MegaMek/megameklab/files/3269429/test-example.zip)

**Comment by neoancient** [comment]
While working on support vehicle construction I recognized the need for omnis to determine the weight of sponson and turret mounts as well as basic/advanced fire control. I haven't done the sponson and pintle weights yet, but when I do I'll be adding the sponson section to combat vehicles.
