### ISSUE TITLE
Request: EDP armor in latter eras

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#307]
### Environment
megameklab-windows-0.45.4
Java version 1.8.0_211

### Description
Electric Discharge ProtoMech armor becomes unavailable in the armor type dropdown after it becomes extinct, I would like to request a workaround, such as having the 'show unavailable' checkbox have an effect on the armor type dropdown.

**Comment by neoancient** [comment]
There is an option to show extinct equipmrnt on the tech advancement tab of the configuration dialog, accessed from the file menu.
