### ISSUE TITLE
Request: WS/SS Additional bay types

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#308]
### Environment
megameklab-windows-0.45.4
Java version 1.8.0_211

### Description
The "Reinforced Repair Facility (Unpressurized)" is missing from the bay options, could it please be added?

This might also be a good opportunity to add a 'Manual Input' or 'Industrial Equipment' bay to cover:
Ore Processing Equipment - Snowden Space Station
Workshop/Manufacturing Equipment - Newgrange YardShip

**Comment by neoancient** [comment]
The reinforced repair bay requires the tech level to be set to experimental.
