### ISSUE TITLE
Drone (Remote) Carrier System operator tonnage

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#309]
### Environment
megameklab-windows-0.45.4
Java version 1.8.0_211

### Description
Right now the tonnage for the Drone Carrier Control System fixed at 2 tons, but it needs additional tonnage for each drone operator (1 per drone).
TO p304: "The Carrier Control System for remote drones weighs 2 tons, plus 0.5 tons per controlled drone unit."

This also means that the number of operators need to be shown on the record sheet.

**Comment by binaryspica** [comment]
Since Drone (Remote) Opreating System is not implemented on MegaMek, I don't think they will fix it near future.

For suggestion, making it 2.5 ton, and also add 'additional drone control' that costs 0.5 ton and requires no slot seems an easy fix.

**Comment by neoancient** [comment]
Not true. MML was created primarily to support MM, but there are people who use that don't ever use MM, and we try to make all the construction data correct regardless of whether it works in MM.

**Comment by Maingunnery** [comment]
What about a right-click function (to add or remove operators/drones) on the item in the 'assign criticals' tab?

**Comment by neoancient** [comment]
Extra operator capacity is what "Drones (as Extra Equipment)" does. Each one increases the weight of the control system by 0.5 tons. I don't think it's very clear from the name what it's for.

**Comment by Maingunnery** [comment]
I found out why I had this issue, I was designing a Clan unit with the Drone Carrier system which is Base All, but the "Drones (as Extra Equipment)" is Base IS, so I didn't see it. So that should be corrected.

Also an enhancement would be, if we can find the drone quantity on the record sheet.

**Comment by neoancient** [comment]
This was fixed by MegaMek/megameklab#1894
