### ISSUE TITLE
ProtoType Jump Jets Missing from Dropdown

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#31]
When building a mech with prototype Jump jets they are missing from the Jump Jet drop down menu.

Steps to duplicate
1) Set MML to build a unofficial Tech Level
2) Set year to between 2464-2471 (Prototypes should be available during this time)
3) Add Jump Jet Move
4) Check Drop down menu and notice only Standard and Improved available

Incidentally Improved shouldn't be available during this time.

**Comment by neoancient** [comment]
I've added experimental-level jump jets to unofficial, but the jump jets dropdown does not filter by year. I intend to make that part of a more general overhaul of the way equipment type choices are presented.
