### ISSUE TITLE
Incorrect heat for Nova CEWS

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#311]
### Environment
megameklab-windows-0.45.4
Java version 1.8.0_211

### Description
The Nova CEWS is a piece of equipment that produces 2 points of heat, but this heat isn't included in the current equipment list. 
IO p66: "The Nova CEWS generates +2 heat while active."

**Comment by neoancient** [comment]
General fix that shows heat values for non-weapon equipment, including null/void sig system, chameleon LPS, et. al.
