### ISSUE TITLE
IS version of Light Machine Gun Ammo[Half] is not available for Inner Sphere Tech Base

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#314]
### Environment
Ver 0.45.4
Windows 7.

### Description
As title says. On Inner Sphere tech level, it is not shown unless you check 'Show Unavailable' option. But it is available if you change it to Mixed Inner Sphere, which is weird. IS full Light Machine Gun Ammo(IS) is always available, meanwhile.

It seems that Clan Machine Guns and the other Machine Gun Ammos are fine and only Half Light Machine Gun Ammo(IS) have the problem.

### Files
![p03](https://user-images.githubusercontent.com/47907439/59526708-88474200-8f14-11e9-8c32-52590d36a7cb.png)
![p04](https://user-images.githubusercontent.com/47907439/59526712-8aa99c00-8f14-11e9-8215-9873b2dd6693.png)

**Comment by binaryspica** [comment]
It seems that the problem is on [AmmoType.java](https://github.com/MegaMek/megamek/blob/master/megamek/src/megamek/common/AmmoType.java#L5803).

On line 5744, in  Light Machine Gun Ammo(Full), it says:

> .setISAdvancement(3064, 3068, 3070, DATE_NONE, DATE_NONE)

But, on line 5803, the counterpart of it in Light Machine Gun Ammo(Half), it says:

> .setClanAdvancement(3055, 3060, 3070, DATE_NONE, DATE_NONE)

I am not familar of MegaMek code, but it seems that use setClanAdvancement instead of setISAdvancement making it only available for Clans, not Inner Sphere.

**Comment by NickAragua** [comment]
Fixed with Megamek PR #1383
