### ISSUE TITLE
Request: allow to drop the engines for the trailer vehicle

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#316]
### Environment
Ver 0.45.4

### Description
Per page 99, TechManual;

> .. Units built as Trailers do not requires an engine, control systems, or crew, unless they are also expected to operate without a suitable Tractor unit or are expected to employ heavy weapons and equipment while operating independently of a unit with an engine.

And page 101 on the same book:

> Tractor/Trailer Vehicle: Combat Vehicles with a Tracked or Wheeled motive type may be built as Trailers. Trailers do not require an engine, control systems, or crew, unless they are also expected to operate without a suitable Tractor unit or are expected to employ heavy weapons and equipment while operating independently of a unit with an engine (in which case, a minimum Engine Rating of 10 applies).

And, by [the answer about trailer engine](https://bg.battletech.com/forums/index.php?topic=24615.0), you may add an engine with Engine Rating of 10 regardless of its tonnage if you want to make a trailer.

But as you know, for now you can't drop the engine on the vehicle, although you may reduce its rating by reduce its Cruise MP.

So, by the rules, if the vehicle's Motive Type is either Tracked or Wheeled, it may drop the engine, or having an engine with Engine Rating of 10 regardless of its actual tonnage. 

I suggest how to implement it by...

-Make 'None' for the Engine section, and available it if the unit is a Combat Vehicle and its Motive Type is either Tracked or Wheeled. If it is checked, it is considered as a trailer without an engine, and its MP would be fixed to 0.
-If the unit is a Combat Vehicle and its Motive Type is either Tracked or Wheeled, allow to reduce the Cruise MP to 0 - if you choose an engine with this, and its Cruise MP is 0, then it is considered as having an engine with Engine Rating of 10.

But is there any better way to implement it?

**Comment by neoancient** [comment]
That's how I've implemented it it for support vehicles in the branch I'm working on. It's one of a couple things I've found that needs to get ported to combat vehicles.
