### ISSUE TITLE
WiGE can be built with less than 5 MP

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#321]
### Environment
Ver 0.45.4

### Description
As title says. Per errata of TechManual,
> WiGEs: These vehicles must be constructed with a minimum of 5 MP.

But for now, in MegaMekLab you can reduce WiGE vehicles' cruising MP less than 5.

**Comment by neoancient** [comment]
Please stop spamming the trackers with brand new errata.

**Comment by binaryspica** [comment]
Sorry if bothering you all. I intend no offense, and I just want to report the possible problems if I have seen it.

**Comment by HammerGS** [comment]
We are very aware of errata, and what is and isn't implemented in the various programs.  Its an issue of having coding time to address the issues.

This covers the explaination very well.
https://github.com/MegaMek/megameklab/issues/282#issuecomment-504812183

**Comment by binaryspica** [comment]
Sorry, I was simply thought that it was not implemented and I didn't know you are aware of it or it. But, if you are fully aware of it, then the report wasn't needed in the first place. 

Anyway, I am always thank you all for maintain such a huge project just for hobby and open it to everyone for free. I didn't intended to bump that.
