### ISSUE TITLE
Cannot place Energy weapons in a LAMs' arms

### ISSUE THREAD

**Issue by VincentDegrassa** [MegaMek/megameklab#322]
### Environment
What version of MekLab does your issue apply to?  45.3
What operating system are you using?  Windows,
What java version are you using? 8 update 211

### Description
Cannot place any type of Energy weapon in the arms for LAMS

### Files

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/3342451/megameklablog.txt)

**Comment by neoancient** [comment]
Duplicate of #260 
This was fixed in 0.45.4.
