### ISSUE TITLE
Improved Heavy Gauss can be split between Arms and Torsos

### ISSUE THREAD

**Issue by WEKarnesky** [MegaMek/megameklab#324]
### Environment
Using the Standalone Megamek Lab 0.45.4 distributed with MekHQ Version 0.45.4

### Description
Because the iHGR can only be mounted in the torso, it can not be split between the torsos and arms but 0.45.4 allows this.

### Files
Attached is a screenshot and a zip with the mtf.

![Screenshot](https://user-images.githubusercontent.com/8506084/60772120-83eeee80-a0a6-11e9-9ffd-35c43cfd32a0.PNG)

[Catapult CPLT-IGR.zip](https://github.com/MegaMek/megameklab/files/3365956/Catapult.CPLT-IGR.zip)

**Comment by HammerGS** [comment]
They actually can split the crits.

From Tactical Operations 3rd Edition pg 314

> The Improved Heavy Gauss Rifle uses the same rules **to mount,** move with and fire as the standard Heavy Gauss Rifle

From Techmanual 5th Printing pg 219

> Heavy Gauss rifles may only be mounted by units powered by fusion or fission engines (including BattleMechs, IndustrialMechs, aerospace units, Combat Vehicles and Support Vehicles). On BattleMechs or IndustrialMechs, **Heavy Gauss rifles may only be mounted in Torso locations, and their critical slots may be divided (but only among two adjacent Torso locations, side-to-center).**

**Comment by WEKarnesky** [comment]
Ah, so you can split to the CT, but not to the arms?  

Thank you for the clarification there, though this is still a bug in that case, so thank you as well for sorting the ticket to the appropriate milestone.

**Comment by neoancient** [comment]
Fixed by #327
