### ISSUE TITLE
Jumpship max Docking Hardpoints does not update unless the user gives focus to the year field

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megameklab#329]
### Environment
45.4
Windows
Java version 1.8.0_201

### Description
When changing the max tonnage of a Jumpship, the max Docking Hardpoints number (on the transport bays tab) does not increase until the user gives focus to the "Year:" field (on the Structure/Armor tab).

This seems to affect all 4 vessel types.

Repro:
1) Create a new blank Jumpship
2) Change the tonnage to 500,000
3) Check the max docking hardpoints field on the transport bays tab
4) Switch back to the structure/armor tab
4) Give focus to the year field
5) Check the max docking hardpoints field on the transport bays tab

**Comment by Morkath** [comment]
Potentially related to #330 as both have to do with updating data and the Year field.

**Comment by neoancient** [comment]
There was no previous ticket opened for this issue, but it was fixed in PR #323
