### ISSUE TITLE
Jumpship/Warship/Station total crew is inconsistent on updating

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megameklab#330]
### Environment
45.4
Windows
Java version 1.8.0_201

### Description
The Total Crew: count on the Warship vessel type seems to be inconsistent on updating.

When switching between vessel types it will not update the total crew: count, until giving focus to the Source/Era: field or Year: field.  Which one updates it seems to depend on what the vessel type was set to before changing it.

Repo:
1) Create a blank Jumpship
2) Switch the Vessel type
3) Check the Total Crew: field

When lowering the tonnage, the total crew does not seem to decrease. (IE go from 100k to 500k back to 100k)

Repo:
1) Create a blank Jumpship
2) Note the Total Crew: field count
3) Increase the Tonnage (+100k)
4) Note the Total Crew: field count
5) Decrease the Tonnage (-100k)
4) Check the Total Crew: field

**Comment by Morkath** [comment]
Potentially related to #329 as both have to do with updating data and the Year field.

**Comment by neoancient** [comment]
The issue of changing the total crew field to zero was fixed as a byproduct of PR #303.
Decreasing the tonnage does not decrease the crew because it is perfectly acceptable to have additional crew and MML cannot guess what the user intends.
