### ISSUE TITLE
Quad Battlemechs are unable to allocate industrial physical weapons to their side torsos

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megameklab#336]
### Environment
45.4
Windows
Java version 1.8.0_201

### Description
TechManual p248: "**Quad BattleMechs** and IndustrialMechs may mount spot welders in the Side Torso locations only, and are limited to one welder per location."

Backhoe, Chainsaw, Combine, Dual Saw, Heavy-Duty Pile Driver, Mining Drill, Rock Cutter, Spot Welder, Wrecking Ball.

Industrial mechs appear to work as expected.  Quad Industrial mechs also seem to function correctly.  Quad Battlemechs however are not working.

### REPRO:
1) Load a new mech
2) change the motive type to Quad (leave base type as Standard)
3) switch to the equipment tab
4) switch to Physical Weapons
5) add any of the industrial weapons listed above
6) switch to the assign criticals tab
7) and then attempt to add the weapon to either side torso

**Comment by neoancient** [comment]
I wonder if the test there was supposed to be to make sure the physical weapon is industrial equipment, to prevent putting a hatchet or a sword in the side torso. It tests the mech instead, with the result that quad battlemechs can't mount any of it, and industrial quadmechs can place any of the handheld physical weapons, including swords and hatchets.
