### ISSUE TITLE
Cost Calculation / Rules: Repair Facility on Space Stations

### ISSUE THREAD

**Issue by Nobyliti713** [MegaMek/megameklab#337]
### Environment
MekLab 0.46.0 RC2 Standalone
OS: Kubuntu Linux
Java Version: OpenJDK 11.0.4

### Description
When adding pressurized or unpressurized repair facilities to a space station, the cost isn't calculated correctly (if at all). Per **_Strategic Operations_** pg. 159, my space station with 2x pressurized bays (355,000 tons combined capacity) and 1x unpressurized bay (500,000 ton capacity) should have $6.05 Billion C-Bills in Bay Costs at a minimum (even before the weight multiplier). But the application currently calculates my bay costs at 49,000 (and that includes cargo and small craft bays).

### Files
![mml_bays001](https://user-images.githubusercontent.com/5794286/63226800-b77e7600-c219-11e9-8f25-0a0499f217e6.png)
![mml_bays02](https://user-images.githubusercontent.com/5794286/63226802-bb11fd00-c219-11e9-8504-a74123103da7.png)

**Comment by HammerGS** [comment]
Please attach the blk file for the unit.

**Comment by Nobyliti713** [comment]
Here ya go. Two slightly different designs, one was imported from MekHQ's MegaMekLab 0.45.4, the other was designed from scratch in 0.46.0-rc2.

### Files
[SS - built in 0.46.0-rc2.blk.txt](https://github.com/MegaMek/megameklab/files/3513929/SS.-.built.in.0.46.0-rc2.blk.txt)
[SS - Imported from 0.45.4.blk.txt](https://github.com/MegaMek/megameklab/files/3513930/SS.-.Imported.from.0.45.4.blk.txt)

**Comment by neoancient** [comment]
Only a few of the unit transport bays are currently being accounted for, though all the doors are counted. So the 49,000 is the small craft bay (2 x 20,000) and 9 doors at 1,000 each. After adding in all the bay types I'm getting 6,050,049,000 (including doors), which agrees with what I calculated by hand.
