### ISSUE TITLE
Incomplete queued print

### ISSUE THREAD

**Issue by popnfloss** [MegaMek/megameklab#342]
When I try PDF printing a large queue of units with fluff images, either with a manual queue or a .MUL file, the program seems to give up after about 45 pages or so and the PDF is left unfinished. The problem doesn't seem to occur when printing without the images. To check if it was a problem with the Microsoft PDF virtual printer, I tested it with XPS Writer and CutePDF Writer and the problem still occurs. I also notice that the program slows down and uses a very large amount of RAM after attempting to print a large queue and the memory isn't freed until the program is closed.

**Comment by popnfloss** [comment]
I managed to work around the problem by increasing the memory to 4096 in MegaMekLab.l4j.ini. It finishes printing now, but MML still eats up all 4GB of that memory and doesn't give it back until the program is closed.

**Comment by sixlettervariables** [comment]
That's pretty typical of a Java application (really any garbage collected language), in general the working size of the heap does not shrink. What would be interesting would be to see the working vs committed size of the heap (how much RAM is actually being used by Java).

If both the working and committed sizes of the heap are the same, that could indicate memory is not being freed up. This may be an issue with MML, or in some cases it can be an issue with the printer/print driver (I do a lot of .NET development, and we constantly have issues with printer drivers and "leaked" memory).

**Comment by neoancient** [comment]
I jumped the gun on closing this. The file caching is used on merging the pages into a single document, but all the documents are created in memory first.
