### ISSUE TITLE
Virtual Reality Piloting Pod

### ISSUE THREAD

**Issue by WEKarnesky** [MegaMek/megameklab#354]
### Environment
MML 0.47.0 from the MekHQ download

### Description
The Virtual Reality Piloting Pod (VRPP) has some issues from two standpoints.  First, it is only available with unofficial and ignoring year, rather than the limited time of Experimental that IO has it (page 39)

This has some Knock-on effects when it comes to loading files that SSW creates.

Before I begin, here is a simple mech saved in MML: [MML VRP MECH VR-Mek.zip](https://github.com/MegaMek/megameklab/files/3720034/MML.VRP.MECH.VR-Mek.zip)

First, because the VRPP is Rules Level 5 in MML instead of the Rules Level 4 it should be, even when SSW saves it as the proper name that MML uses, `Virtual Reality Piloting Pod`  Example here:  [vr3 mm3.zip](https://github.com/MegaMek/megameklab/files/3720040/vr3.mm3.zip)

But I'd also request that you recognize `VR Piloting Pod` as a valid name, as it makes the slot look better in MML and SSW, and here is a SSW file saved like that: [VR-SSW VRS.zip](https://github.com/MegaMek/megameklab/files/3720048/VR-SSW.VRS.zip)

**Comment by HammerGS** [comment]
I can't speak to the name, but VRRP is available in MML at the proper tech levels, the screen shot is from the .47 release.  
![image](https://user-images.githubusercontent.com/13752452/66708204-0f14fb80-ed0a-11e9-9f94-b55f5f632b77.png)

As piece of equipment its in universe life span is 3052-3055. The example mech you've attached is from 3050. So it have to be built as unofficial to have that equipment available.

![image](https://user-images.githubusercontent.com/13752452/66708283-4fc14480-ed0b-11e9-9d63-72e39ba2461a.png)

**Comment by WEKarnesky** [comment]
Do you not allow mechs built within the R&D start date? Perhaps that's where my confusion for the rules level exists.

![image](https://user-images.githubusercontent.com/8506084/66709547-70919600-ed1b-11e9-927c-2ace8c2dc57f.png)

**Comment by neoancient** [comment]
The R&D start date is when they started working on it, not when they have an actual working prototype. All dates come from the universal technology advancement table:
![Screenshot from 2019-10-12 20-20-21](https://user-images.githubusercontent.com/16927464/66709623-f8809b80-ed2d-11e9-9006-4f8fbfe90510.png)
Dates that are noted as approximate are available five years earlier (or five years later in the case of extinction dates). If using faction-specific dates, the prototype or production date is used for the given faction, but other factions are delayed per the guidelines given before the tech advancement tables. It is also possible to use it after the extinction date if you check "Show extinct equipment."

As for the name, that's part of a separate issue of updating the SSW import code. For most equipment that's a simple matter of adding an additional lookup name. The way cockpits, gryos, and engines are implemented will require a lookup name to translate the key where it differs.
