### ISSUE TITLE
Bug: ICE wants engine heat sinks

### ISSUE THREAD

**Issue by Xeno426** [MegaMek/megameklab#372]
0.47.1
Platform Windows 7 6.1 (x86)
Java version 1.8.0_231-b11

### Description
Internal Combustion Engines should not have any internal heat sinks. However, when building a mech, MML still tries to assign internal heat sinks. Make a 50t mech move at 3/5, and the engine would have 6 internal heat sink if it were a standard fusion, but should have zero if it's ICE. 

Fix: ICE should always set the number of internal heat sinks to 0, regardless of the engine rating.

**Comment by neoancient** [comment]
BattleMechs with non-fusion engines use the same rules as IndustrialMechs, found on TM, p. 71. Weight-free heat sinks and critical-free heat sinks are not the same thing, and the number of critical-free heat sinks does not depend on engine type.
