### ISSUE TITLE
Super Heavy Naval Displacement not working (47.2)

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#381]
Been playing around with this program but whenever I try to make a super-heavy naval combat vehicle ala a Jormungand but I keep getting bad engine warnings (871 and 1473 being the most common).

Another problem is that I can never get the max tonnage to go above 51 tons, no matter how much I fiddled with it. Not making it super heavy makes the engine go to monstrous size and won't go above 132 in max tonnage. This is getting weird because it has been otherwise working decently for me.

**Comment by neoancient** [comment]
Large naval support vehicles are not yet implemented. They should be coming in the next few months.

**Comment by GamerFoxNeumann** [comment]
> The Jormungand is not a combat vehicle. It's a support vehicle. Large naval support vehicles are not yet implemented. They should be coming in the next few months.

Thanks, just give me the heads up when they do become available. :)

**Comment by neoancient** [comment]
Watch for announcements of new versions. It will be in the release notes.
