### ISSUE TITLE
RFE: Improved display of text from Assign Criticals Tab

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#383]
From this forum post.
https://bg.battletech.com/forums/index.php?topic=67812.msg1569133#msg1569133

> Does MML do Dropships/Jumpships/Warships/Space Stations?  yes.
> 
> Does MML do them well?  No.  Adding weapons and ammo to ships in MML is a trial and a half, especially the ammo.  The UI just isn't pleasant to work with, and you have very little feedback on things like 'how much ammo does this bay already have in it?'

I think the major issue is the text boxes are to small when opened to see all the ammo. While the NAC/35 at the top is visible. The Barracudea in the AL isn't.

![image](https://user-images.githubusercontent.com/13752452/71220355-752b7b00-2285-11ea-91a0-d90700d0d9f3.png)

### Environment
What version of MekLab does your issue apply to?  Current to Repo (47.3)
What operating system are you using?  Windows,

Is their anyway to avoid cutting off the text and show that information?

**Comment by SJuliez** [comment]
I think this is largely solved. Closing this issue. I copied the forum link to #37

**Comment by SJuliez** [comment]
![image](https://github.com/MegaMek/megameklab/assets/17069663/4b2c17d8-5a65-4d5e-9957-3cb757da0762)
