### ISSUE TITLE
Unable to choose Naval motive types for Combat Vehicles

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megameklab#39]
While updating unit sources in MML I noticed that the Monitor naval vessel was showing Hover as its motive type inside the lab. The blk file correctly shows that it is a ship. Looking in the code though there is no reference to a Naval motive type. 

Vehicle/tabs/StructureTab.java line 115

**Comment by HammerGS** [comment]
You can't make Naval with MML.  This is a long known issue.
