### ISSUE TITLE
0.46.1 - WiGE Weight Differs Upon Reload Because of Heat Sink Addition

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megameklab#402]
Here's the vehicle when just finished editing - it passes verification with 80/80 tonnes used.
![PelicanWiGEOriginal](https://user-images.githubusercontent.com/39067288/73006031-ee177880-3dd7-11ea-880c-1efc6b746457.png)

When loaded, it gains 10 tonnes of heatsinks, pushing it to 90/80 tonnes used.
![PelicanWiGEReloaded](https://user-images.githubusercontent.com/39067288/73006036-ef48a580-3dd7-11ea-8672-f3f324b10366.png)

The WiGE file in question:
[Pelican_WIGE_Wedgetail_BI.zip](https://github.com/MegaMek/megamek/files/4104383/Pelican_WIGE_Wedgetail_BI.zip)

This was raised on Discord.

**Comment by neoancient** [comment]
The screenshots show a combat vehicle. The provided file is a support vehicle, and was not created by MML (at least not from what is shown in the screenshots). Combat vehicles get 10 free heat sinks from the fusion engine. Support vehicle engines never provide weight-free heat sinks.
