### ISSUE TITLE
Maximum BAR Value For Tech Rating C Support Vehicles is 6 instead of 7

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megameklab#405]
Using a Support Vehicle to create a primitive tank dating before 2300. Armour Tech Rating C should be able to do BAR value of 7 (IO 121), but can only do up to a BAR rating of 6.

**Comment by neoancient** [comment]
See the chart in TM, p. 134. BAR 7 armor at tech rating C requires the armored chassis modification.
