### ISSUE TITLE
Clan BattleArmor using IS armor Weights

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#421]
From Discord. 
Was helping someone making a BA from the Project Zhukov fan TRO. Noticed the armor weights where off compared to the TRO.  Ran the weight check and looks like the BA is using IS armor weights.

![image](https://user-images.githubusercontent.com/13752452/73907092-4a5fab00-4862-11ea-9d64-984067cd4f20.png)

### Environment
What version of MekLab does your issue apply to?  47.4 in Repo
What operating system are you using?  Windows

[DEIMOS BattleArmor.zip](https://github.com/MegaMek/megameklab/files/4163271/DEIMOS.BattleArmor.zip)

**Comment by neoancient** [comment]
When I load the file provided it imports as Clan armor. But I found that if I start a new unit and change from IS to Clan, the armor stays as IS. If I switch to another armor type then back it starts using the Clan weights.
