### ISSUE TITLE
Feature Request: The Ability to Recreate the Argo from Hare Brained Schemes's Battletech

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#432]
This is just a simple feature request and nothing more.

**Comment by HammerGS** [comment]
This is going to be almost impossible to acheive. I know CGL didn't build the Argo using any of the rules in TechManual or Strat Ops. It's basically a custom one off thing. Part DropShip, Part Warship.

**Comment by GamerFoxNeumann** [comment]
> This is going to be almost impossible to acheive. I know CGL didn't build the Argo using any of the rules in TechManual or Strat Ops. It's basically a custom one off thing. Part DropShip, Part Warship.

That would be a problem... but then again, the damn thing is fanfic fuel...

**Comment by neoancient** [comment]
You can still create it without the grav decks and multiple docking collar system. If at some future point the construction rules are revised to allow grav decks and the remaining construction details are provided for the MDCS we'll revisit this. But for now this is in the same category as frankenmechs and the illegal design from XTRO: Boondoggles, which is that it would be nice to be able to support them, but they differ enough from the standard construction rules that they would take too much time away from more mainstream things.
