### ISSUE TITLE
Infantry not retaining specializations or equipment

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#433]
As of late, I've been encountering a problem with 0.47.3 with the infantry, specifically not retaining specializations and sometimes even equipment.

For example, I've been creating Xenoplanetary Condition troops and combat engineers and yet they aren't retaining the Xenoplanetary Condition or engineering specializations. No matter how many times I save them, they never show up. Is this a common problem?

**Comment by HammerGS** [comment]
Just tested this and looks like nothing is written to the BLK file (assuming it should)

**Comment by GamerFoxNeumann** [comment]
> Just tested this and looks like nothing is written to the BLK file (assuming it should)

Yeah, and my .txt files are showing up blank as well...

I mean how can I set up various mechanized and motorized Xenoplantary Condition specialized infantry ranging from support teams to actual line infantry squads if I can't keep the specialization!

**Comment by Windchild292** [comment]
I'll fix this

**Comment by GamerFoxNeumann** [comment]
> I'll fix this now

Thanks for the quick action. :)

**Comment by Windchild292** [comment]
Issues were on MegaMek side of things, so this is fixed in MegaMek PR 1658

**Comment by neoancient** [comment]
Fixed by Megamek/megamek#1658
