### ISSUE TITLE
Infantry exports not going to TXT, only HTML

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#435]
I've been encountering this possible problem for a while now, and only now has it become... annoying.

The basic gist is that whenever I try to export an infantry to text, the text file is literally blank. HTML works, just not TXT. Is this a problem or is it just me?

**Comment by Windchild292** [comment]
This is an issue in develop, I'll fix it.

**Comment by GamerFoxNeumann** [comment]
> This is an issue in develop, I'll fix it.

Thanks... it's a bit annoying.

**Comment by Windchild292** [comment]
Fixed, MM PR 1666

**Comment by GamerFoxNeumann** [comment]
> Fixed, MM PR 1666

So... next update?

**Comment by Windchild292** [comment]
That would be correct

**Comment by neoancient** [comment]
Fixed by Megamek/megamek#1666
