### ISSUE TITLE
Disappearing DS Collars on Space Station

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#437]
Sent via PM

Think I found a bug, but cannot find anything in the logs. Using 47.3 MekHQ, MekLab

 _Take Olympus Recharge Station
 Remove cargo bay
 Modify all pressure bay to 1M ton (1 NOS, 1 ALS, 1 ARS)
 Add 3 Recharge Batteries to hull
 Should still have 4 dropship collars showing
 Use remaining cargo
 Dropship collars zero out and cannot be selected_

 _I have duplicated this repeatedly_

Can can duplicate the behaviour in 47.4
### Environment
What version of MekLab does your issue apply to?  Standalone MML
What operating system are you using?  Windows

Log files not available

**Comment by 2ndacr** [comment]
I was able to duplicate it in 47.4 release also.

**Comment by Windchild292** [comment]
I'll pick this one up, and have already discovered a bug beneath this. The bay location reverts to NOS when the weight is changed.

**Comment by 2ndacr** [comment]
I noticed that also, but was easy to correct, the biggie is losing the dropship collars completely

**Comment by 2ndacr** [comment]
Glad I was able to duplicate it and provide detailed instructions to fix it

**Comment by Windchild292** [comment]
The actual error is that the tool tip has not been updated to account for the naval repair facility changes.
They are disappearing because the maximum number of potential DropShip collars is reduced as the pressure bay size is increased.

**Comment by 2ndacr** [comment]
thank you sir

**Comment by Windchild292** [comment]
My pleasure :)
