### ISSUE TITLE
MML not tracking Single heatsink to Double(Freezer) Change

### ISSUE THREAD

**Issue by Lornalt** [MegaMek/megameklab#438]
Changing the Heatsinks on any mek from Single to double(freezer) in MML first allows this to happen with no issues. However upon reloading the mek file the heatsinks switches from Double back to Single.

Edit -- Apparently PDHS (double (freezers)) are meant to be used as a mix with core single heat sinks. They should not be allowed to be used as the core heat sinks of a me. Sarna.net on heatsinks show that PDHS could not be mounted in Engines. 

### Environment
Using version 0.46.1 stable as well as 0.47.4 Dev. Both as standalone or as part of Mekhq
Windows 10 and 7 (used a desktop for 10 and a laptop for 7)
Java version 1.8.0_241

### Description
![MML shows no error upon switching from Single to Double](https://user-images.githubusercontent.com/60933894/74254869-0706b000-4d2c-11ea-8541-d312473a6c5b.jpg)
![Summary page shows correct heatsink values](https://user-images.githubusercontent.com/60933894/74254903-1259db80-4d2c-11ea-8342-307f70db6ad8.jpg)
![Refit page shows wrong heatsink values now](https://user-images.githubusercontent.com/60933894/74254914-17b72600-4d2c-11ea-824b-2483eb3a0aff.jpg)

### Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/4186654/megameklablog.txt)

**Comment by Lornalt** [comment]
Amended Issue based on additional sources from Sarna.net information. Prototype Double Heat Sinks or Double(Freezers) cannot be used as Engine Heat Sinks.

**Comment by neoancient** [comment]
It's more complicated than that. You can replace any of the heat sinks with prototype doubles, including the 10 weight-free heat sinks that MML assumes, but all the doubles have to be assigned to critical slots regardless of the number of critical-free slots provided by the engine.
