### ISSUE TITLE
Combat Vehicle Chassis Mod [Flotation Hull] can be added to non hovercraft, VTOLs, WiGEs, and conventional fighters

### ISSUE THREAD

**Issue by BRDiger** [MegaMek/megameklab#440]
HQ's MekLab 0.47.4
Windows

As per Tactical Operations, p. 302, "Floating Hull" the Chassis Mod can only be added to HOVERCRAFT, VTOLS, WIGES and CONVENTIONAL FIGHTERS.
Mek Lab let´s me add it to Tracked and Wheeled Vehicles (it´s even podable) and validates it.

Additionally the Megameklog complains 

>  : "WARN [mekhq.campaign.parts.equipment.EquipmentPart] {AWT-EventQueue-0} 
I don't know how much Combat Vehicle Chassis Mod [Flotation Hull] costs."

While Sarna states the the price is doubled, the table on page 407 Tactical Operations gives the costs as 1.25xTC

**Comment by neoancient** [comment]
Note that per errata, WiGE vehicles have a flotation hull as part of their basic construction and will not see the chassis mod as available equipment.
https://bg.battletech.com/forums/index.php?topic=46241.msg1065439#msg1065439
