### ISSUE TITLE
Aerospace Fighter's Preview says that reduced Heat Sink is damaged.

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#444]
### Environment
Ver 0.47.4

### Description
It is an old bug so perhaps you are already aware of this, but...

If you load any random canon Aerospace Fighter, and drop some heat sinks, if you check the Preview section it is counted as damaged. Fore example, If a fighter have 24 double heat sinks, in the Heat Sinks section it says,

> **Heat SInks**: 24 [48]

But if you drop four of them and checks it again, it says,

> **Heat SInks**: 20 [40] _4 damaged)_

The italic text is red.

**Comment by neoancient** [comment]
These are unrelated and should be separate issues.

**Comment by binaryspica** [comment]
Is it better to make a new issue and split these then?

**Comment by HammerGS** [comment]
Yes. They should be separate issues

**Comment by binaryspica** [comment]
Got it. I will split it. This issue will got the first and #461 gets the second.
