### ISSUE TITLE
Unit stacking violation.

### ISSUE THREAD

**Issue by monbvol** [MegaMek/megameklab#45]
Shouldn't be able to put a Dervish and a Quickdraw in the same hex as the bot did.

![stackingbug](https://cloud.githubusercontent.com/assets/17420975/21298051/b4fdf2e0-c53f-11e6-8a3f-c2059f3598ce.png)

[stackingbug.sav.gz](https://github.com/MegaMek/megameklab/files/659798/stackingbug.sav.gz)

[gamelog.zip](https://github.com/MegaMek/megameklab/files/659799/gamelog.zip)

**Comment by HammerGS** [comment]
Sorry you've got this on the MegaMekLab tracker. We can't move things between the various trackers can you reopen this on the MegaMek tracker.

https://github.com/MegaMek/megamek/issues
