### ISSUE TITLE
Can't add ammo for light and medium weapons to support vehicles

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#454]
Using MML 0.47.4 on OS X, I can't add seem to add additional ammunition for light or medium weapons to a support vehicle. Maybe I've missed it?

**Comment by neoancient** [comment]
It's not implemented. The way we track ammo is not well suited for adding dozens of distinct infantry weapon ammo types and I haven't figured out the right way to work it into the system yet.
