### ISSUE TITLE
Spot welders aren't treated as energy weapons

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#455]
Using MML 0.47.4 on OS X, spot welders do not generate heat or require power amplifiers. I've tested this on IndustrialMechs, support vehicles, and combat vehicles. They should generate two points of heat and require 0.2 tons of power amplifiers.

**Comment by neoancient** [comment]
TM, p. 248 says they are only treated as heavy energy weapons on units without a fusion or fission engine.

**Comment by AlphaSled** [comment]
Humbly requesting another examination of this issue.
Testing on the JAW-65A Jabberwocky, as of 48.0, shows that Spot Welders aren't requiring Power Amplifiers on Fuel Cell or ICE engine'd 'Mechs.
