### ISSUE TITLE
Save menu command does nothing when unit is invalid

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#456]
Using MML 0.47.4 on OS X, when I try to save a unit that MML thinks is invalid (it's sometimes wrong about that), nothing happens. With 0.43.9-RC3 and earlier versions, I would at least get a warning that I was saving an invalid unit. I have to use Save As to save anything MML thinks might be invalid.

Also, under MML 0.47.2, I would sometimes change the Model field of a unit, make a few other changes, and save it only to find that MML had decided to save it with the old Model name, overwriting the previous unit. This didn't happen every time. I'm not sure what triggered it. It would sometimes happen even after I'd made a bunch of other changes to the unit. Save As always worked properly. I haven't seen this pop up on 0.47.4 yet, but I've gotten used to Save As and have rarely used plain old Save since switching to 0.47.4.

**Comment by neoancient** [comment]
Are you saying that Save As will always save it, but Save does nothing when the unit is flagged as invalid?

**Comment by assaultdoor** [comment]
That's it.
