### ISSUE TITLE
Cost for combat vehicle internal structure is based on unrounded values

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#459]
Using MML 0.47.4 on OS X, the cost for internal structure of a 6-ton tracked combat vehicle is 6,000 c-bills. Structure is 10,000 per ton, and masses should be rounded to the nearest ton since MML doesn't do fractional accounting, so the cost should be 10,000 c-bills.

The most obvious solution is, of course, to add fractional accounting.

**Comment by neoancient** [comment]
Combat vehicle structure is rounded to the half ton. Fractional accounting is an optional rule, so it is not a solution.
