### ISSUE TITLE
New Omni mechs and Engine Free Heat Sinks

### ISSUE THREAD

**Issue by tomether** [MegaMek/megameklab#46]
When I create a new Omni mech, the number of free engine heat sinks do not match what I think they should be.  For instance, if I create a normal 75 Ton mech with 4/6/0 speed, it shows that there are 12 free engine heat sinks.  As soon as I click the omni check box, the number of engine free heat sinks drops to 10. It does not appear to matter if it is a clan or IS omni mech.

**Comment by tomether** [comment]
I am running MegaMekLab.exe that was packaged in themekhq-0.42.0-windows package.

**Comment by tomether** [comment]
Sorry user error - should not have been closed.

**Comment by HammerGS** [comment]
This behavior is intended.  Pg 54 of TM describes what happens with Omnis

```
A Clan or Inner Sphere OmniMech may add more heat sinks at this stage, or—at the designer’s option—
may stick with the 10 free sinks already provided by the fusion engine. As heat sinks may be mounted in Omni-pods just like other weapons and equipment, any additional sinks can easily be left to alternate configurations.
 
However, said configurations must always use the same heat sink type as that used by the base chassis. In addition, all heat sinks added onto later configurations must be mounted as pods and thus occupy critical space on the OmniMech’s record sheet (even if the Engine Rating would otherwise allow some of them to
be “critical-free”). It is therefore generally more efficient (and well advised) for OmniMechs to incorporate their maximum complement of “critical-free” heat sinks into their base designs.
```

So In MML when you select Omni it resets the HS to the base 10, but the Base (Omni) spinner becomes available allowing you set the Maximum of 12 Chassis Based Heat Sinks.

**Comment by tomether** [comment]
Thanks for the info.  I do not have a copy of the TechManual so I
appreciate you explaining this to me.  The older manuals that I have do not
have this explanation.  I have not picked up any new manuals in about 20
years.
