### ISSUE TITLE
Issues with pintle mounts

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#463]
Using MML 0.47.4 under OS X:

1)  Pintle mounts cannot mount items such as sprayers or handheld searchlights. Per TM p. 234, pintle mounts can hold weapons _and equipment_, but not heavy weapons.

2) HB:HD includes two vehicles, the Apocalypse World Rover and the Pintel Heavy Combat ATV, which include pintle mounts with a fixed mass. That currently isn't an option in MLL. Pintle mounts are, like regular combat vehicle turrets, entirely dependent on the mass of weapons and equipment they hold.

**Comment by neoancient** [comment]
Empty pintle mounts can be assigned a weight for vehicles with the omni chassis mod. For others they serve no purpose. The support vehicle examples in the house handbooks series are especially bad about violating construction rules, and I wouldn't take any example from a house handbook to be normative.
