### ISSUE TITLE
BA LB-X crit space bug

### ISSUE THREAD

**Issue by svetpavel** [MegaMek/megameklab#47]
BA LB-X has 0 crit space instead of 2, though the weight is correct and it still can be assigned to a location (in which it does not take any crit space).

**Comment by HammerGS** [comment]
Thanks, I'll have a look at it.

**Comment by HammerGS** [comment]
Fixed in MM commit https://github.com/MegaMek/megamek/commit/2710c5479257880d93443526c8d333eb39c66b2c
