### ISSUE TITLE
Adding/removing Environmental Sealing to/from critical slots on combat vehicles

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#474]
Using MML 0.47.4 on OS X, I've identified two issues with adding or removing environmental sealing for combat vehicles. In the Assign Criticals tab, I can't drag Environmental Sealing to any of the critical slots. I get the "no" sign by my cursor. I can right-click it in the list of unassigned equipment and add it to a critical slot, though. However, once it is assigned to a location, I can't right-click on it and remove it from that location. My only option is to delete it.

Also, there are two different equipment items for environmental sealing: Combat Vehicle Chassis Mod [Environmental Sealing] and just plain Environmental Sealing. The former weighs 0 tons, but fits with the naming conventions for amphibious and flotation hull chassis mods. The latter doesn't fit the pattern, but seems to be what I want. I haven't tested either in a MegaMek game.

**Comment by neoancient** [comment]
The just plain environmental sealing is for industrial mechs and has gotten confused with the combat vehicle version in the equipment entries.
