### ISSUE TITLE
Engine Criticals not set correctly in Super Heavy Mixed tech units

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#49]
Brought up on Facebook.  Steps to recreate.
1) Open MML
2) Set Tech to Mixed IS
3) Set Tech Level to Experimental/Unofficial
4) Set the mech weight to anything over 100
5) Flip to the Assign Crit tab and notice the engine critical aren't refreshed correctly.

![image](https://cloud.githubusercontent.com/assets/13752452/22838010/5269fb40-ef80-11e6-89ab-0020fa512068.png)

and

![image](https://cloud.githubusercontent.com/assets/13752452/22838025/62a3ab14-ef80-11e6-811f-90cb3fadfda1.png)

If you select Compact engine then back to Standard things refresh correctly.

**Comment by neoancient** [comment]
MML did not have any considerations for mixed tech superheavies, so besides failing to set the superheavy flag, it was allowing non-fusion engines. I fixed this for BattleMechs and IndustrialMechs.
