### ISSUE TITLE
Problem with infantry unit weight breakdown in the Reports menu

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#494]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, there are several problems with items in the Unit Validation menu.

For aero units, Unit Validation > Unit Cost Breakdown gives the BV calculations, but the window is sized for a cost breakdown.

For BA, Unit Validation > BV Calculations and > Unit Cost Breakdown both give empty windows.

For infantry, Unit Validation > Unit Cost Breakdown gives the BV calculations, again in a window that is sized for cost breakdowns. Unit Validation > Weight Unit Weight Breakdown has no result, but generates an exception in the logs (pasted below).

For ProtoMechs, Unit Validation > Cost Breakdown gives the BV calculations, again in a window that is sized for cost breakdowns.

Here is the exception generated by an infantry weight breakdown:
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> 	at megameklab.com.util.UnitUtil.showUnitWeightBreakDown(UnitUtil.java:3981)
> 	at megameklab.com.util.MenuBarCreator.jMenuUnitWeightBreakdown_actionPerformed(MenuBarCreator.java:755)
> 	at megameklab.com.util.MenuBarCreator.lambda$loadUnitWeightBreakdownMenuOptions$12(MenuBarCreator.java:180)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
> 	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
> 	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
> 	at java.awt.MenuItem.processEvent(MenuItem.java:628)
> 	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:357)
> 	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:345)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:763)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.awt.EventQueue$3.run(EventQueue.java:703)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:733)
> 	at java.awt.EventQueue$4.run(EventQueue.java:731)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

**Comment by SJuliez** [comment]
All of the above are solved, except calling the unit weight breakdown on a conv infantry gives an NPE.
