### ISSUE TITLE
SRCS on Mechs can't be assigned a location, and thus isn't saved

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#496]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I can find SRCS (regular and improved) on the list of equipment in the Equipment tab, and I can add it to my list of equipment. However, when I switch to the Assign Criticals tab, the SRCS doesn't show up. That means it can't be assigned a location, and since unassigned equipment doesn't get saved to disk, the SRCS disappears for good.

I'm not sure why the SRCS is added through the equipment list, since it doesn't occupy any critical slots.

**Comment by binaryspica** [comment]
It can't be saved so it is surely a bug.

Besides, Smart Robotic Control System requires no slot and it can't be assigned a location.
