### ISSUE TITLE
Super heavies shouldn't be allowed to use certain equipment.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#50]
From a Facebook Conversation on Super Heavy Construction.  Currently MML allows Super Heavy mechs to be built with the following systems:

Updated list broken down by Tab:
[Structure/Armor Tab] Only IS allowed
***Chassis Section***
-Structure drop down-
Clan Standard
Clan Endo Steel
Clan Endo Composite
Clan Industrial

-Engine Type drop down- Following not allowed
~~Fission~~ see comments
~~Fuel Cell~~ see comments
~~Clan Fuel Cell~~ see comments

-Enhancements drop down- Following not allowed
MASC
TSM

***Movement Section*** Following not allowed
No Jump Jets or Jump Boosters of any type.
No Underwater Movement Units

[Equipment Tab] Following not allowed
***Other Equipment***
AES
Modular Armor
Partial Wing
Supercharger
Super-Cooled Myomer

[Assign Criticals Tab] Following not allowed
Armored Components

Per IO pg 162 these systems are not allowed.

**Comment by ravionhawk** [comment]
To clarify the Chassis.

Super Heavies can be made using Mixed Tech, but the Clans do not have Super Heavy structures of any sort.

Per IO pg 48 on the Universal Technology Advancement Table, there are only 5 Super Heavy Structure Types.
![image](https://cloud.githubusercontent.com/assets/25833002/23047819/31c6be96-f480-11e6-9c37-cf230a11a1c2.png)

**Comment by neoancient** [comment]
I took care of the invalid engines in the process of fixing #49 .

**Comment by ravionhawk** [comment]
I see.

I made the list for Hammer just before I grabbed the latest release. Thank you.

**Comment by pheonixstorm** [comment]
So under other equipment MASC is allowed?

**Comment by ravionhawk** [comment]
MASC and TSM are on the "Enhancements" drop down menu on the "Structure/Armor" tab.
They are prohibited on Super Heavies.

**Comment by neoancient** [comment]
I did not see any reference to super-cooled myomer in the superheavy rules or superheavies in the scm rules.

**Comment by ravionhawk** [comment]
Let me check on that.

I added it to the list based on the fact that TSM and MASC (both myomer enhancements) are prohibited.

**Comment by ravionhawk** [comment]
We may need a ruling from CGL. The way the rules for SH in IO on pg. 162 reads, you can not use ANY type of myomer except for SH Myomer. Doesn't mention SCM.

But the rules for RISC Super-Cooled Myomer (pg. 94) does say that SCM can only be used on Battlemechs and Omnimechs (non-pod) which is different from Superheavy Battlemechs and Superheavy Omnimechs. 

There might be an errata coming down the pike to cover this.
But we definitely need a ruling from CGL.

![image](https://cloud.githubusercontent.com/assets/25833002/23099981/34bcfc64-f642-11e6-9382-94d04dfdf8ce.png)

**Comment by ravionhawk** [comment]
Matter of fact, with the prohibitions with SCM and how it works, looks like it needs to be put in the same spot as TSM and MASC.
