### ISSUE TITLE
I can do many illegal things with industrial equipment

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#500]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I've found a bunch of errors with which industrial equipment units can equip, and where.

Here are the problems I've noticed with vehicles. I've only tested combat vehicles.

I can mount a bulldozer on the rear of a vehicle. TM p. 242 says I can only mount them on the front. However the Reverse Buffel (TRO 3075) and the UL-14 (TRO:VA(R)) both have rear-mounted bulldozers. I've asked [a rules question about this on the forums](https://bg.battletech.com/forums/index.php?topic=68392.0) to see if this is actually an error.

I can add two bulldozers to the same side of a unit. I should only be able to mount one. (TM p. 242).

I can place as many of these items as I have tonnage for in any vehicle locations I want:
Backhoe
Chainsaw
Combine
Dual Saw
Heavy-Duty Pile Driver
Mining Drill
Rock Cutter
Wrecking Ball
I should only be able to mount one instance of any of these in each of the front, rear, and turret locations (or just front/rear for the pile driver, per TM p. 244). So, for example, if I've got a backhoe in the turret, I shouldn't be able to add another, nor should I be able to add a rock cutter or combine.  (e.g. TM p. 241, but repeated for each of the items listed plus the bulldozer).

The only exception to this is the bulldozer: I can't mix any of these with a bulldozer. So, that's good.

The Heavy-duty Pile Driver should only be allowed on wheeled, tracked, or naval vehicles. I've mounted it on other vehicles, and even managed to put it in a VTOL mast mount. (TM p. 244)

Likewise, the wrecking ball should only be allowed on ground- or naval-based vehicles, but I mast-mounted it in a VTOL. (TM p. 249) I love that image.

I can mount ladder anywhere, not just on the sides or in the turret. (TM p.245)

I can mount multiple bridge layers in one location. It should be only one per location. (TM p. 242)

I can mount more than four lift hoists, and can mount lift hoists in the body of a ground vehicle. (TM p. 245)

While I can't put lift hoist directly in rotor, but I CAN mast mount it. I wouldn't have thought of the mast mount, except that the error message I got when I tried to validate a design with a lift hoist in the rotor said I needed a mast mount. (TM p. 245)

Here are the problems I've noticed with 'Mechs. I've only tested IndustrialMechs.

The equipment list includes a Buzz Saw, supposedly from page 243 of TM. I don't see that.

I can mount bridge layers in arms or legs, or more than one in a location. It should just be torso locations, and just one per location. (TM p. 242, and note that current TM errata says they can go in any torso location)

I should only be able to mount one chainsaw, backhoe, combine, mining drill, rock cutter, salvage arm, or wrecking ball in each arm. So a two-chainsaw arm or an arm wit a chainsaw and a combine should be illegal. But, critical spaces permitting, I can mount duplicates or more than one kind of item on the same arm. (Rules are repeated with each of those items, but see e.g. TM p. 241)

I should only be able to mount salvage arms and spot welders in the arms of humanoid IMs, but I can mount them wherever I want and I can mount more than one per location. (TM p. 248)

I can't drag and drop most items that require arm-mounting without hand actuator onto a torso location, but I can do that for a salvage arm. The design is invalid, but it doesn't work like chainsaws or backhoes or other items like that.

I can mount extended fuel tank and ladder in locations other than the torso. (TM pp. 244-245)

I can mount pile drivers in an arm with lower arm actuator. The error message mentions only hand actuator. I should have to remove both hand and lower arm actuators. (TM p. 244)

I should only be able to mount two lift hoists on an IndustrialMech, but I can mount more. (TM p. 245)

Here are the issues I've noticed with quad IMs.

Quads shouldn't be able to mount wrecking balls at all, but that isn't flagged as illegal. (TM p. 249)

Quads shouldn't be able to mount salvage arms at all. MML allows this, but only in the torso. If I put one in, say, a leg, I get a message during validation saying Quad Mechs can only mount salvage arm in side torso location. (TM p. 248)

Quads should be able to mount mining drills in the side torsos, but can't. (TM p. 246)

**Comment by HammerGS** [comment]
So I have to ask. Are going through the books and testing everything line by line?  If that's the case we also need a list of unimplemented errata, and rules.

**Comment by assaultdoor** [comment]
I was just trying to build a bunch of engineering vehicles, and when I looked up the differences between chainsaws, dual saws, and rock cutters in TM, I realized I was breaking some rules and MML wasn't catching that. So then I went through the section on industrial equipment and tried testing a bunch of stuff.

I'll go back through the list and give page numbers for the rules.

**Comment by neoancient** [comment]
We have some users that ask how they can help with no coding skills. One of the things we suggest is compiling a list of what rules and errata remain to be implemented. Given your obvious attention to detail we wondered if that was something you would be interested in. That's what Hammer's question was about. It wasn't a criticism in how you're making your reports.

**Comment by assaultdoor** [comment]
Yeah, sure. I can actually code, too, but I'm way better at breaking things. Is there a centralized list of this stuff I can add to, rather than filing bug reports? I'm thoroughly unfamiliar with github.
