### ISSUE TITLE
I can remove the base 10 heat sinks that come with an engine

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#501]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, if I have a 'Mech with some of its 10 free heat sinks outside the engine, I can right-click on them in the Assign Criticals tab and delete them. Each one I delete reduces the 'Mech's weight by a ton.

When I go back to the Structure/Armor tab, the field that shows the number of heat sinks shows how many are left, but I can't increase that number by clicking the up arrow. I can type in a number of heat sinks >= 10 and it will update, so all is not lost.

**Comment by neoancient** [comment]
This causes a similar problem with jump jets.
