### ISSUE TITLE
WiGE units should not be able to mount dual turrets

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#505]
Using MML 0.47.4 under OS X with Java build 1.8.0_51-b16, I can put dual turrets on a WiGE. TO p. 347 says dual turrets can't be put on VTOL, WiGE, fixed-wing, airship, or satellite units. VTOLs and fixed-wing units work just fine, and neither satellites nor airships are implemented yet.

**Comment by neoancient** [comment]
This is errata that hasn't been implemented yet.

**Comment by binaryspica** [comment]
https://bg.battletech.com/forums/index.php?topic=46374.msg1069313#msg1069313

I think that I am late, but there was an official answer for this as well.
