### ISSUE TITLE
The nail/rivet gun should actually be two different items

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#506]
I'm using MML 0.47.4 on OS X with Java build 1.8.0_51-b16.

The nail/rivet gun is represented as a single item in MML, but TM p. 246 states that nail guns and rivet guns are technically different, and "[w]hen mounted, the gun must be identified as either a nail or rivet gun."

Not sure when this would become relevant in combat, but I did want a unit with one of each.

**Comment by neoancient** [comment]
They are identical in every way except name. You can note which is which in the notes section.
