### ISSUE TITLE
Sponson turrets should be available to support vehicles, but not to WiGEs

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#514]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I can't seem to add sponson turrets to any support vehicles, despite 2018 TO p. 348 stating that they are "[a]vailable to ground-based, naval-based and VTOL Combat and Support Vehicles (but not other units such as Airships, Fixed-Wing units and Satellites)". This also matches the errata that binaryspica pointed to for the WiGE dual turret issue: https://bg.battletech.com/forums/index.php?topic=46374.msg1069313#msg1069313

Similarly, the errata in the link above suggests sponson turrets should not be legal for WiGEs. However, I just built a combat WiGE with sponsons that passed validation.

**Comment by neoancient** [comment]
Sponson turrets are available for both combat and support vehicles. They are experimental. The rules for sponsons and the link above are not at all clear about WiGEs.
