### ISSUE TITLE
Gyro switching and validation

### ISSUE THREAD

**Issue by Giklab** [MegaMek/megameklab#52]
Switching a Standard to XL Gyro with equipment in the CT slot(s) does not produce an error, but simply removes the gyro. The design validates even without the gyro present.

![bug](https://cloud.githubusercontent.com/assets/26093231/23415296/1a193cde-fddf-11e6-8d6e-6765b6b8c098.PNG)

**Comment by neoancient** [comment]
This is a general problem with system equipment, and a similar thing happens when changing the engine or cockpit to something that requires critical slots that already have equipment in them.

**Comment by neoancient** [comment]
I looked back on this one to reference it and I see that it never got updated with the commit that fixed it.
42eb77354
