### ISSUE TITLE
Industrial 'mech Envi Sealing Cost

### ISSUE THREAD

**Issue by rroby1** [MegaMek/megameklab#522]
### Environment
MML 0.47.4

### Description
There is an environmental sealing line in the equipment database with a 0 cost. Not exactly sure if this is for industrial 'mechs (ejection seats are labeled as for industrial 'mechs). Industrial 'mech environmental sealing has a cost of 225 x Unit Tonnage per Techmanual page 278.

I remember seeing a cost for something changed recently, however I can't seem to locate the issue. If this is a duplicate of a closed issue I apologize.

**Comment by neoancient** [comment]
I did something with combat vehicle environmental sealing but I'll have to check whether I did anything involving cost for IndustrialMechs.
