### ISSUE TITLE
Trailer hitches should occupy an item slot on combat vehicles

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#523]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I can add trailer hitches to a unit without using up any item slots. Per TM p. 98, each hitch uses 1 item slot. I don't see any errata that changes this after the Trailer Hitch quirk was removed from the game.

**Comment by HammerGS** [comment]
Their is pending unpublished errata that will combat vehicles hitches for no slot cost.
