### ISSUE TITLE
Armored motive system appears in equipment list for VTOLs and rail

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#531]
Using MML 0.47.4 on OS X with Java build 1.8.0_51-b16, I can pod-mount an armored motive system on a combat vehicle without any trouble. The construction rules themselves don't say you can't pod-mount it, but TO p. 275 says we can't pod-mount armor (except modular armor). The table on TO p. 405 lists the armored motive system as armor.

Also, VTOLs and rail units aren't allowed to use an armored motive system per TO p. 282. However, the armored motive system shows up in the equipment list for combat and support VTOLs, as well as support rail units. The unit is not flagged as invalid until I actually assign the armored motive system a location under Assign Criticals. In contrast, the system correctly doesn't show up at all if I'm trying to build a fixed-wing support unit.

**Comment by neoancient** [comment]
The armored motive system is not listed as armor in TO. It's listed just after the armor because that's where it falls in alphabetical order.

**Comment by assaultdoor** [comment]
Sorry, wrong page. The table on page 404 says the Armored Motive System is armor.
