### ISSUE TITLE
0.47.4: Support Fixed Wing Aircraft with Propeller mod will not validate

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#536]
I was playing with MekTek Lab 0.47.4 when I encountered this odd problem. Whenever I use the 'propeller' chassis modification with a fusion power plant, I can't input a fuel load, leaving me unable to use the design.

Is this a bug or a reoccurring problem?

**Comment by HammerGS** [comment]
TM pg 127 - †Fixed-Wing unit types may only use Electric engines if they have the Prop-Driven chassis modification.

**Comment by neoancient** [comment]
I was sure this was a duplicate that had been fixed in the current master branch, but I couldn't find the issue and I just verified that it's still a bug.

**Comment by neoancient** [comment]
Fixed-Wing Support Vehicles that use the Prop-Driven chassis modification and are powered by Solar, Fission, or Fusion engine types do not require Fuel Points at all. (TM, p. 129)

**Comment by GamerFoxNeumann** [comment]
@neoancient, is there news on the propeller bug hunt?

I'm just politely asking because it's annoying me to hell that I can't do fusion/solar/fission props via MegaMekLab.

**Comment by neoancient** [comment]
I haven't gotten to it yet. I don't have much free time these days.

**Comment by GamerFoxNeumann** [comment]
> I haven't gotten to it yet. I don't have much free time these days.

I'm just asking, here's to hoping you find the bug and crush it beneath your coding boot. [imaginary toast here]
