### ISSUE TITLE
Dropdown menu's text turns invisible .

### ISSUE THREAD

**Issue by agm-114** [MegaMek/megameklab#546]
### Environment
Megamek Version: Standalone v0.47.4 Development Snapshot
OS: Windows 10
Java Version: 1.8.0_151

### Description
Dropdown menu's text turns invisible .
After selecting a drop down, all the available options correctly display however if any further action is taken within that drop down (including closing it by clicking on the top section) all text for that drop down turns invisible 
Selecting any other UI option seems to fix this issue for the drop down that is currently bugged.

This issue only occurs for certain drop down menus, the screen shot with the red underlining indicates the menus where I was able to reliably reproduce the issue.
It appears only drop downs affected by tech base have this issue. I have tried swapping tech base and level and this does not affect whether or not this issue occurs.

![image](https://user-images.githubusercontent.com/46271745/77832211-b7791980-710a-11ea-9623-103e46113954.png)
![image](https://user-images.githubusercontent.com/46271745/77832223-d1b2f780-710a-11ea-9505-15de9bb5bbdf.png)
![image](https://user-images.githubusercontent.com/46271745/77832297-6158a600-710b-11ea-8509-2fb88846174d.png)

**Comment by HammerGS** [comment]
You you provide us with detailed steps.

**Comment by agm-114** [comment]
I'm not sure I follow. Is this a request for more detailed replication steps?

**Comment by Windchild292** [comment]
I believe it is, and second that @agm-114.

**Comment by agm-114** [comment]
![Bug](https://user-images.githubusercontent.com/46271745/77833580-ded4e400-7114-11ea-92cc-3b875304d95e.gif)

**Comment by Windchild292** [comment]
I'm just going to add that is a great way to show it @agm-114

**Comment by agm-114** [comment]
Oh I forgot to include it in the gif, but the issue is the same if you click one of the options in the dropdown.

**Comment by neoancient** [comment]
I was not able to reproduce this, probably because it depends on a certain combination of theme and operating system. But after looking over the code and fixing a similar issue that I can reproduce, I am confident that I found the fix for it.
