### ISSUE TITLE
Battle Armor bomb rack ammo not listed

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megameklab#551]
MMlab 47.1

For a bomb rack to work, MM requires it to have ammo. (Which is a work around.  Bomb racks are supposed to be 1 shot weapons)  Micro Bomb ammo (Found on the standard Sylph design) is not listed (even with show unavailable checked) in Megameklab, making it difficult to design custom Battle Armor with this weapon system.

**Comment by neoancient** [comment]
Ammo is not displayed for one-shot weapons.
