### ISSUE TITLE
Can't add Ammo to SV's (Small and other)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#555]
From FB

I found a flaw in the recent MegaMekLab version 0.47.5, there is no ammo listed for any ballistic and missile based weapons.

I can confirm that none of the ammo shows. The drop down menu seems off. Doesn't seem to open correctly.
 
Nothing in the logs.

### Environment
What version of MekLab does your issue apply to?  47.5
What operating system are you using?  Windows

**Comment by GamerFoxNeumann** [comment]
I'm seeing this as well. @neoancient, have you seen this happen with your version?

**Comment by neoancient** [comment]
Yes. I did a bunch of work on equipment filtering and inadvertently filtered out all the ammo. 0.47.5 is not going to be very useful for building SVs.

**Comment by GamerFoxNeumann** [comment]
Ah, thanks for giving us the heads up @neoancient.
