### ISSUE TITLE
Bug Report on Random Occurences 

### ISSUE THREAD

**Issue by TigerShark** [MegaMek/megameklab#56]
NOTE: This is being copied from a BT.com thread on SSW. (http://bg.battletech.com/forums/index.php?topic=32391.msg1309407#new)

I've submitted a bug report on it before. Many versions ago. It's difficult to provide and create screen shots for, or even reproduce. Basically, if you're creating infantry, certain equipment either appears or doesn't appear. If you restart the program and try again, it may be there. It may not.

If you do something like changing eras or tech levels on a 'Mech, there are times when equipment disappears, but the unavailable tonnage is still assigned to that weapon/equipment. i.e.: 70 ton 'Mech. Buy a Guardian ECM (1.5t). Delete the ECM. 1.5t is still missing from the total, but the item has been deleted.

This happens at complete random and usually happens after the unit has had equipment placed or moved multiple times. But it's difficult to reproduce consistently. I'll post another bug report on it.

EDIT: I will try to post specific instances of this in the thread replies when I get home.

**Comment by TigerShark** [comment]
The "infantry equipment" bug is mostly in reference to Support weapons and does often occur when you enter a specific year for the unit's inception. I realize it's supposed to restrict equipment to that year, but even if the number is removed, that equipment doesn't come back (except when it does).

**Comment by neoancient** [comment]
I have noticed some unexpected behaviors where changing one thing affects something else, then you change that and it changes a third thing, etc. I have rewritten the bulk of the code for the various structure tabs in part to normalize interactions between the controls, and I have not seen such behavior in my testing so I am closing this as resolved.
Code merged into master branch in 0f2c19a8.
