### ISSUE TITLE
Use Remaining Tonnage for Cargo button can be disabled when it should be enabled, or vice versa

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#561]
Using MML 0.47.5 on OS X with Java build 1.8.0_51-b16, the Use Remaining Tonnage for Cargo button does not toggle between enabled and disabled unless you click on one of the fields in the table of transport bays.

Steps to reproduce (disabled when it should be enabled):
1) Create a station with a grav deck, escape pod, or some other item that can be removed or made lighter.
2) Click Use Remaining Tonnage for Cargo to use up all remaining mass.
3) Now that the Use Remaining Tonnage button is greyed out, click on the Size of the cargo bay that just got all the mass. You should be able to edit the size of that bay.
3) Remove/reduce the mass of an item that is _not_ a transport bay.
4) Return to the Transport Bays pane. The bay you selected in step 3 should still be selected, and you should be able to click Use Remaining Tonnage for Cargo on it. However, that button is disabled

To see it enabled when it should be disabled, do the opposite. With some weight free, click on a cargo bay. Then add equipment or otherwise use up the mass _without_ using a transport bay. When you return to the Transport Bays pane, the button should be enabled even though all free mass has been used up.

In either case, clicking on any other part of the table should correctly enable/disable the button.

I've tested this for support vehicles, DropShips, and space stations and found bugs for all three. DropShips and space stations exhibit both versions of this bug, while support vehicles only have an issue with the button being enabled when it shouldn't be.

**Comment by neoancient** [comment]
Closing as trivial.
