### ISSUE TITLE
MegaMekLab illegally giving armor types to Mechs

### ISSUE THREAD

**Issue by monbvol** [MegaMek/megameklab#567]
### Environment
47.5
Windows 10 64 bit
Java vendor Oracle Corporation
Java version 1.8.0_221
![ArmorError1](https://user-images.githubusercontent.com/17420975/79021504-8ba95b00-7b30-11ea-815f-1b2d4e09b684.png)
[Removed copyrighted content that exceeds fair use allowance - Neoancient]

### Description
MegaMekLab allows Commercial Armor to Battlemechs when it is not available(screenshot of page 206 Tech Manual to corroborate).

These rulings 
[https://bg.battletech.com/forums/index.php?topic=31145.msg726777#msg726777](url)

also indicate that Commercial Armor remains unavailable via the Patchwork armor rules on page 377 of Tactical Operations.

### Files
Screenshots uploaded

**Comment by HammerGS** [comment]
Their is an updated request for Rulings here
https://bg.battletech.com/forums/index.php?topic=68863.0

**Comment by monbvol** [comment]
Aware of it but considering that there were already two rulings, one as
recent as Dec. 2019 and links provided(if they got malformed please let me
know so I can correct them) that already ruled this as illegal and I'm
aware of no errata since then that changes that it would seem likely that
it is still illegal to mount Commercial Armor on Battlemechs via the
Patchwork Armor rules.

**Comment by Windchild292** [comment]
Fixed in https://github.com/MegaMek/megamek/pull/3485
