### ISSUE TITLE
ATAC & ARTS weight

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#570]
megameklab-windows-0.47.5

### Description
During designing a drone ship I have found out that the true weight of ATAC and ARTS is not being calculated. The ATAC weight is left at 2%, without any additional tonnage for controlling other drones. While the ARTS weight is kept at 0 tons, as placing the ARTS system in the hull does not seem to be doing anything.  

ATAC       [IO, p146] 
"For each SDS drone it is intended to direct (of any size), 150 tons is added to this weight. ATACs may be installed in human-crewed ships, or in a WarShip-sized SDS drone. On human-crewed ships, 1 crewman is required for every 3 drones the ATAC can direct. "
I see a number of possible solutions:
1. Assume that all transported units are drones (SC,ASF,Mech,CV,DS) & if the unit has any Drone Control System then assume that it is not a human-crewed.
2. Letting designers set the number of controlled drones, such a mechanism can also latter be used for other equipment that rely on external units/factors for their final weight. And assume that units with any Drone Control System are not a human-crewed

Advanced Robotic Transport System (ARTS)    [IO, p147]
Please add ARTS variants of current types to the list of possible transport bays.

**Comment by neoancient** [comment]
ATAC and ARTS are separate issues.

**Comment by neoancient** [comment]
ATAC/DTAC implemented by #610
