### ISSUE TITLE
Environmental Sealing chassis mod on support vehicles requires 8 item slots

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#571]
Using MML 0.47.5 on OS X with Java build 1.8.0_51-b16, adding the environmental sealing chassis mod to a support vehicle requires 8 equipment slots. This is a change from 0.47.4, and I don't see any place in TM or TM errata that suggests chassis mods occupy any slots.

**Comment by neoancient** [comment]
Fixed by Megamek/megamek@02b4061
