### ISSUE TITLE
Changing between small, medium, and large support vehicles removes all equipment and chassis mods

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#572]
Using MML 0.47.5 on OS X with Java build 1.8.0_51-b16, if I adjust the mass of a support vehicle so that it changes size between small, medium, and large, chassis mods, engine type, fuel, fuel type, quarters, armor, armor BAR, turrets, transfer bays, and equipment are all reset. The only things that remain are the unit's speed, tech ratings, and all of the Basic Information.

**Comment by neoancient** [comment]
So does changing between ground, VTOL, and fixed wing. Or between biped and wuad mechs. A new unit instance has to be created. Figure out what ypu want to build first.

**Comment by assaultdoor** [comment]
Switching from a regular 'Mech to an ultralight or superheavy works just as a user would expect. It is extremely counterintuitive that vehicles don't work this way, and instead wipe out the design.
