### ISSUE TITLE
SV adding Slots for Armor.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#579]
Working through the failed units from the Entity Verifier. A few of the Zugvogel Omni Support Aircraft fail because they are getting 2 slots of armor assigned. Tech Manual pg 134 has the following:

> Space: Under these rules, no armor type available to SupportVehicles reduces their equipment slot space.

Units Impacted
Zugvogel Omni Support Aircraft D
Zugvogel Omni Support Aircraft F

### Environment
What version of MekLab does your issue apply to?  47.5
What operating system are you using?  Windows

**Comment by neoancient** [comment]
See the footnote on the support vehicle armor table, same page.

**Comment by neoancient** [comment]
That change to the table is still in the latest errata (v4.0, Dec 2019). The text was not updated to reflect the change.
