### ISSUE TITLE
Right-click > Left/Right Torso > Add to Left/Right Torso for targeting computer makes it use only one crit slot

### ISSUE THREAD

**Issue by crazys1** [MegaMek/megameklab#58]
Version: 0.43.1

How to reproduce the issue; 

1. Use the 'Mech unit type.
2. Add a targeting computer. 
3. Add enough weapons so that the targeting computer requires at least two critical slots. 
4. Go to the Assign Criticals tab.
5. Right click on the targeting computer in the Unallocated Equipment pane and choose "right torso > Add to right torso" or "left torso > Add to left torso" (either one). The targeting computer gets added, but it uses only one critical slot.

This issue only occurs with the side torsos.

**Comment by ravionhawk** [comment]
I have confirmed replication of this issue with both I.S. and Clan Targeting computers.

Doesn't matter the size of the Targeting Computer.

![image](https://cloud.githubusercontent.com/assets/25833002/24588220/628d7030-1792-11e7-9fdc-bb0443d916a7.png)
