### ISSUE TITLE
Vehicles may now mount bulldozers in the Front or Rear

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#584]
I know you just fixed this so that vehicles may only mount one bulldozer blade in the Front location, but we just got a ruling on this. "Combat and Support Vehicles may mount a maximum of two bulldozer blades per unit, with a maximum of one per Front or Rear location."

https://bg.battletech.com/forums/index.php?topic=68392.msg1600770#msg1600770

Is this a case where I should have reopened the old issue rather than creating a new one?

**Comment by HammerGS** [comment]
This has already been coded.  The Megamek has access to the errata before it's released.
