### ISSUE TITLE
Double MASC listing in MML 0.47.5

### ISSUE THREAD

**Issue by sartris** [MegaMek/megameklab#585]
MML 0.47.5

apologies if this has been reported already or if it's not really an issue

When changing from IS to Clan tech base in the mech editor, the the myomer enhancement dropdown lists MASC twice. Is this Clan and IS versions listed separately? Suggest labeling them separately akin to fusion engines or removing one as redundant.

**Comment by HammerGS** [comment]
This has been fixed for the next release.
