### ISSUE TITLE
MML 0.47.5: Vehicular Grenade Launchers/Vehicular mine dispensers not available on aerospace craft

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#591]
Vehicular Grenade Launchers and Vehicular Mine Dispensers do not appear in the available equipment list for aerospace fighters, conventional fighters, small craft, or dropships. Per tactical operations page 315 and 325, both systems are permitted on those craft.

**Comment by neoancient** [comment]
I noticed this while reviewing equipment available to fixed wing support vehicles. It was fixed by MegaMek/megamek#1881.
