### ISSUE TITLE
MML 0.47.5 Primitive jumpship maximum armor not calculated correctly

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#592]
Maximum armor points on primitive jumpships is not calculating accurately. The maximum tonnage is accurate, but the maximum number of points you are able to allocate is too low. Specific example, we'll use a fifty thousand ton primitive jumpship with a structural integrity of 90. The program allows ninety tons of armor, which is correct, but only allows 57 of the resulting 82 armor points (including structural integrity and using standard armor) to be allocated. Note that this error is NOT present in version 0.46.1.

**Comment by neoancient** [comment]
Please provide detailed steps to reproduce.

If I start a new primitive jumpship, leave the weight at 50k, set the SI to 90, maximize the armor, and auto-allocate I get 16 F, 15 L/RFS, 13 L/RRS, and 10 A, which is a total of 82 points of armor.

**Comment by LiamsGhost** [comment]
Sorry, I mispoke. 90 tons of standard armor on a fifty thousand ton hull with an SI of ninety should yield 126 armor points (90 tons of armor at 0.8 per ton gets you 72 points. Nine free points of armor per facing from SI adds 54 points to that total, for a total of 126). While the program allows you to add the ninety tons of armor, it only allocates 82 points, with an additional 25 points listed as wasted armor points.

**Comment by neoancient** [comment]
Primitive jumpships multiply all armor by 0.66, with the added armor and the SI armor rounded down separately. This is shown in the example in IO, but left out of the text. See errata for a clearer explanation.
72 x 0.66 = 47.52, rounded down to 47.
54 * 0.66 = 35.64, rounded down to 35.
47 + 35 = 82.

**Comment by LiamsGhost** [comment]
That's primitive armor. I'm talking about standard armor.

**Comment by neoancient** [comment]
The option for standard armor is a vestige of before the implementation of the errata, which makes it clear that the primitive multiplier is a function of the primitive dropship construction itself rather than a difference in armor type.

**Comment by LiamsGhost** [comment]
It makes no such thing clear, as the errata'd example still only applies the modifier for the primitive armor itself, and no such additional modifier:

_"David then multiplies the 19 tons of armor he has opted for by the standard Advanced Aerospace Unit Armor Weights for a 100,000-ton Inner Sphere WarShip using standard armor, and finds that this yields 15 armor points [19 (armor tonnage) x 0.8 (standard armor for a 100,000 vessel) = 15.2, rounded down to 15]. He then adds the free 6 points to 16 for a total of 21. Multiplying this total armor value by the Primitive armor factor of 0.66, he finds he has 13 armor points to allocate [21 (non-Primitive armor points) x .66 (Primitive armor factor) = 13.86, rounding down to 13].
He thus assigns this armor as follows: 3 to the nose, 2 to each fore-side, 2 to each aft-side and 2 to the aft. This leaves a running total of 66,859 tons."_

If there was an inherent modifier simply for being a primitive jumpship, separate from the primitive armor modifier, both modifiers would be applied. To assume an inherent "because its a primitive jumpship" modifier only applies to standard armor would be assuming that the writer found it easier to say "a primitive jumpship may use standard armor, but it is functionally identical to primitive armor in all respects" than to say "a primitive jumpship may only use primitive armor"

Please note that this example is contained in the same errata document and has likewise been corrected from the prior version where maximum armor determined using structure mass/12. 

I have posted a clarifying question on the rules board simply to establish this unambiguously. 

In addition, EVEN IF your reading of the errata is correct, megameklab is still not allocating armor correctly, as ninety tons of standard armor does not just include the 82 points of armor that can be allocated, but an additional twenty five points of wasted armor (as I mentioned in the prior response), which can be removed to save tonnage without affecting the total number of armor points available. Going back to the prior example, maximizing the armor grants  eighty two points, but so does 59.5 tons. 

Considering it possible that this was an artifact of maximizing the armor, I attempted to recreate the design and enter the required tonnage without first clicking maximize armor and decreasing it, only to find out it wouldn't let me do so. Attempting to increase armor tonnage did not allow me to increase it beyond three tons, regardless of available tonnage or structural integrity armor limits. Attempting to directly type the tonnage into the field didn't work either. The only way to increase the armor beyond three tons was to first maximize it, then reduce it to the desired level. 

So even if you're right, it's STILL BROKEN!

**Comment by neoancient** [comment]
These are three different issues:
1. From the text in the errata (emphasis added):
> **All  armor mounted on a Primitive JumpShip**—including the “free” armor provided by the vessel’s structural integrity value—must be multiplied by 0.66, rounding down to the nearest whole number.

I saw your rules question when you posted it and subscribed so I'll be notified if there is any change.

2. The maximize armor button does exactly what it says. If the maximum defined by the rules is 90 tons, it sets it to 90 tons.

3. See #543.

**Comment by LiamsGhost** [comment]
Actually, what the maximize armor button does in this case is leave you with 25 wasted armor points, allowing you to then reduce the armor by 30.5 tons without actually changing the total number of armor points you have allocated. I feel like I've already said this twice.
