### ISSUE TITLE
Wrong damage for Enhanced ER PPC 

### ISSUE THREAD

**Issue by wildfire142** [MegaMek/megameklab#6]
Using version 0.1.51

When trying to use the enhanced ER PPC on an aerospace fighter the table in the equipment tab shows damage as only 10 points should be 12.

Damage shows correctly for Mechs and Vehicles

**Comment by HammerGS** [comment]
Fixed in MM commit.

https://github.com/MegaMek/megamek/commit/7999d50fd366f151dfc01436efb6e8a0895a6948
