### ISSUE TITLE
Clan LRM & SRM ammo issues.

### ISSUE THREAD

**Issue by ravionhawk** [MegaMek/megameklab#60]
Clan LRMs & SRMs, when setting the Tech Level to Clan only, are missing ammo types while having improper ammo types. Some of the ammo types that should be Standard Rules can only be found when setting the rules level to Advanced or higher.

Per Interstellar Operations pp. 61 - 62

Clans have access to:

--LRMs--
Standard
Anti-Radiation
Artemis IV
Artemis V
Flare
Follow-the-Leader
Fragmentation
Heat-Seeking
Incendiary
Narc
Smoke
Swarm
Thunder

--SRMs--
Standard
Anti-Radiation
Artemis IV
Artemis V
Harpoon
Heat-Seeking
Inferno
Narc
Smoke
Tear Gas

First Screen Shot
Year = 3145
Tech Level = Clan
Rules Level = Standard
![image](https://cloud.githubusercontent.com/assets/25833002/24866616/a430736a-1dd8-11e7-95ae-f40a614da591.png)

Second Screen Shot
Year = 3145
Tech Level = Clan
Rules Level = Advanced
![image](https://cloud.githubusercontent.com/assets/25833002/24866684/e592d212-1dd8-11e7-8aba-5c6cfd1a13a1.png)

Third Screen Shot
Year = 3145
Tech Level = Clan
Rules Level = Experimental
![image](https://cloud.githubusercontent.com/assets/25833002/24866732/1151a2e8-1dd9-11e7-8009-7391b061a41e.png)

IO Screen Shots
![image](https://cloud.githubusercontent.com/assets/25833002/24866835/60ab292c-1dd9-11e7-9f72-a661f3a0579a.png)
![image](https://cloud.githubusercontent.com/assets/25833002/24866854/72ac31a2-1dd9-11e7-914b-f92402db49ea.png)
![image](https://cloud.githubusercontent.com/assets/25833002/24866892/8ba2c392-1dd9-11e7-8e09-d3d355a384c5.png)

**Comment by HammerGS** [comment]
We are very aware of the issues around ammo. These will be addressed when IO is implemented. That branch is open and in development.
