### ISSUE TITLE
Warship heatsinks not showing in preview TRO

### ISSUE THREAD

**Issue by casperionx** [MegaMek/megameklab#604]
### Environment
Standalone megamek lab
ubuntu 19.10
1.8.0_181

### Description
When I preview the warships I build in the preview/TRO tab it doesn't show the correct amount of heatsinks. Please see attachments
Summary is fine and shows the correct heatsinks for the vessel.

Export is also affected.

![summary_warship](https://user-images.githubusercontent.com/615576/80303676-017e1980-87f5-11ea-9504-4872da895490.png)

No errors in the log.

![warship_heatsink_issue](https://user-images.githubusercontent.com/615576/80303659-e01d2d80-87f4-11ea-89f0-14f324ba36c7.png)

**Comment by neoancient** [comment]
Despite the MML version number and the unit file not being provided, I am confident that this was already fixed by #468
