### ISSUE TITLE
Coolant pods do not add weight until they are assigned critical slots

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#61]
Per this forum post.

http://bg.battletech.com/forums/index.php?topic=57134.0

I can confirm the tonnage doesn't change for coolant pods on the bottom of the equipment tab when the equipment is added.

Nothing in the logs.

**Comment by arlith** [comment]
Weight is computed in `Mek.StatusBar` by using `TestEntity.calculateWeight`, which will ignore unallocated ammo, as that represents one-shot weapons.  `UnitUtil.getUnallocatedAmmoTonnage` then adds in unallocated ammo weight, however it needs to track some special exceptions for one-shot ammo, like cruise missiles and coolant pods.  Coolant pods were missing.
