### ISSUE TITLE
Problems with ammunition display in TRO preview for spacecraft

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#613]
Under MML 0.47.5 on OS X with Java build 1.8.0_51-b16, the TRO previews for small craft, DS, JS, WS, and space stations have two mistakes in the way they display ammunition.

First, the Ammunition: display, between the crew and the notes, pluralizes single-ton ammunition (1 ton_s_).

Second, the Weapons section includes the incorrect number of shots for ammo-using weapons. It appears to be squaring the number of shots per ton. It works fine for the number of capital missiles available, though. Since ammo is recorded in blk files by the number of shots, could it be treating the number of shots as the number of tons?

**Comment by neoancient** [comment]
Duolicate of #593
