### ISSUE TITLE
MML 0.47.6 disappearing VSTOL Equipment

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#621]
VSTOL equipment mounted on conventional fighters does not save when the file is saved, being absent when the file is loaded again in Megameklab.

**Comment by neoancient** [comment]
It worked fine in my tests. We need steps to reproduce.

**Comment by LiamsGhost** [comment]
Huh, I could have sworn it was happening with this version, but I can't recreate it either. Most likely the problem was with a prior version and it got fixed.
