### ISSUE TITLE
Double Heat Sinks are allowing "doubling up" on Super Heavy Mechs

### ISSUE THREAD

**Issue by ravionhawk** [MegaMek/megameklab#63]
The following images show the I.S. DHSs (tripling up).
The Clan DHSs and Laser HSs are "doubling up" and are harder to screen cap.

4 I.S. DHS
![image](https://cloud.githubusercontent.com/assets/25833002/25306354/5e6e7f72-2759-11e7-8fda-02e1ca54f627.png)

First I.S. DHS "doubled up."
![image](https://cloud.githubusercontent.com/assets/25833002/25306358/acb9009e-2759-11e7-875e-6ac326fcfa53.png)

Second I.S. DHS "tripled up."
![image](https://cloud.githubusercontent.com/assets/25833002/25306364/cd04034e-2759-11e7-8564-3646d8529edf.png)

**Comment by HammerGS** [comment]
Tested and confirmed as well.

**Comment by neoancient** [comment]
I noticed that MML was also allowing ammo with different rack sizes (e.g. AC/5, AC/10) to be doubled up so I fixed that also.
