### ISSUE TITLE
Industrial Mechs should be able to use Torso Mounted Cockpits

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#638]
From this forum post:
https://bg.battletech.com/forums/index.php?topic=69631.0

### Environment
What version of MekLab does your issue apply to?  47.6 and Repo

### Description
Per TacOp pg 301

**Comment by binaryspica** [comment]
I am think about to do this, but I have a question. Is it requires a new cockpit(Industrial Torso-Mounted Cockpit) or just allow Torso-Mounted Cockpit to IndustrialMech? 

Nothing says on Torso-Mounted Cockpit that requires Advanced Fire Control, so I think that both penalty of IndustrialMech without Advanced Fire Control and Torso-Mounted Cockpit stacks so it is right that make a new cockpit. But is it correct?
