### ISSUE TITLE
Component Armoring not working in mixed tech units

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/megameklab#64]
It looks like it always happens in Clan based mixed tech, but sometimes in IS as well.

**Comment by HammerGS** [comment]
Version?  Steps to reproduce.

**Comment by pjfarland** [comment]
Versions 43, 43.1, 43.2 all Dev.  
Steps to reproduce:
Start Mech Lab; switch to Experimental Tech; increase weight to 200 tons.  Click on various components to try to add component armoring.  Doesn't even have the option.
And it seems to happen to all Tech types in 43.1 and 43.2.  I'm not going to try to pull up 43.0 again to see if that was operator error in only seeing it happen in mixed tech or not.

**Comment by HammerGS** [comment]
per IO pg 162

> Armored Components: Under these rules, superheavy ’Mechs may not use armored components.
