### ISSUE TITLE
can only print out a single squad of battle armour to a record sheet

### ISSUE THREAD

**Issue by arcaanritual** [MegaMek/megameklab#641]
is the facility available to print a whole platoon of BA to a record sheet? There doesn't appear to be an option or a howto in the documentation.

**Comment by HammerGS** [comment]
You can fit 5 to a sheet.  

Method 1 - In Megamek build a MUL with the BA you want. Save the MUL use the print from MUL option in MML.

Method 2 - Use the File--Print units to file option
![image](https://user-images.githubusercontent.com/13752452/83891630-b536cb00-a70a-11ea-9a23-da3eae4075d3.png)
