### ISSUE TITLE
Unequal BV calculation when adding CASE (II)

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#645]
### Environment
MekLab 0.47.5
Windows 10 Pro N, newest update at the time of writing
Java version 1.8.0_241

### Description
I've picked a Fafnir (FNR-5) in MML with the intent to replace the HGRs with HPPCs with Capacitors (see picture below).
The current BV is 2196, including:
"Explosive Weapons/Equipment Penalty |   | = -6.0."

Placing CASE II on the left changes that value to -5.0, increasing total BV to 2197. 
Placing CASE II on the right changes the value to -1.0, increasing total BV to 2202. 
Adding it on both sides changes the values to 0 and 2203, as you'd expect from the above values. 
The Mech is otherwise symmetrical. The effect is independent of removing the remaining lasers. 

I'd tentatively call this a bug, though I consider it more of an oddity - I'm not sure if there's some arcane rule I've missed that mandates this because somehow, the right side is hit more often.

### Files
![image](https://user-images.githubusercontent.com/19310656/84542104-0c373400-acf9-11ea-9f65-757ca8fededd.png)

**Comment by neoancient** [comment]
There's a bug in the way the capacitors are linked to the PPCs. It's ending up with one linked to the PPC in the other torso and the other not linked at all.
