### ISSUE TITLE
Quarters, infantry bay,  and Life Support cost calculations are wrong on large craft

### ISSUE THREAD

**Issue by JohnLangford** [MegaMek/megameklab#647]
### Environment
What version of MekLab does your issue apply to? 0.47.6
What operating system are you using? Linux (ubuntu)
What java version are you using?  
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### Description
When working on warships, the cost of quarters and infantry bays (including battle armor) should be zero as per Strategic Operations page 160.  However, when I assign quarters the cost goes up by a variable amount depending on the quarter in a manner consistent with the price of quarters being included.  

Also, it appears that life support costs are not being calculated properly.  It should be 5000 per quarter.  (It should include bay personnel as well, but that seems(?) to be taken into account properly.)

**Comment by Maingunnery** [comment]
This is also true for DropShips and Small Craft, see TM p282

**Comment by neoancient** [comment]
I did some spot checking and couldn't find any examples of incorrect life support costs.
