### ISSUE TITLE
Sorting by BV breaks (apparently on "variable")

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#651]
### Environment
MekLab 0.47.5
Windows 10 Pro N, newest update at the time of writing
Java version 1.8.0_241

### Description
Trying to build a BV-Efficient Mek, the sorting function seems to bug out whenever some of the items to be sorted don't have a fixed BV. Setting it to sort by that and clicking on "Physical Weapons", "All Weapons", or "Equipment" results in not getting there, and the tables not showing the correct equipment anymore, akin to past issues sorting BA equipment by weight.

### Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/4782365/megameklablog.txt)
I would assume this is the issue:
"Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double"

**Comment by neoancient** [comment]
This was fixed by #617
