### ISSUE TITLE
Mass Drivers use more slots than shown

### ISSUE THREAD

**Issue by UB-JM** [MegaMek/megameklab#655]
### Environment
MekLab 0.47.5
Windows 10 Pro N, newest update at the time of writing
Java version 1.8.0_241

### Description
I am trying to build a warship with a mass driver (I know, I need help). 
In the current ship (picture attached), the ship's nose has 10 slots used, and everything behaves as expected up until I add a 12th weapon to the arc, at which point it increases the firecontrol weight. 
My most likely explanation is that the Mass Driver counts as 10 slots used, which is consistent with the weight not going up when adding the 21st weapon. However, it does list it as 12/20 instead of 21/40 weapons, so the description and calculation do not match. 
I haven't found any construction rule saying that a Mass Driver counts as 10 weapons, but just assuming it does, it would be nice if that was reflected in the UI somehow. 

### Files
Provide the megameklablog.txt file for any NPE's or errors that MekLab might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklablog.txt file
And provide the unit's file that the issue relates to if this is a unit-specific bug.
(Delete the above lines)
![image](https://user-images.githubusercontent.com/19310656/85161173-acdca500-b25f-11ea-9fb6-fdcf72208532.png)
![image](https://user-images.githubusercontent.com/19310656/85161878-b4e91480-b260-11ea-8fe1-ec35bb4bce58.png)

**Comment by neoancient** [comment]
See the construction rules for mass drivers, TO p. 322.
