### ISSUE TITLE
ARTS Transport Bays

### ISSUE THREAD

**Issue by Maingunnery** [MegaMek/megameklab#658]
megameklab-windows-0.47.7

Description
The weight of ARTS is not being calculated. The ARTS weight is kept at 0 tons, as placing the ARTS system in the hull does not seem to be doing anything. Reference: Advanced Robotic Transport System (ARTS) [IO, p147]

Please add ARTS variants of Transport Bays to the list of possible transport bays.

**Comment by Maingunnery** [comment]
This includes ARTS Pressurized Repair Bays, see Historical LoT1, page 173.

**Comment by neoancient** [comment]
Any unit with ARTS installed as equipment will need to be remade with ARTS bays instead.
