### ISSUE TITLE
MegaMekLab allows stealth Superheavies

### ISSUE THREAD

**Issue by lenny53207** [MegaMek/megameklab#660]
### Environment
What version of MekLab does your issue apply to?  mekhq-windows-0.46.1
What operating system are you using?  Windows
What java version are you using?  Version 8 Update 251

### Description
Describe the issue and provide screenshots ingame if able. MegaMekLab allows stealth systems to be installed and validated on SuperHeavy Mechs
Provide the rulebook, page number, and text if you feel like this is a rules issue. Interstellar Operations page 162
And provide the steps you have taken to reproduce the issue.

**Comment by binaryspica** [comment]
You should read it again. The construction rules never prevent to install stealth systems on the superheavy mechs. It just doesn't functional at all.

**Comment by lenny53207** [comment]
Ah, well that seems silly.

**Comment by binaryspica** [comment]
Yeah it is indeed silly. But that's rules as written. -_-;;

**Comment by HammerGS** [comment]
I would recommend posting a clarification to rules forum. We can always reopen this if needed.
