### ISSUE TITLE
Formatting Issue when printing multiple sheets from MUL

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megameklab#665]
0.47.7

When Printing from MUL, with multiple vehicles or infantry/BattleArmor on one sheet, the formatting is incorrect and the sheets overlay each other or go off the page.  Example here:
https://comstarhomeblog.files.wordpress.com/2020/07/davion-planetary-malitia-marlowes-rift-all-sheets.pdf
https://comstarhomeblog.files.wordpress.com/2020/07/spiders-web-batallion-alpha-star-all-sheets-3.pdf

MUL Files
https://1drv.ms/u/s!Asv8Dn0xvFQPirAv1qYPN_1M0sbt1Q?e=vZp36l
https://1drv.ms/u/s!Asv8Dn0xvFQPirAv1qYPN_1M0sbt1Q?e=3XKrAV

**Comment by HammerGS** [comment]
Please post the MUL files used to help with testing.

**Comment by strategoslevel3** [comment]
Done.  Lined to Onedrive as you can't attach MUL files

**Comment by neoancient** [comment]
I can't reproduce that using export to PDF or print to PDF. Include all steps to reproduce.

**Comment by neoancient** [comment]
Closing due to lack of requested information.

**Comment by neoancient** [comment]
I happened on this issue while testing something else. The issue occurs when the margins are not the default 0.25".
