### ISSUE TITLE
Aft Right weapons arc on spheroid DropShips does not properly display extra fire control tonnage

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#668]
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, if I assign more than 12 weapons to the Aft Right firing arc of a spheroid, the extra tonnage field remains at 0. The extra mass of the firing control and other gear _is_ correctly calculated and factored into the total mass used, but it is not displayed properly in the "Extra tonnage:" field in the Assign Criticals tab. I have not seen this happen with any other firing arc on a large aerospace unit.

Steps to reproduce:
1. Create a 200-ton spheroid DropShip using Inner Sphere technology
2. Add 13 medium lasers but do not assign them a location. Tonnage listed at the bottom of the window should be 42.5/200.0.
3. Assign all 13 medium lasers to the Aft Right firing arc. Slots used correctly reads 13, Weight-free allowed correctly reads 12, but Extra tonnage incorrectly reads 0.0. Meanwhile, Tonnage at the bottom of the window correctly reads 44.0/200.0.

**Comment by neoancient** [comment]
It's actually showing the extra tonnage on the aft left arc, and if you put them in the aft left it shows nothing.
