### ISSUE TITLE
"Delete all" option for bay ammunition on a wing of an aerodyne DS is replaced by "Change facing"

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#678]
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, right-clicking on ammunition in a weapon bay normally gives three options: Remove, Delete, and Delete all. However, if you right-click on ammunition in a weapon bay mounted in an aerodyne DropShip's wing, the Delete all option is replaced by Change facing (which doesn't change the facing of the ammo). Instead, it is found under Delete, at the very bottom. If a unit has many tons of ammunition, Delete all may well be off the screen and entirely inaccessible.

**Comment by neoancient** [comment]
The change facing option changes the facing of the bay the ammo is in. This works as intended.
