### ISSUE TITLE
LRM/SRM bays on large aerospace units do not reflect damage increase from Artemis IV

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#679]
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, the damage displayed for a missile bay on a large aerospace unit does not reflect the increase provided by Artemis IV. For example, a bay with two LRM 20s is listed as doing 24 points of damage, whether or not it contains an advanced FCS. According to the table on TM pp. 341-343, a pair of LRM 20s with Artemis IV should do 32 damage. I've seen the same issue with SRMs.

**Comment by neoancient** [comment]
The damage displayed where?

**Comment by assaultdoor** [comment]
Each bay on an advanced aerospace unit displays the total damage for all weapons in the Assign Criticals tab. For example, "LRM Bay (48/700)".
