### ISSUE TITLE
Equipment from older version of MML failing to load

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#682]
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, when starting MML or loading a unit with certain kinds of equipment that was created by an older version of MML, I get "Failed to load equipment:" errors.

Equipment that fails to load on my custom designs, all of which were created using older versions of MML:
BAExtendedLifeSupport
Fluid Suction System - from an older version of MML, not marked with (Vehicle) or [Standard]) or (Mech)
Liquid Storage (0.5 tons) - but not 1 ton
Extended Fuel Tank (1.5 tons) - but not 1 ton
Rocket Launcher 10 - specifically on a vehicle, but it's okay on Meks.

Equipment that fails to load from units that ship with MML, mostly Solaris or MFUK designs:
CLVehicularGrenadeLauncher
Claw
CLArrowIV FASCAM Ammo
Claw (THB)
Command Console
Mace (THB)
CC Sensors
Dual Cockpit
ISCaselessAC10 Ammo
ISCaselessAC10

**Comment by neoancient** [comment]
Provide unit file(s) per reporting instructions.

**Comment by assaultdoor** [comment]
BAExtendedLifeSupport: [Nelson Marine Boarding Armor Mk I.txt](https://github.com/MegaMek/megameklab/files/4957539/Nelson.Marine.Boarding.Armor.Mk.I.txt)

Fluid Suction System: [RR-5 Recovery Vehicle (Update).txt](https://github.com/MegaMek/megameklab/files/4957516/RR-5.Recovery.Vehicle.Update.txt)

Liquid Storage (0.5 tons): [Tinker T02 SalvageMech.txt](https://github.com/MegaMek/megameklab/files/4957543/Tinker.T02.SalvageMech.txt)

Extended Fuel Tank (1.5 tons): [Bǔshí Zhě (MASH).txt](https://github.com/MegaMek/megameklab/files/4957556/B.shi.Zhe.MASH.txt)

Rocket Launcher 10: [Gatecrasher Assault Breaching OmniTank (A).txt](https://github.com/MegaMek/megameklab/files/4957564/Gatecrasher.Assault.Breaching.OmniTank.A.txt)
