### ISSUE TITLE
Infantry augmentations not working

### ISSUE THREAD

**Issue by lenny53207** [MegaMek/megameklab#689]
### Environment
What version of MekLab does your issue apply to? mekhq-windows-0.46.1
What operating system are you using? Windows
What java version are you using? Version 8 Update 251

### Description
I built an augmented marine platoon with augmentations and armor giving them 3 points of armor that is reflected in the summary, but the TRO shows 2 points of armor, a printed record sheet also show 2 points of armor and does not show the augmentations or marine specialization.  When loaded in megamek they initially load ok, but with the wrong BV, when I configure the squad, the marine specialization is not checked. Checking it increases the BV, but not what the TRO says.  the squad then shows invalid. megamek also reports 2 points of armor and none of the augments.  There is no option to join a C3i net either. 
[Manei Domini Marines.zip](https://github.com/MegaMek/megameklab/files/4956976/Manei.Domini.Marines.zip)
![cyber marines](https://user-images.githubusercontent.com/67663652/88117631-43fb8c00-cb81-11ea-929b-5122b93bf284.jpg)
![cybermarines 1](https://user-images.githubusercontent.com/67663652/88117632-44942280-cb81-11ea-94a2-e4683ce2fdc1.jpg)

**Comment by neoancient** [comment]
The only part of this that has anything to do with MML is the record sheet printing. As of the latest development snapshot the augmentations are printing on the record sheet, but the effects of myomer implants on the damage divisor do not. Everything else reported here depends on implementation of warrior augmentations in MegaMek.
