### ISSUE TITLE
GPL V2 Licence concerns.

### ISSUE THREAD

**Issue by starsiegeplayer** [MegaMek/megameklab#690]
### Environment
N/A

### Description
The software is licensed under GPLv2 but the distribution includes files which are not GPLv2 compatible. 
1) The BtLogo_old.ttf includes a readme file which states "This file is free for non-profit and recreational use, and is not to be used on commercial products without the permission of Fantasy Productions."  Since the distributed program uses the font, commercial use of the program is prohibited which is in conflict with GPL V2.

2)  Record sheets include the copyright notice for Topps.  If the record sheets include material under Topps Copyright, and the Topps Company has not licensed these materials under use of the GPL V2, then is their inclusion in the program also a violation of GPL V2? 

### Files
N/A

**Comment by neoancient** [comment]
1. The license forbids inclusion in commercial products. MML is not a commercial product.
2. The license applies to the program source code. It does not apply to anything generated by the program, nor could it.
