### ISSUE TITLE
Communications Equipment for Combat Veh., Support Veh, CF/ASF

### ISSUE THREAD

**Issue by WolfDroid72** [MegaMek/megameklab#694]
-- version .47.7, use individual app, but downloaded all under the HQ choice.
-- Windows 10
-- Java 8 version 261

### Description
Communication Equipment is currently assigned in 1 crit, 1 ton units: which is normal for 'Mechs.  That restriction is in place on combat vehicles, support vehicles, and Fighters.

TM.pdf: p212 & TM.pdf errata p17 of 40

"Combat and Support Vehicles need to allocate only 1 equipment slot to the entire set, regardless of its tonnage. Aerospace units may treat communications  equipment like cargo, allocating the set to the Body/Fuselage location without occupying weapon slots. For these units, all additional communications equipment adds 1 crewman to the unit’s minimum crew needs for every ton of communications gear."

Combat/Support Veh's should be able to install 1-15 (14 for combat vehs) tons of equipment but use up only one slot, similar to multiple tons of similar ammo get assigned.

Fighters can install gear into fuselage with out using any slots, but must be done individually (repetitive, mostly a non-issue)

**Comment by HammerGS** [comment]
In 47.7 yous should be able to hit the spinner in the size column for variable sized equipment.
![image](https://user-images.githubusercontent.com/13752452/88202053-8c5c8d80-cc05-11ea-8eb4-49947c3dc5e9.png)

**Comment by WolfDroid72** [comment]
THANK YOU! (caps intended)
