### ISSUE TITLE
Pilot name printing on RSs

### ISSUE THREAD

**Issue by vizax** [MegaMek/megameklab#7]
_Note: I noticed this while in MHQ, but since it is a MML issue, i posted here._
I was playing around with MHQ last night testing out how to use the campaign. I printed my record sheets (from MHQ) to PDF and noticed the pilot names were misaligned to the sheet.

I've since looked at `mml.com.ui.mek.printing` and found the xy coords (`PrintMech.java, line 237, for bipedal`), and that prompted me to check the quad and tri mechs.

Results
- Bipedal - misaligned - as noted above  [Sample - bipedal - misaligned](https://github.com/MegaMek/megameklab/files/186122/Hunchback.HBK-4H.pdf)
- Quad - missing pilot print code  [Sample - quad - missing](https://github.com/MegaMek/megameklab/files/186337/Goliath.GOL-1H.pdf)
- Tri - same alignment as bipedal  [_i guess my campaign settings won't let me pull a tri, but see below?_]

If it is ok, I'd like to adjust the xy coords and then add in the same code to have it populate on the quad.

**Comment by arlith** [comment]
You are right, this should be a MML issue.  The mek editor in MHQ is just running MML, so it shouldn't matter if you run it as a stand-alone program or within MHQ.

Looks like you've got the right idea for fixing this, go ahead and create a pull request.

**Comment by vizax** [comment]
I'm here, figured I should check the rest...
Addition:
* Dropship - missing, will add
* Aero - missing, will add
* BattleArmor - not needed? (I don't see a name field, I've never used battle armor stuff)
* Vehicle - Looks good. No change needed.

**Comment by arlith** [comment]
BA consist of multiple suits, so there's no one pilot name.  Technically there could be 4-6 names, depending on faction, but generally I think pilot name isn't added for BA.

**Comment by Dylan-M** [comment]
For BA, do the same things as Vees... put the CO name. @vizax I'd like to see the PR if you're up for it.

**Comment by vizax** [comment]
@Dylan-M, I'll see what I can do, but don't wait for me to do anything. I've gotta  new baby coming in 3 weeks... my life is about to be....   hectic...

**Comment by Dylan-M** [comment]
Been there, enjoy!
