### ISSUE TITLE
Jump Jet/Mechanical Jump Booster availability issues for FC/ICE IndustrialMechs

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#701]
Using MML 0.47.4 on OS X, the "Jump/UMU MP" field and up/down arrows, and "Jump Type" combo box for IndustrialMechs that use ICE or fuel cell engines are sometimes greyed out when they should not be, or are not greyed out when they should be.

An IndustrialMechs using and ICE or fuel cell engine cannot mount jump jets (TM p. 69), and mechanical jump boosters don't appear until ca. 3060 (IO p. 35), so the whole jump section on the Structure/Armor tab should be greyed out for ICE/FC IndustrialMechs until 3060 or so, at which point only the mechanical jump booster should be available. This is not the case.

Steps to recreate the problems:
1) Create a new IndustrialMech 
2) Setting the engine type to ICE or Fuel Cell. Despite the availability of mechanical jump boosters in 3150, the whole jump jet section is greyed out.
3) Change the Tech Level to anything at all, or just click on the Tech Level combo box but leave it the same. Or, change the Tech Base. Either way, the jump jet section once again appears to be available.
4) Change the Jump Type combo box to be mechanical jump boosters. These work fine.
5) Change the Jump Type combo box to be jump jets again. Now the section is greyed out.
6) Set the year to 3050. Note that the Jump/UMU MP options, as well as the JumpType combo box, are not greyed out despite _no_ jump options being legal.
7) You can't type in the Jump MP field or use the up/down arrows, but you can click on the JumpType combo box. Once you pick Jump Jets (the only option), the whole jump jet section is greyed out.

**Comment by neoancient** [comment]
While this is not precisely identical to #44, the underlying issue in both cases is that MM treats mechanical boosters as a type of jump jet. Rather than hacking together an awkward workaround the underlying issue needs to be addressed.
