### ISSUE TITLE
External engine type in Rail Support Vehicle causes load failure

### ISSUE THREAD

**Issue by darodrigues** [MegaMek/megameklab#705]
On both standalone and mekhq, running Linux openjdk 11.0.8 2020-07-14, upon attempting to load a Rail Support Vehicle with an External engine type, a popup appears with the message:

"Warning: Invalid unit, it might load incorrectly!
While parsing file <filename>, unable to match Artemis to launcher for <unitname>"

and fails to load. Similarly, the unit doesn't show up either when loading from cache, even though a build using a fusion engine or any of the other types loads fine.

**Comment by neoancient** [comment]
Attach unit file

**Comment by darodrigues** [comment]
[Urban Tram (External).blk.gz](https://github.com/MegaMek/megameklab/files/5004750/Urban.Tram.External.blk.gz)
Here's an example.
