### ISSUE TITLE
47.7 Bug fuel summary half ton too high on small craft  - Cosmetic

### ISSUE THREAD

**Issue by MarcJC** [MegaMek/megameklab#711]
In 47.7 I loaded the Battle Taxi small craft to make a customized version.  I noticed that while the fuel section had the numbers I wanted, the summary section below was always a half ton higher than the listed weight of fuel.  (Except when fuel was zero, that displayed correctly)  This appears to be a purely cosmetic issue, and as such should be considered low priority, even though I assume the difficulty of the fix will minor.

**Comment by assaultdoor** [comment]
Did you include the weight of the pumps (2% rounded up to the nearest half ton, per TM p. 186)?

**Comment by MarcJC** [comment]
I didn't know about the pump weight.  
Might want to poke Hammer as he told me to open the ticket, I'm sure he will want to know what the cause was also.  

Might want a UI upgrade?  Maybe a hover text to explain the pump weight is there?  Or move the pump weight to one of the other categories.  

Anyways thanks for explaining where the higher number is coming from
