### ISSUE TITLE
Small support vehicle record sheet shows weight in tons

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#726]
The quantity of standard seats on a support vehicle record sheet is listed as a set number of tons instead of the number of seats (see attached sheet. It's two standard seats, not two tons of them)

Also on attached sheet: the total tonnage of the vehicle is listed as 4 tons when the actual design is 4.5 tons

[War Truck.pdf](https://github.com/MegaMek/megameklab/files/5025409/War.Truck.pdf)

**Comment by neoancient** [comment]
Small support vehicles are not finished. See #454
