### ISSUE TITLE
Quadvee cockpit not being applied correctly

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#74]
When designing a quadvee, the quadvee cockpit is showing up as a one-slot standard cockpit when assigning criticals.  Also, it's still only taking up 4 tons and not 3 tons.

**Comment by neoancient** [comment]
I think I fixed this since the last release when dealing with #52 . But since then I rewrote the code for the structure tab and it's fixed now.
0f2c19a8
