### ISSUE TITLE
47.9 oddball characters appearing on infantry record sheet.

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#740]
the characters â€” appears on infantry record sheets in places where there would normally be marked by a dash to indicate there is no value.

**Comment by neoancient** [comment]
Name at least one specific location.

**Comment by LiamsGhost** [comment]
Easier to just show you
[Heavy Field Gun Battery (motorized).pdf](https://github.com/MegaMek/megameklab/files/5048992/Heavy.Field.Gun.Battery.motorized.pdf)
