### ISSUE TITLE
Exposed Weapon Linkage problem with DOM-O1

### ISSUE THREAD

**Issue by assaultdoor** [MegaMek/megameklab#744]
Using MML 0.47.9, the megameklablog.txt file includes this error once it finishes loading:
exposed_linkage RT      6       CLERLargeLaser failed for Dominator DOM-O1 A - Gauss Rifle != CLERLargeLaser
exposed_linkage RT      6       CLERLargeLaser failed for Dominator DOM-O1 B - Double Heat Sink is not a weapon!
exposed_linkage RT      6       CLERLargeLaser failed for Dominator DOM-O1 C - ER PPC != CLERLargeLaser
exposed_linkage RT      6       CLERLargeLaser failed for Dominator DOM-O1 D - Rotary AC/5 != CLERLargeLaser
exposed_linkage RT      6       CLERLargeLaser failed for Dominator DOM-O1 Prime - Double Heat Sink is not a weapon!

**Comment by neoancient** [comment]
Provide relevant files per instructions.

**Comment by assaultdoor** [comment]
The DOM-O1 Dominator file comes with the current version of MegaMekLab.

**Comment by HammerGS** [comment]
These are old MFUK unofficial units. There is a new Dominator coming as part of ilClan Rec guides and the quirks are coded for the new one. When it loads the unofficial units the names are causing issues.
