### ISSUE TITLE
0.47.9 Really early dropships and small craft not allowed

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#765]
Megameklab does not allow for the construction of primitive small craft with an introductory date before 2345, or primitive dropships with an introductory date before 2465. Per interstellar operations, both craft were available as early as 2100. (I assume you're going to say that primitive small craft and dropships aren't fully implemented yet)

**Comment by HammerGS** [comment]
We need a lot more details and references for this bug report. It's basically just the template with a title.
