### ISSUE TITLE
Patchwork armor error 47.X

### ISSUE THREAD

**Issue by WantToBeInWaikiki** [MegaMek/megameklab#768]
Patchwork armor is giving an error (to many armor points allocated) in versions 47.8,9,10 that I found. the error is happening across HQ, LAB, and MM

Git won't let me attach a mechfile so here's a link to my forum post with the attached 46.1 valid test mech that failed in 47.X

 https://bg.battletech.com/forums/megamek-games/patchwork-armor-47-8-10/

**Comment by neoancient** [comment]
[Marauder II MAD-4A TEST.txt](https://github.com/MegaMek/megameklab/files/5265090/Marauder.II.MAD-4A.TEST.txt)
