### ISSUE TITLE
Engine type doesn't change weight on Hover vehicles (47.10)

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megameklab#769]
Hover vehicle types don't change their engine weight regardless if you use Standard, Light, XL, and XXL version of the engines, even as crit slots are updated - The engine itself still weights the same. This applies for both IS and Clan vehicles, for both normal normal hover weights up to 50 and superheavy hovers until 100 tons, and to both IS and Clan version of the engines in all tech ratings and time periods.

This makes Light, XL, and XXL engines worthless on these vehicles as they have BV, Crit, Tech, and C-Bill disadvantage - While providing no advantages as they keep the same working Fusion system and number of heatsinks.

Difference of engine in tracked vehicles do work and can be shown to compare.

Hover:
![2020-09-22 17_18_03-Mortimer C-F blk](https://user-images.githubusercontent.com/38392980/93933949-cd9e1600-fcf8-11ea-861e-0016c4940888.png)
![2020-09-22 17_17_52-Mortimer C-F blk](https://user-images.githubusercontent.com/38392980/93934027-ead2e480-fcf8-11ea-9468-48b4ad978f13.png)

Tracked:
![2020-09-22 17_16_37-Mortimer C-F blk](https://user-images.githubusercontent.com/38392980/93934036-ec041180-fcf8-11ea-8b37-a6f8344aea10.png)
![2020-09-22 17_17_26-Mortimer C-F blk](https://user-images.githubusercontent.com/38392980/93934031-eb6b7b00-fcf8-11ea-8d08-1eee8d0d3add.png)

### Environment
47.10

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue.
(Delete the above lines)

### Files
Provide the megameklablog.txt file for any NPE's or errors that MekLab might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklablog.txt file
And provide the unit's file that the issue relates to if this is a unit-specific bug.
(Delete the above lines)

**Comment by neoancient** [comment]
The engine weight does change for hover vehicles, as long as the weight is above the minimum 20% of the total vehicle weight.  See TM, p. 101.
