### ISSUE TITLE
Index out of bounds error when changing Fenrir BA tech base from IS to Clan

### ISSUE THREAD

**Issue by Question2** [MegaMek/megameklab#77]
Loaded a fenrir BA in MML, tried to change the tech bae from IS to clan, and got a index out of bounds error with MML 43.3.

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1283594/megameklablog.txt)

**Comment by neoancient** [comment]
This has to do with increasing the squad size. The arrays for armor, internal, and crit space were not resized.
Fixed in 9ede598
