### ISSUE TITLE
(HQ 47.10) Primitive Prototype weapons have wrong tech ratings and invalid

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megameklab#771]
Primitive Prototype weapons, when I'm using them in industrialmechs, appear as just "experimental" tech, even if they display as standard - and were prototypes centuries ago.

This is an standard industrialmech of 2995 that doesn't get to use PRIMITIVE tech because it's too advanced, even if it's displayed as standard. This basically happens with all primitive prototype weapons.
![2020-09-22 21_32_29-C__MechModVar_mekhq-0 47 10](https://user-images.githubusercontent.com/38392980/93951369-7e69dc80-fd1c-11ea-93fc-24f209f01120.png)

Presumably this is because the equipment lacks proper introduction dates.

Not only does this change the tech rating of the unit, but instantly invalidates it as though it coudn't exist.

### Environment
HQ meklab 47.10, win 7 64 bits

![2020-09-22 21_32_55-New Mek mtf](https://user-images.githubusercontent.com/38392980/93951351-701bc080-fd1c-11ea-8914-8577f554e38e.png)

**Comment by neoancient** [comment]
All prototype equipment is experimental. See IO, p. 118.

**Comment by NimoStar** [comment]
Then explain why it's listed as standard and common tech. And why it allows you to put it in and then tells you it's invalid.

Even if that, if anything it should change the 'Mech summary to Experimental, instead of saying it's "Invalid", as it happens also in other units.
