### ISSUE TITLE
Superheavy industrialmechs fail validation

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megameklab#773]
TRO: Vehicle Annex for the Diglord is the original source for the mentioning of the "Three-Man Digging Machine" IndustrialMech.  Jihad Hotspots: Terra, does say to the effect that in the Superheavy construction rules that such mechs (not 3 walker, which was excluded) and machines in its tonnage are Superheavy industrial mechs.

Besides those two canon references, and the construction rules, "Three-Man Digging Machine" IndustrialMech was also mentioned in the Colossal writeup in ER:3145.

The Industrialmechs in the program can by default go up to 200 tons; however, saving working industrialmechs over 100 tons is impossible.

Given that such 'mechs already exist, superheavy industrialmechs should be able to mount superheavy gyros, which are the only option for their weight category.

In fact, there is a superheavy industrial cockpit, which would be pointless if such 'mechs were impossible as they are now

![2020-09-23 06_38_07-CutterTitan Piledrive mtf](https://user-images.githubusercontent.com/38392980/93995503-75522d00-fd67-11ea-822e-c1554d25f69b.png)

![2020-09-23 06_38_12-CutterTitan Piledrive mtf](https://user-images.githubusercontent.com/38392980/93995496-73886980-fd67-11ea-89b6-de5a35b974b0.png)

![2020-09-23 06_40_23-CutterTitan Piledrive mtf](https://user-images.githubusercontent.com/38392980/93995698-bba78c00-fd67-11ea-9c0c-80246b8d485b.png)

### Environment
47.10

***

_IN addition, I couldn't find *any* way of adding advanced fire control to industrialmechs. This is a prerequisit to using ECM, Targeting Computer and other stuff, as the program itself reminds, and also Stealth Armor (which requires ECM). As it stands there seems to be no way to solve this._

**Comment by NimoStar** [comment]
In fact, the megamech itself doesn't give such an error when loading the files - They are not invalid for the main game

**Comment by neoancient** [comment]
The standard cockpit is industrial cockpit + advanced fire control.

**Comment by NimoStar** [comment]
I see. Although even using industrial cockpit why not have the option?
BTW Combat Vehicles have both "Basic Targeting" and "Advanced Targeting" it on "other" equipment even though they have it by default... that's what also confused me, while Industrials don't have the equipment at all (other than as part of the cockpit as you describe)
