### ISSUE TITLE
Quad-LAM request (Canon)

### ISSUE THREAD

**Issue by NimoStar** [MegaMek/megameklab#788]
There is no ability to make a Quad-LAM even though such unit exists as an official unit.

See:
[Scorpion LAM](https://www.sarna.net/wiki/Scorpion_LAM)

### Environment
47.10

### Description
Adding "quad" to the LAM motive types would make this work.
Even in "Unofficial" level (the canon unit is mentioned to be a failed experiment, even if it can be brought to battle)

![2020-10-04 10_40_58-New Mek mtf](https://user-images.githubusercontent.com/38392980/95017356-3bb6d700-062f-11eb-9e51-6bdaf1a67198.png)

**Comment by neoancient** [comment]
Like the other units in XTRO: Boondoggles, the Scorpion LAM is a canon example of a failed attempt to build a unit that violates the construction rules.
