### ISSUE TITLE
Record Sheets printing small for Layout. 

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#802]
From Discord from a player.

My local players had sheets at the last game and a bunch were the 66% size (allowing for your extra tables but the tables weren't there.)

![image](https://user-images.githubusercontent.com/13752452/95898602-85e53a00-0d4c-11eb-9512-c519a8b1dd85.png)
Physical size is 6.375" x 8.25"
the very outer edge
+133.33333333333334%
I've seen your bonus tables sheet...
this looks like it's meant for that...

![image](https://user-images.githubusercontent.com/13752452/95898623-91d0fc00-0d4c-11eb-9d15-9b63e1cabdb0.png)

### Environment
What version of MekLab does your issue apply to?  47.11
What operating system are you using?  Windows,

**Comment by neoancient** [comment]
These are scaled at 75% size. The sheets with tables are scaled at 80%, and this scaling happens regardless of whether the tables are there or not.
