### ISSUE TITLE
0.47.13 Primitive dropship engine and control mass by year not applied correctly

### ISSUE THREAD

**Issue by LiamsGhost** [MegaMek/megameklab#823]
For primitive dropships, the change in engine and control mass that is supposed to take place at year 2300 is only applied at year 2351. Similarly the change to those systems that is supposed to be applied in 2351 doesn't kick in until 2400. 

This is best verified by first building the dropship at an earlier year and then changing the year to the later one.

**Comment by neoancient** [comment]
This also affects the fuel factor. It looks like the dates were copied from the small craft table.
