### ISSUE TITLE
Typo in Hit Location Table on Record Sheet

### ISSUE THREAD

**Issue by JstnB** [MegaMek/megameklab#826]
When a record sheet is generated with the reference tables turned on, the Hit Location Table is instead labeled "Hit Location_Table" with the underscore.

**Comment by neoancient** [comment]
For which unit type?

**Comment by sixlettervariables** [comment]
I think this may be it: https://github.com/MegaMek/megameklab/blob/master/resources/megameklab/com/printing/reference/MekHitLocation.properties

**Comment by JstnB** [comment]
For a mech.
