### ISSUE TITLE
 MegaMek Lab - Infantry 2 Secondary Weapons BV not being Calculated Correctly (Possibly others)

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#83]
MegaMek Lab appears to not correctly determine BV of Infantry units with 2 support weapons. This applies to Foot and Jump Infantry. Specifically the 2 support weapons will reduce an infantry unit my 1 move. This will change a foot infantry to move 0 (move or shoot) or jump infantry to 0/2. In the case of foot infantry the resulting speed factor should be 0.44 (I.E. stays the same) while for jump would be at movement 3 would be 0.77 and reduced to 2 for 0.65 with 2 support weapons. (TM 315)

For example the two units attached (mechanized vs Jump) have the M42B primary and the Support Laser ER IS.  The Mechanized should have a speed modifier of 0.77 for move 3 while the Jump Infantry should be 0.65 for move 2.  Both should have a defense factor of 1.1.  They should both be around 98 points with the jump infantry being 12% cheaper on the offensive value (rather than twice as expensive). Please see attached.

[FRR Jump Support Laser IS Infantry.pdf](https://github.com/MegaMek/megameklab/files/1327880/FRR.Jump.Support.Laser.IS.Infantry.pdf)
[FRR Mech Support Laser IS Infantry.pdf](https://github.com/MegaMek/megameklab/files/1327881/FRR.Mech.Support.Laser.IS.Infantry.pdf)

**Comment by FrozenIceman01** [comment]
Note, if Anti-Mech is selected the BV of the Jump Infantry goes down from 160 BV to 152BV

**Comment by HammerGS** [comment]
Looking deeper into this, I think part of the is MML is it's not taking into account the crew of the secondary weapons. See highlighted part of screen shot looks like its saying they have 6 Lasers.  I suspect there's more but I'm still looking into it.
![image](https://user-images.githubusercontent.com/13752452/31100009-296cc52a-a785-11e7-9e27-8ac60bb597e2.png)

**Comment by FrozenIceman01** [comment]
Hello Dave,

That actually looks OK calculation wise.   3x 7 trooper squads would be 21
troops, and if there are 2 support weapons per that should result in 15
rifles and 6 support weapons.  Unless in your version above only one
support weapon was selected and the program calculated for 2.

I am also interested in seeing what happens between Anti Mech selected and
not as it seemed to be adding things funny.

If you are asking about the rest of the crew receiving rifles instead of
loosing them to support as weapon crews: Per page 151 on TM

"Once chosen, Secondary Weapons are assigned to the
platoon with one trooper per weapon. Even if the weapon is
crewed by multiple soldiers, only one is required to aim and
fi re it, while the others are free to use their own Primary Weapons
in combat. Troopers designated as Secondary Weapon
operators may not use their Primary Weapon at the same
time, and so receive the Damage Value for their assigned
Secondary Weapon instead."

Thank you,
Andrew

**Comment by neoancient** [comment]
Attaching the blk files would have been more useful than the record sheets, but I believe between the RSs and the description I've basically built what you were working with. I don't see the problem you're describing. The jump infantry is showing a speed factor of 0.65 and the mechanized shows 0.77, and both have a TMM of 1.1.

![image](https://user-images.githubusercontent.com/16927464/34189180-f0f3bd8a-e4ff-11e7-9427-5b724aa06394.png)

![image](https://user-images.githubusercontent.com/16927464/34189399-ef500aa0-e500-11e7-9cf5-eb170208df11.png)

**Comment by FrozenIceman01** [comment]
Hello Dave,

Ya, like I said in my last response it looks like the calculations are
correct.  However what did not appear correct is when anti-mech is
checked.  It lowered the BV instead of increasing it.  However this finding
was created two releases ago.  I'll see what I can do to verify it on the
new build this weekend.

-Andrew

**Comment by neoancient** [comment]
Closing as no problem found.
