### ISSUE TITLE
Patchwork Armor on VTOL rotor incorrectly flagged as invalid

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#840]
### Environment
ver 0.47.14

### Description
When you pick a VTOL, and check Patchwork option, and pick any armor that adds slots on Rotor, MegaMekLab put that item on Rotor location. And as you know, you cannot put any items other than Mast Mount on Rotor, so it immediately says it is invalid for what it did.

The suggestion is, always put the additional slot generated by Patchwork Armor to Body location will solve the problem. After all, put those items on other than body have no actual effect.

**Comment by neoancient** [comment]
The extra slots from patchwork are placed in the same location as the armor as a convenient way to track them, but should have no effect on anything else. It's not a problem to put them into the rotor, but the validation needs to ignore armor when checking for equipment in the rotor.
