### ISSUE TITLE
Double heatsinks incorrectly switching between Clan and IS versions

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megameklab#842]
On mixtech Mechs using Clan double heatsinks, some of them are sometimes transformed to IS double heatsinks (3 crits instead of 2). This usually happens on unassigning them from a location, or when changing engine size (and thus changing the number of heatsinks that do not occupy crit space).

I'm on version 0.47.14 on Windows 10 64-bit.

**Comment by neoancient** [comment]
I worked with this for a while but never saw the problem. Can you give me specific steps to reproduce it?

**Comment by alexbib** [comment]
Quickest way for me to reproduce it is to load a saved mixed IS mech with clan double HS (for instance the one I attached) and manually pull off a HS from its crit or reduce the mech's walking MP by 1.
[HSbug.zip](https://github.com/MegaMek/megameklab/files/5666057/HSbug.zip)

**Comment by neoancient** [comment]
That would be why I couldn't reproduce it. I think I know what the problem might be.
