### ISSUE TITLE
Talons not handled correctly for superheavies or tripods

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megameklab#844]
When saving a superheavy mech equipped with Talons, it does not pass validation (with the message "Talons require 2 critical slots in each leg", which is not true on superheavies, crit space being correctly halved by the program).

When attempting to load the save file, it does not load at all, giving the error message "Unable to load talons in non-Mek entity for New Mek".

Version 0.47.14 on Windows 10 64-bit.

**Comment by neoancient** [comment]
These are two separate issues. The error on loading is because the code that distributes the talons assumes mechs are either biped or quad.
