### ISSUE TITLE
MegaMek Lab - Aerodyne Roster Sheets

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#85]
Aerodyne Roster Sheet Fail to load (Mechbuster) and as such can't really be printed.  Not completely sure what is going on.

**Comment by HammerGS** [comment]
I can't duplicate this. Are you l using File->Print->Other Unit (Ctrl-O)?

[MechBuster (Standard).pdf](https://github.com/MegaMek/megameklab/files/1347682/MechBuster.Standard.pdf)

**Comment by FrozenIceman01** [comment]
No, I am using File\Load\From Cache\IS Introductory Box Set\Mechbuster (any)

Using 43.3

**Comment by neoancient** [comment]
Conventional fighter editing was added in 0.43.4. Prior to that you could only print a record sheet using File>Print.
