### ISSUE TITLE
Null Signature Vanishes the moment that I 

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#852]
So, I was modifying the Werewolf 005 when I discovered something: the Null Signature system completely vanishes whenever I modify the design on 0.47.15. Is this a bug or are there rules that simply make that happen?

**Comment by sixlettervariables** [comment]
Modify as in change the load out or simply open it up in MML?

**Comment by GamerFoxNeumann** [comment]
This happens if I change anything other than the amount of armor. Change weapons? Null Sig vanishes. Change tech from IS to IS Mixed? Vanishes. Change armor type? Vanishes.

Even when it vanishes, I can't replace the Null Sig system. It doesn't show up in the equipment section despite using the experimental tech rules.

**Comment by neoancient** [comment]
The null signature system is extinct between 2790 and ~3110. If you want to use it in in those years you need to enable the "show extinct tech" option.
