### ISSUE TITLE
Sniper and Thumper Artillery should be available for aerospace fighters

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megameklab#854]
### Environment
MML 47.6
### Description
Tacops pg 405
Thumper and Sniper artillery are available options for aerospace fighters.
They are not listed as available options in Megameklab even with "show unavailable" selected.

**Comment by HammerGS** [comment]
Per TO: AU&E - Conventional Artillery (Thumper/Sniper/Long Tom) are not available to ASF. But Artillery Cannons are they are listed under Ballistic Weapons.

![image](https://user-images.githubusercontent.com/13752452/103327027-1a883b80-4a10-11eb-9753-5189f62de836.png)
