### ISSUE TITLE
Can't find the External Hardpoints when building Aerospace/Conventional Fighters

### ISSUE THREAD

**Issue by GamerFoxNeumann** [MegaMek/megameklab#855]
Found this in 0.47.15. Whenever I use the Aerospace Fighter portion of the program, I discover that the external hardpoints don't show up even when using the 'show unavailable' option.

Is this a bug or has the construction rules changed in this regard?

**Comment by HammerGS** [comment]
TechManual pg 196 under External Stores. The come automatically with ASF's. The hardpoints are for Fixed wing support.
