### ISSUE TITLE
Cannot add more surgical theater of MASH

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/megameklab#856]
### Environment
Ver 0.47.15

### Description

Once were MASH divided to Core component and MASH Operation Theater, so I can put the additional MASH theater manually. But for now, Operation Theater is got removed and I can't put it at all. It seems that the number of MASH determines its theater and automatically calculate the tonnage, but on MegaMekLab you cannot change it at all - you cannot manually put the additional theater as the new items, each additional MASH Equipment just costs an another 3.5 tons and one slot, and the equipment has nothing to adjust its number of theater either.

**Comment by neoancient** [comment]
You need to set the size on the equipment tab.

**Comment by binaryspica** [comment]
Oh, I found how to do. I was think about right click on this on either equipment or assign Criticals tab, but it was on the item's size.
