### ISSUE TITLE
Aerospace Asset Armor Threshold

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#86]
The Threshold for Aerospace Assets are not changing to 10% (round up) of the armor value (Page 239 TW).  For example if you Modify an armor value on one of the sides from 40 to 41 or 49 to 50 the Theshold doesn't increase accordingly on the Printed Record Sheet.

**Comment by HammerGS** [comment]
MegaMekLab is currently getting a lot of work as we implement a editor for Large Space Craft and review the build options.  Leaving this open until that is finished.
