### ISSUE TITLE
Partial Wing on record sheet

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#869]
v.47.16

The location for Partial Wings under the "Weapons & Equipment Inventory" section of record sheets currently only lists one of the two side torsos.

Would it be possible to change this so that it's listed as being in both side torsos instead?

**Comment by HammerGS** [comment]
For Reference.
![image](https://user-images.githubusercontent.com/13752452/104824000-9d303980-580b-11eb-9609-4b8d10529c66.png)

**Comment by neoancient** [comment]
This is also true of talons and mech tracks, off the top of my head. I believe this is also true of the unit summary/TRO views as well.
