### ISSUE TITLE
 MegaMek Lab - Mad Cat IV unable to be opened

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#87]
Uncertain exactly what is going on but the Mad Cat IV causes the program to freeze/lock up if you attempt to open the Mad Cat IV.  It does not appear to be tied to Ferro Lamellor Armor as the Vulture IV opens up fine, current guess is it is tied to the XXL engine.

**Comment by HammerGS** [comment]
We need to log file to trouble shoot bugs like this.

https://github.com/MegaMek/megamek/wiki/Making-a-Bug-Report

**Comment by FrozenIceman01** [comment]
Certainly:

MegaMech Lab Version: 43.3

Image of screen when tried to open (About and Exit are able to be selected), see below.

![mml image when mad cat iv selected any variant](https://user-images.githubusercontent.com/32250003/30788492-bfa91c80-a151-11e7-8f4a-2308814c0043.png)

Log File generated on Close:

[megameklablog.txt](https://github.com/MegaMek/megameklab/files/1327941/megameklablog.txt)

**Comment by FrozenIceman01** [comment]
Certainly, comment added with log file and screen shots.

**Comment by HammerGS** [comment]
Which variant where you trying to load.  In the current unreleased builds they are loading.

**Comment by FrozenIceman01** [comment]
These variants are currently causing the issues:

Issues:
Mad Cat IV Prime, A, B, C

Load OK:
PR 2 and PR standard appears to open fine (both use XL engines).

**Comment by HammerGS** [comment]
No issues loading in the current releases for me.  The issues are fixed for the pending 0.43.4 release
