### ISSUE TITLE
Incorrect loaded design validation for clan LFC warship armor.

### ISSUE THREAD

**Issue by Dropskiler** [MegaMek/megameklab#872]
<v.47.16> 
Using maximal allowed tonnage for Clan Lamellor Ferro-Carbide armor type results in invalid unit warning on load attempt. In example: Lab calculates 275 tons of CLFC to 302 points but still expects only maximal amount of 275 points 1.0 multiplier instead of 1.1...
![image](https://user-images.githubusercontent.com/78222218/106297279-d2e51180-6252-11eb-892d-f13b46964703.png)

**Comment by HammerGS** [comment]
Was there a reason you closed this?

**Comment by Dropskiler** [comment]
My fault had tab open on second monitor.

**Comment by Dropskiler** [comment]
Done > I was able to recreate it on other machine and instalation.
[CLFC test ship Jumpship.zip](https://github.com/MegaMek/megameklab/files/5895088/CLFC.test.ship.Jumpship.zip)
