### ISSUE TITLE
Radical Heat Sinks are not being calculated correctly in Heat Generation/Heat Dissipation 

### ISSUE THREAD

**Issue by ShadowDefcon** [MegaMek/megameklab#875]
Windows 10
Megamek Labs bundled with MegaMek HQ 0.47.16
Java version 15.0.1

Radical Heat Sinks do not appear to be calculated correctly for Heat Generation/Heat Dissipation. Nor is it being printed correctly on the record sheet. Examples: I have a Super Heavy with 44 Double Heat Sinks and a Radical Heat Sink. MML is displaying Heat dissipation as being 106 instead of 132. An Assault Mech I have has 15 DHS and a RHS but the Heat Dissipation is only showing 36 instead of 45.  And Lastly, another Super Heavy with 31 DHS and a RHS and a Dissipation of 75 instead of 93. The Rules for RHS are they work like Coolant Pods and allow heat sinks dissipate 1 more point of heat per heat sink regardless of the type. So 44 DHS would dissipate an additional 44 points of heat for a total of 132(44*2+44)

**Comment by binaryspica** [comment]
> **Radical Heat Sinks**: When computing the heat sink capacity of a unit using the Radical Heat Sink System, multiply the unit's normal heat sink capacity by 1.4, and round up to the nearest whole number. This multiplier applies in addition to any others for special heat sink types (such as double heat sinks). For example, a unit with 15 double heat sinks and a Radical Heat Sink system would end up at a heat sink capacity of 36 for heat capacity purpose (15x2x1.4=36).

They just made it by follow the rules. Although I think that multiple of 1.5 is more reasonable, though, but by the rules 1.4 is correct.

In short, MageMekLab is actually calculates heat correctly.

**Comment by ShadowDefcon** [comment]
The entry you are quoting is under the Battle Value section for calculating Battle Value, not for the actual usage of the Radical Heat Sinks. Pg. 89, IO has the entry for the usage of Radical Heat Sinks. Not to mention that the example that is given in that entry is wrong. 15x2x1.4 is not 36. It is 42. Using that entry, the examples that I listed earlier still come up incorrect. 44x2x1.4=123.2 not 106 that is shown in Lab for example 1. Example 2: 15x2x1.4=42 not  36 which Lab shows, and the last example I gave 31x2x1.4=86.8 not 75 that Labs shows.

Radical Heat Sinks(Pg 89, IO)
Game Rules: The radical heat sink system works like the coolant pod(see pg. 304, TO). except that it can be activated more than once during a scenario. Unfortunately, repeated use of this system-especially in rapid succession-raises the chances for a catastrophic failure. 
A radical heat sink system may be triggered only once per turn-at the start of the unit's Heat Phase- and increases the cooling capacity of the unit's functioning heat sinks by 1 point each in that turn(regardless of heat sink type).

So going with the entry for how Radical Heat Sinks are used on pg 89, IO, the correct formula for the Heat Dissipated part of the Heat Profile should be (Heat Sinks x Heat Sink Type)+Heat Sinks.  And to be clear the following picture has the part I am referring to circled.

![MegaMek - HeatGen](https://user-images.githubusercontent.com/78337514/109116206-28a3c100-770e-11eb-83cd-bed48986a2b7.PNG)

**Comment by ShadowDefcon** [comment]
Gotcha. While I get your explanation, I don't understand their decision to have it display that way, but that is just me. Thanks

**Comment by binaryspica** [comment]
Well, I think that that's because it is the most neutral and sure standard. Even in the thread, you said the full effect on the triggered turn, and I said a half of heat dissipated by it(assumed that use it once per each two turns, for it never suffers a malfunction when used by each two turns). While both of them have the reasons, but if you have to choose only one then any rules reference about this is the most suitable choice.

The best option is also able to see how effective it is when it is used, but they are yet to making the refined version of heat display so I think that they are not ready for it right now.

**Comment by ShadowDefcon** [comment]
That's cool. I guess I am still used to how Heavy Metal dealt with it. You could choose to have it display and print the maximum heat the unit was capable of generating or you could choose different options. I wrongly assumed that the devs for MegaMek Lab was aiming for total heat. That was the error on my part.
