### ISSUE TITLE
RFE - ComStar Infantry Platoons 6 Squads of 5 Troopers

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megameklab#876]
### Environment
46.17
### Description
MegaMek Lab allows only a maximum of 30 troopers in a Platoon.  Is it possible to change this to allow 6 squads of 6 (36 troopers) fro ComStar Level I's?

**Comment by HammerGS** [comment]
Tech Manual pg 146 - Oversized Platoons.  They would need to be broken down into 2 units of 18 (for example)
