### ISSUE TITLE
RFE: Display armor and structure type on record sheets

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megameklab#877]
### Environment
0.47.16
Windows

### Description
Armor and Structure type are not listed on the exported/printed record sheets.

There is no way to tell if an industrial mech has heavy industrial armor or light industrial armor.  If you want to determine if a suit has Industrial or Heavy Industrial, you have to reverse engineer from how many armor points it has.  

The armor that take up crit slots can be determined that way, but it would be more user friendly if it was listed in one specific spot.

Commercial armor looks like it drops the info between the mechs legs on the diagram, and the BAR below that.

Instead, the "Armor Diagram" and "Internal Structure Diagram" text headers, could instead list the type of armor and internal structure.

### Files
An example of changing the headers, to show the armor and structure types.

![changedHeaders](https://user-images.githubusercontent.com/33232503/106535968-0c20ba00-64bd-11eb-9a9b-e91fed272764.png)

**Comment by neoancient** [comment]
Record sheets are not meant to show complete construction details. The type of armor and structure is shown when it has a game effect. Industrial and heavy industrial are functionally the same.

**Comment by Morkath** [comment]
> 
> 
> Record sheets are not meant to show complete construction details. The type of armor and structure is shown when it has a game effect. Industrial and heavy industrial are functionally the same.

Hardened?  FeroLamallar?  Reflective?  Reactive?

**Comment by Morkath** [comment]
It would also make it easier in campaigns, for determining what type of armor you need to purchase to repair it.
