### ISSUE TITLE
RFE: Move BAR location on support vehicle record sheets to improved location

### ISSUE THREAD

**Issue by Morkath** [MegaMek/megameklab#878]
### Environment
0.47.16
Windows

### Description
The BAR data field on support vehicle record sheets is in an awkward position, and difficult to see.  It is currently right next to the large Battletech logo, which makes it difficult to quickly parse.

It would be helpful if it was moved to a more easily visible location.  Possible locations are above the "Armor Diagram" field, or in the "Vehicle Data" box, below the "Rules Level" entry.

### Files
Current Location: 
![barLocation](https://user-images.githubusercontent.com/33232503/106537059-31162c80-64bf-11eb-9685-537963dec7d8.png)

Improved Location Options: 
![barLocation_improved](https://user-images.githubusercontent.com/33232503/106537074-3b382b00-64bf-11eb-8319-e81db8f59a91.png)

**Comment by neoancient** [comment]
This is entirely subjective. I don't see a problem with where it is. Your proposed location would require resizing the armor diagram and creating more whitespace instead of using what is already there.

**Comment by Morkath** [comment]
Putting it in the Vehicle Data box, which already has a giant white space of area would require resizing?

And no, it's not really subjective.  Putting small text right after a block of giant text and under/next to a small superscript, is bad design.
