### ISSUE TITLE
MegaMek Lab - Resolution Resize Issue on Advanced Search on small monitors

### ISSUE THREAD

**Issue by FrozenIceman01** [MegaMek/megameklab#88]
On monitors with a resolution of 1366x768 or less the advanced search button (File\Load\From Cache) the area on the bottom (Okay and cancel buttons) are unable to be seen.  The advanced Search menu can not be resized and as such the Okay button can not be selected.

**Comment by Dylan-M** [comment]
While it should be resizable, there is usually a minimum size. It may be that our current minimum resolution expectations are higher than the resolution you're running on. There aren't many people running on such low resolutions anymore, and many of our dialogs take up a lot of space to avoid having a lot of scrollbars all over them. Feel free to submit a PR, but I think this will be considered pretty low priority.

**Comment by sixlettervariables** [comment]
That form is part of the MegaMek repository, and is currently marked as not resizable. I've got it to ~740px and allowed resizing.

**Comment by NickAragua** [comment]
Addressed with megamek PR #1070
