### ISSUE TITLE
Battle armor AP weapon weight disappearing

### ISSUE THREAD

**Issue by alexbib** [MegaMek/megameklab#883]
The weight of anti-personnel weapons on a battle armor disappears once they are mounted (either on AP mount or in gloves).

v0.47.17

**Comment by neoancient** [comment]
See TM, p. 271

**Comment by alexbib** [comment]
Unless my edition of Tech Manual is outdated, it says AP weapons take no additional slots, not no additional weight:
"Anti-personnel weapons placed in an AP mount take up no additional weapon slots beyond those of the mount itself (see Modular Weapon Mounts, p. 263). The weight of any given AP weapon and its ammunition may be found on the Conventional Infantry Weapons and Equipment Table (p. 349)."

**Comment by neoancient** [comment]
When using an older edition check the errata.
From the 3rd ed., corrected:
"... the weight of these weapons and any 
ammunition required is never counted towards a battlesuit’s weight limits."

**Comment by alexbib** [comment]
Ah, ok, thanks!
