### ISSUE TITLE
Heat Sink/Laser Insulator Interaction on Vehicles

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#885]
v47.17

When multiple lasers weapons are mounted in a vehicle's location alongside multiple laser insulators, MML is currently only detecting one of the insulators for the purposes of eliminating heat sink requirements.

For example, this test fusion-engine'd vehicle mounts two large lasers (normally requiring 6 extra heat sinks) alongside two laser insulators (reducing overall heat generation by one per large laser). However, MML only drops the heat sink count down to 5 instead of bringing it down to 4.

[Insulator Test.zip](https://github.com/MegaMek/megameklab/files/6032992/Insulator.Test.zip)

**Comment by neoancient** [comment]
MM currently expects the laser insulator to come immediately after the laser. That order is determined by when they are added when first creating or modifying the unit, then on their slot placement when the unit is reloaded. I've reworked that section to make it less demanding.
