### ISSUE TITLE
Minor Chassis Availability Issues

### ISSUE THREAD

**Issue by ZPointZ** [MegaMek/megameklab#889]
### Environment
MekHQ 0.47.17
Windows 10 10.0
Java 1.8.0_281

### Description
- **Checked using "Standard" Tech Level:** Light Fusion Engines are available from 3050 when the design was first rumored to exist in 3053 and stolen from Wolf's Dragoons in 3058 by the Lyrans (_Field Manual: Lyran Alliance_, p. 147). It became available to the FedCom in 3062 (_TechManual_, p. 214, 2020 ed.: "Light engines"). The Wobbies immediately stole the design from the FedCom in the same year (_Technical Readout: 3067_, pp. 64-65). The DC and FWL got them by 3066 after the Dragoons sold it to them, and they were also selling them to anyone but the Wobbies and Trinity Alliance after that year (_Technical Readout: Project Phoenix_, pp. 26, 56), which covers the Capellans, etc. Perhaps they could be Experimental in 3053, Advanced in 3058 or 3062, and Standard by 3066?
- **Checked using "Standard" Tech Level:** Compact Engines are available from 3055 when they first became available in 3068 to the Lyrans (_TechManual_, p. 214, 2020 ed.: "Compact engines"). 
- **Checked using "Experimental" Tech Level:** Extra-Extralight Engines are available from 3050 when they first became available in 3055 to the FedCom (_Tactical Operations: Advanced Units & Equipment_, p. 121, 2020 ed).
- **Checked using "Standard" Tech Level:** Extralight Gyros, Compact Gyros, and Heavy-Duty Gyros are all available from 3050 when they first became available in 3067 (Heavy: DC; XL: C*) and 3068 (Compact: FS & LA) (_TechManual_, pp. 219-220, 2020 ed.).
- **Checked using "Standard" Tech Level:** Small Cockpits are available from 3055 when they first became available in 3067 to the FedSuns (_TechManual_, p. 211, 2020 ed.: "Small Cockpit").
- **Checked using "Standard" Tech Level:** Triple Strength Myomer is available from 3023 when it first became available only to the Capellan Confederation in 3028, but this was a non-production grade prototype called TSM-X (_Interstellar Operations_, p. 103, 2016 ed.). Standard production of TSM would only begin in 3050 (_TechManual_, pp. 240, 2020 ed.). The Federated Suns were deploying the prototype TSM-X on IndustrialMechs only in 3045 (_Ibid._) while the Capellans were using it on BattleMechs (_IO_, p. 103). Current _IO_ errata doesn't change anything.
- **Checked using "Standard" Tech Level:** I left this until last because it's an interesting one. Endo-Steel is available from 3035 when it first became available in 3040, and prototype ES is available from 3030 when it's first available in 3035. The _TechManual_ (p. 224, 2020 ed.) lists ES as recovered by the Draconis Combine in 3035; however, _Interstellar Operations_ (p. 103, 2016 ed.) says that prototype ES-P was available in 3035; Standard production is listed as 3040 in the DC. Since only _IO_ makes mention of prototype ES, I would suggest shifting the dates for both prototype and standard forward 5 years in MML. Current _IO_ errata doesn't change anything.

That's everything that I could spot, disregarding experimental engine types like ICE which I left alone. I first noticed a few of these and then decided to do a more comprehensive check.

**Comment by HammerGS** [comment]
There are two tech level validations in MML.  The simple one is by default and uses static tech for equipment.  So most things in Tech Manual are Standard. Most things in TO/SO/IO will be Advanced or Experimental.

What you are describing is enable using variable tech level in the options. Which uses the IO tables.

We don't have Prototype TSM coded for either construction or use.

**Comment by ZPointZ** [comment]
"What you are describing is enable using variable tech level in the options. Which uses the IO tables."
That is simply not true. I'm using the same settings I've always used.
![image](https://user-images.githubusercontent.com/73061772/109875360-57400f80-7cab-11eb-9d2d-8fb1eaa07bea.png)
This can easily be confirmed by checking it yourself, because it's all there.
![image](https://user-images.githubusercontent.com/73061772/109876259-899e3c80-7cac-11eb-988b-f322e36cd2c8.png)

**Comment by HammerGS** [comment]
Turn on Variable Tech Level.

**Comment by ZPointZ** [comment]
Okay, I understand now. My apologies.

**Comment by ZPointZ** [comment]
> The simple one is by default and uses static tech for equipment. So most things in Tech Manual are Standard. Most things in TO/SO/IO will be Advanced or Experimental.
Hang on, since I went through the static, default setting on Standard, then why doesn't it match up with the _TechManual_? Most of what I went through referred to it. I get now that to use Variable Tech Level you need the box checked, but that uses IO tables, right, so that would be completely different.
