### ISSUE TITLE
Aero recordsheet not printing

### ISSUE THREAD

**Issue by vizax** [MegaMek/megameklab#9]
As discussed in PR #8, Aero record sheets are not printing. Hopefully this is an issue isolated to me, and I'm doing something wrong, but don't know yet.

Steps to reproduce:
- Open MML
- File | Switch unit type | choose Aero
- [optional] fill in as much data as you want
- File | Print |Current Unit

Expected outcome: A print of the record sheet

Actual outcome: MML and printer just sits and does nothing. (I've let it sit for up to 15 minutes)

Stepping through the code in debug mode, I see it hangup as in the below screenshot.
![debug clip](https://cloud.githubusercontent.com/assets/1894549/14020531/9509bb68-f1a5-11e5-8f2f-407b35bcb3b8.PNG)

**Comment by arlith** [comment]
Can you see if you get the issue when running from the jar file?  Either a compiled jar, or download the release.

I found that I have problems printing Aero record sheets when I try in Eclipse, but if I built a jar and run it, it works.  I  think that the problems come from my paths in Eclipse.

That stack trace is kind of odd too.  It's stuck on a method outside of the project.

**Comment by arlith** [comment]
I can't seem to reproduce this issue.  I'm able to get ASF sheets to print fine.

**Comment by Dylan-M** [comment]
No response from OP, and developers unable to reproduce. Closing.
