### ISSUE TITLE
Fluff paragraph breaks: everything after gets deleted

### ISSUE THREAD

**Issue by SaAnAlstad** [MegaMek/megameklab#909]
### Environment
MekLab 0.49 (only stand-alone tested)
Win10
Java vendor AdoptOpenJDK
Java version 11.0.11

Note: "What java version are you using?  If unsure it will state your java version at the top of the megameklablog.txt file."
Correct file is megameklog.txt. The "blog" does NOT have the info.

### Description
In the fluff (only tested on support vessels), when a paragraph break (one open line) is used to separate paragraphs, everything after the first paragraph is lost when the file is saved. I have saved the file, closed MekLab, and then reopened both, to see the subsequent paragraphs were gone.

Recommendation: If this is known and/or cannot be resolved, suggest placing guidance under the fluff section titles:
Capabilities
(One paragraph only)

### Files
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/6480728/megameklablog.txt)
![Paragraph breaks](https://user-images.githubusercontent.com/84202318/118317297-dcbf1780-b4c5-11eb-9909-17a7e969fd32.png)

**Comment by Windchild292** [comment]
Duplicates https://github.com/MegaMek/megamek/issues/1757.

The log issue is another bug, which is known and IIRC open on the MM tracker.
