### ISSUE TITLE
Tech C Fusion Engines do not obey minimum weight rule

### ISSUE THREAD

**Issue by SaAnAlstad** [MegaMek/megameklab#910]
### Environment
MekLab 0.49 (only stand-alone tested)
Win10
Java vendor AdoptOpenJDK
Java version 11.0.11

### Description
In ML, fusion engines get cheaper the better their rating. For example, if the Engine Tech Rating is initially set to C, the overall cost of the vehicle will drop when it gets changed to D. Interestingly, when it then gets changed to E, the price doesn't change, but then a change to F has it drop again. 

### Files
![Fusion Engine Rating - C](https://user-images.githubusercontent.com/84202318/118320938-e7c87680-b4ca-11eb-9d83-f7ad041a76a2.png)
![Fusion Engine Rating - D](https://user-images.githubusercontent.com/84202318/118320939-e7c87680-b4ca-11eb-8a5b-63e5a3cf8db5.png)
![Fusion Engine Rating - E](https://user-images.githubusercontent.com/84202318/118320940-e7c87680-b4ca-11eb-91da-346d1425afad.png)
![Fusion Engine Rating - F](https://user-images.githubusercontent.com/84202318/118320937-e7c87680-b4ca-11eb-89ca-b001755720b8.png)
[megameklablog.txt](https://github.com/MegaMek/megameklab/files/6480888/megameklablog.txt)

**Comment by SJuliez** [comment]
The scaling as such is in line with the rules, TM rules p.280 and 127. The cost scales with engine weight which goes down with tech rating. When two tech ratings have the same weight and cost, it's due to rounding. What's wrong according to my understanding of the rules is that tech C fusion engines will have an absolute minimum weight of 5t according to TM p.126 but MML doesnt set this. It doesnt affect any current units though.

**Comment by HammerGS** [comment]
Hi, I wanted to double check this one again based on this forum post. 
https://bg.battletech.com/forums/non-combat-vehicles/pato-amphibious-plane-for-the-frontier/msg1865788/#msg1865788

When I checked our code I saw this.
![image](https://user-images.githubusercontent.com/13752452/189557395-bb162ff7-5602-4a49-bf50-7c600465ef8d.png)

But it references min weight as .5 tons not the pg 127 reference on Tech manual
![image](https://user-images.githubusercontent.com/13752452/189557441-f8bd27ff-1223-444e-b961-ca860f69b391.png)

But I could be misunderstanding the formulas.

**Comment by neoancient** [comment]
What's the issue? Lines 341-2 set the weight of D+ fusion engines to the calculated weight or 0.25t, whichever is greater. Lines 343-4 set the weight of fission and any other fusion engines to the greater of the calculated weight or 0.5t.

**Comment by neoancient** [comment]
Oh, I see. It's supposed to be 5 and not 0.5.
