### ISSUE TITLE
48.0+ RFE - Make "Use TRO format for summary" non-default

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megameklab#920]
Exactly what it says in the title. When sharing designs in the Discord chat, people often do so by File -> Export -> to Clipboard (text). I find that the non-TRO format is significantly more readable for this purpose, but the existence of the Configuration option is not obvious to a new user of MML, and even for veteran users it is one more thing to reset upon downloading a new version. Changing the default would alleviate this. Any users who do prefer the TRO format can of course still activate the option as normal. 

While I think this would be a useful QoL change, I am aware that it is a bit of a "matter of taste". Any comments?

**Comment by neoancient** [comment]
Preferences are subjective. The TRO is the universal standard format and will remain the default.
