### ISSUE TITLE
Targeting Computer gets (IS) tag on Record Sheet

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#921]
v.49.0

The Targeting Computer, when mounted on a purely Inner Sphere 'Mech, still has an (IS) tacked onto it on the Record Sheet as if it were mounted on a mixed-tech design. See: LGN-2N Legionnaire for a quick example.

The same occurs with mixed-tech designs using a Plasma Rifle, even though no canon Clan Plasma Rifle exists (and so no distinction should be needed.)

**Comment by HammerGS** [comment]
Fixed
