### ISSUE TITLE
UI QOL Request - Large Craft Ammunition Allocation

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megameklab#930]
The current way of allocating ammunition for large craft designs is very cumbersome and time-consuming.  Instead of using a right-click menu, I propose an input window asking how many shots to allocate to a firing arc.  See example below:

![image](https://user-images.githubusercontent.com/18338059/121813206-02f8e400-cc39-11eb-95f0-f06b6c8c89e5.png)

**Comment by neoancient** [comment]
Duplicate of #192
