### ISSUE TITLE
"Use Remaining Tonnage" button causes Issues in conjunction with ProtoMech's Myomer Booster

### ISSUE THREAD

**Issue by Skygallant** [MegaMek/megameklab#933]
### Environment
MegaMekHQ Meklab version 0.49.1
Windows 10 64bit
OpenJDK 11 LTS

### Description
I was playing with protomechs and I wanted to add a myomer booster. The booster weighs 375kg and I was looking for something to make up the 25kg i had left over. I noticed that if i press "use remaining tonnage" button while at 14975kg/15000kg it gave me an extra point of armor (bringing the total to 53) and only charge me 25kg instead of the full points cost of 50kg/point of armor and brings my total tonnage to 15000/15000.

Upon subsequent inspection, reloading the file into MMlabs causes an error to appear and once the file has loaded the correct tonnage of 15250kg displays.

### Files
Mech .blk in question:
http://skygallant.com/share/Enigma%20X14.blk

**Comment by neoancient** [comment]
The issue is that it tries to use all the remaining tonnage rather that a multiple of the weight of individual armor points.
