### ISSUE TITLE
Cannot open gun emplacements

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megameklab#936]
I was looking to create an "objective turret" in 49.2, something non-damaging that could be hidden and require exposing.  When I try to load any gun emplacement in the editor, it always throws up a pair of message dialogs:

![image](https://user-images.githubusercontent.com/70451747/125201686-6d4b7700-e22d-11eb-8879-85c1d9045c22.png)

![image](https://user-images.githubusercontent.com/70451747/125201743-9409ad80-e22d-11eb-8094-b2da400e2101.png)

Nothing is loaded into the editor.

**Comment by HammerGS** [comment]
Gun emplacements are not supported for construction in MegaMeklab. They need to be created by manually editing/creating a file.
