### ISSUE TITLE
Bug: If a cockpit variant is selected for a mech and the year changed to an unavailable one, it remains equipped

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/megameklab#941]
### Environment
Standalone MegaMekLab 0.49.2
Windows 10
What java version are you using?  If unsure it will state your java version at the top of the megameklablog.txt file. (not present in this file and is only in megameklog.txt)
AdoptOpenJDK Java version 11.0.11

### Description
When making or customising a Mech if you select a cockpit variant, for example the Small Cockpit and then change years so it becomes unavailable the dropdown menu changes, however, the Small cockpit remains the equipped head configuration until you go back into the dropdown menu and change it. This is true for all cockpit variants.

**Comment by Windchild292** [comment]
This has been resolved since then.
