### ISSUE TITLE
Bug: If the size of cargo is manually altered it soft reverts if moved in MML

### ISSUE THREAD

**Issue by SVNaas** [MegaMek/megameklab#942]
Version 0.49.2

If a cargo equipment is manually altered and the entity corrected slot wise, for example 2T is edited to two lines as:
Cargo:SIZE:2.0
Cargo:SIZE:2.0

It will display correctly in MML until moved via any means, at which point it will revert to one slot. Though it will still state the correct weight and slots required on the tooltip. Though if deleted or otherwise calculated the crits won't be calculated correctly allowing for an invalid design after being moved due to the reversion to one slot.

**Comment by HammerGS** [comment]
Closing as invalid. The unit in question is a super heavy.
