### ISSUE TITLE
C3 Master on Support Vehicle

### ISSUE THREAD

**Issue by foij00** [MegaMek/megameklab#944]
MMLab 49.2

Lab will not validate a support vehicle with a C3 Master Computer.
The Zugvogel A has a C3 Master, which MML says is invalid.
See attached screenshot.

My old version of TechManual (with Battlemaster on front), page 209 under "C3/C3I Computer" says "Support Vehicles require Advanced Fire Control Systems in order to be able to mount a C3 or C3i system of any kind".  The Zugvogel has an advanced fire control system.

![Clipboard01](https://user-images.githubusercontent.com/45526752/130717059-e3e1a667-f9df-4cb0-94f8-38247e3d38a4.jpg)

**Comment by SJuliez** [comment]
This issue appears solved by recent MM changes.
