### ISSUE TITLE
Infantry Platoon Tech

### ISSUE THREAD

**Issue by Bad-Syntax** [MegaMek/megameklab#946]
v0.48.0 of MML, don't think OS/java matters as app works fine.

So I design an infantry platoon:
Open MML
Select 'new infantry unit'
Change year to 1950
add 'Rifle (Sniper)' as primary weapon
Export->HTML

HTML shows tech D/D-D-D-D
Rifle (Sniper), page 350 of TM, states it is tech B, with C-C-C availability on page 300.

So the platoon should be B/C-C-C-C instead.

HOWEVER, if I change the date to, say 2500, which autochecks Anti-Mek Training, and then unselect that, and go back to 1950, change my primary back to sniper, then do a new export, my stats are now C/C-C-C-C which is still incorrect.

Not sure where it is getting a tech of 'C' from, as even giving the platoon shortbows only makes it C/A-A-A-A.

There is no validation for the tech/availability to see where it is failing at.

**Comment by neoancient** [comment]
1950 is outside the time frame of BattleTech.

**Comment by Bad-Syntax** [comment]
Uhh, the year has nothing to do with it, 1950 is 'pre-spaceflight' so I was filtering to get really old weapons that should be tech A or B.  Change it to 2500, use a short bow, still C/A-A-A, when it should be A/A-A-A.

**Comment by Bad-Syntax** [comment]
And heck, change it to 3145, add just a shortbow, and apparently shortbows are X availability for centuries:

New Infantry
Tech Base: Inner Sphere (Standard)
Tech Rating/Availability: C/X-X-X-A
Transport Weight: 2.5
Equipment:
     Primary Weapon: 28 Bow (Shortbow)
     Secondary Weapon: None
Battle Value: 42
Introduction Year: 3145
Cost: 177,087.549 C-bills
Notes: None
Platoon Type (Specialty): Foot (None)
     Ground MP: 1
Platoon Size (Squad/Platoon): 28 (7/4)
Armor Divisor: 1
To-Hit Modifier (Range in Hexes):
     +0 (0 Hexes)
Maximum Weapon Damage (# of Troopers):

**Comment by gsparks3** [comment]
> And heck, change it to 3145, add just a shortbow, and apparently shortbows are X availability for centuries:

This is the availability of the unit overall. It is unavailable in those eras because the introduction date is specified as past them.

**Comment by Bad-Syntax** [comment]
> > And heck, change it to 3145, add just a shortbow, and apparently shortbows are X availability for centuries:
> 
> This is the availability of the unit overall. It is unavailable in those eras because the introduction date is specified as past them.

Yeah, I was focusing on the tech rating not being correct, but was using 3145 as an example on the 1950 thing not being a thing.  

Though it would be nice to have a button for year as "earliest possible" for generic units or at least a year available calculation or something.  There are often times you may want to know if your unit could have been created earlier.

Outside of this particular bug, just sayin'.
