### ISSUE TITLE
Vehicle fusion engine weight calculated inconsistently

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megameklab#95]
When designing a VTOL, if the engine type is changed from ICE to fusion, the fusion engine weight shows as 50% that of the same size ICE. However, if the VTOL weight or MP is then changed (say increase either by one and then back to the original value), then the fusion engine shows as roughly 78% that of the same size ICE.

e.g. 25t VTOL, 10 MP ->  ICE, engine = 7t. Change fusion, engine = 3.5t, flip MP up and back, engine = 5.5t

Which is correct - should VTOL fusion be 50% of ICE or ~78% of ICE? (From looking at some of the built-in designs, it looks like ~78% of ICE is correct.)

Note: The same issue also exists with VTOL XL engines, and possibly the other advanced types.

**Comment by neoancient** [comment]
A fusion engine is half the weight of the equivalent ICE, but fusion and fission engines in vehicles require shielding to protect the crew equal to half the engine weight, so it should come out to 75% of the ICE weight, rounded up to the nearest half ton. The rounding makes it come out closer to 78%. What was happening here is that the tank flag wasn't getting set on the engine so when you changed the engine type, but it was getting set when the MP changed.
