### ISSUE TITLE
Superheavy tripod record sheets are generated with spaces for only two mechwarriors

### ISSUE THREAD

**Issue by pavelbraginskiy** [MegaMek/megameklab#965]
Here is a megamek superheavy tripod record sheet:
![image](https://user-images.githubusercontent.com/29113974/142729040-81176845-4631-497b-9902-39bb1d5a00ad.png)

However, a superheavy tripod mech has three mechwarriors. The blank record sheet found in Interstellar Operations has a warrior data segment that looks like this: 
![image](https://user-images.githubusercontent.com/29113974/142729092-6106c5bf-8104-4a9c-a74c-d539cb34951a.png)

**Comment by HammerGS** [comment]
Per bug report text - 
Version? 
Also attach your MTF file if a custom unit. 

As I can print an Ares with no issues.
[Ares ARS-V1C Aphrodite.pdf](https://github.com/MegaMek/megameklab/files/7574873/Ares.ARS-V1C.Aphrodite.pdf)

**Comment by pavelbraginskiy** [comment]
My bad, I had 48.0 but it is actually fixed in 49.5.
