### ISSUE TITLE
Artemis IV and Turrets

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#985]
v.49.2

Artemis IV and V systems do not currently count towards the total tonnage of a Shoulder Turret. For example, MML currently states that an LRM/20 with Art-IV (11 tons total) weighs an extra ton when mounted in a turret (only accounting for the LRM launcher) when it should weigh a total of 1.5.

**Comment by SJuliez** [comment]
Corrected by MM #3408
