### ISSUE TITLE
Errata - Turrets (Sponson, Shoulder, and Head turrets) need to include all equipment in turret for Turret Weight

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megameklab#988]
I know the base code is in MegaMek putting it here to make it easier to find. 

Here is the new wording that will replace the current wording on Tactical Operations: Advanced Units and Equipment, p.156.

_All of the turrets described here have a weight equal to 10 percent of the tonnage of all weapons and equipment assigned to the turret (not including power amplifiers, heat sinks and ammunition). Sponson Turrets—which are always mounted in pairs—do not have to assign the same tonnage of weapons and equipment in each Sponson, but must assign a total of 10 percent of the total tonnage for all Sponson-mounted weapons and equipment to their turret mechanism weight. Round all turret weights up to the nearest half-ton. For ’Mech Turrets, a critical slot must also be assigned to the unit’s record sheets to represent the turret mechanism (and the weapons and equipment assigned to that turret must be noted on the record sheet as well)._

This brings them inline with vehicle turrets.

**Comment by SJuliez** [comment]
Corrected by MM #3408
