### ISSUE TITLE
[0.43.4] VTOL tech base changes from "Mixed Inner Sphere" to "Clan" when tonnage changed

### ISSUE THREAD

**Issue by RexPearce** [MegaMek/megameklab#99]
When designing a Mixed Inner Sphere VTOL, changing the tonnage to a different value causes the tech base to reset to "Clan".

I've been changing the tonnage up/down to work around the engine weight bug described in issue #95 when a chin turret is present to work around issue #98. The combination of these three issues means it's not possible currently to create a mixed IS VTOL with a chin turret and have a correct weight fusion/XL engine.

(...and there goes my plans to mount my newly captured cER PPC in a turret on a Kestrel!)

**Comment by neoancient** [comment]
This was fixed in 55588a4.
