### ISSUE TITLE
Record Sheets - Incorrect Armor Totals

### ISSUE THREAD

**Issue by AlphaSled** [MegaMek/megameklab#992]
v.49.6

Certain vehicular record sheets are displaying incorrect armor point totals, occasionally alongside text glitches.

Examples: 
[Huitzilopochtli Assault Tank 'Huey' (Standard).pdf](https://github.com/MegaMek/megameklab/files/7798254/Huitzilopochtli.Assault.Tank.Huey.Standard.pdf)
[Shillelagh Missile Tank.pdf](https://github.com/MegaMek/megameklab/files/7798255/Shillelagh.Missile.Tank.pdf)
[Fury Command Tank (Fury IIIm).pdf](https://github.com/MegaMek/megameklab/files/7798256/Fury.Command.Tank.Fury.IIIm.pdf)

**Comment by SJuliez** [comment]
I can't find any armor point errors nor text glitches.
![image](https://user-images.githubusercontent.com/17069663/147910219-ce154f09-8036-4921-87a8-de8c19d2ec7b.png)

**Comment by AlphaSled** [comment]
What the...

Apologies, looks like it was a visual bug on my end. No idea what happened. This can be closed.
