### ISSUE TITLE
Bug: physical weapon placement on quad mechs

### ISSUE THREAD

**Issue by pinguspangus** [MegaMek/megameklab#996]
### Environment
Standalone Meklab 0.49.6
Windows 10

### Description
Currently quads can mount quite a few of the melee weapon options in invalid locations, below is a mech I've made to try and show off all of the current issues I could find. 
This design is invalid as meklab does flag multiple physical weapons in the same location, but still lets me place some weapons like hachets, swords, lances, and vibroblades in any location. 
(This whole discovery arose from making a head-mounted lance rhino mech)
In megamek games these incorrectly placed weapons are ineffective (the to hit roll is "impossible: attacker is quad") but the attacks are still available to be selected like they are functioning
![image](https://user-images.githubusercontent.com/97119120/148100700-ec80afc1-4305-4d1a-a276-20a8ca450dab.png)

### Files
[Chainsaw Legs Jim OOPS-1.txt](https://github.com/MegaMek/megameklab/files/7809419/Chainsaw.Legs.Jim.OOPS-1.txt)

**Comment by SJuliez** [comment]
This should be resolved with recent equiment validation changes in MegaMek.
