### ISSUE TITLE
TAG not available for Fixed Wing Support Vehicles

### ISSUE THREAD

**Issue by pokefan548** [MegaMek/megameklab#999]
### Environment
MegaMek Lab ver. 0.48.0, Windows 10

### Description
MegaMek Lab erroneously does not allow TAG to be mounted on Fixed-Wing Support Vehicles. Per TechManual p. 238, there is nothing precluding any unit from mounting TAG.

**Comment by SJuliez** [comment]
Should be fixed by #3389 of MM
